### ISSUE TITLE
[Bug] WildcardProcessor: Invalid literal for int() with base 10 in f577d97 update

### ISSUE THREAD

**Issue by Chubbly** [ltdrdata/ComfyUI-Impact-Pack#101]
The [f577d97](https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/f577d974a64b849a89ff85d5dcd283ffbffe9fd9) update has broken the ImpactWildcardProcessor node, stacktrace below

```
Error handling request
Traceback (most recent call last):
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 178, in populate_wildcards
    populated = wildcards.process(data['text'])
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 83, in process
    pass1, is_replaced1 = replace_options(text)
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 55, in replace_options
    replaced_string = re.sub(pattern, replace_option, string)
  File "re.py", line 209, in sub
  File "C:\Users\hoffl\Stable Diffusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 41, in replace_option
    config_value = int(parts[0])
ValueError: invalid literal for int() with base 10: 'Small Dog'
```

The text in the User Input text area is ({Small Dog:0.6|Large Cat:0.65|Tiger:0.6}), using the populate option.

**Comment by ltdrdata** [comment]
I'd fixed it. Thank you for the report.
