### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by jilt** [ltdrdata/ComfyUI-Impact-Pack#106]
Having issues with the manual installation too:
````
### Loading: ComfyUI-Impact-Pack (V3.20)
## ComfyUI-Impact-Pack: Updating dependencies
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: Updating subpack
Traceback (most recent call last):
  File "D:\sdxl\ComfyUI\ComfyUI\nodes.py", line 1647, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\__init__.py", line 39, in <module>
    do_install()
  File "D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\__init__.py", line 33, in do_install
    spec.loader.exec_module(impact_install)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 177, in <module>
    install()
  File "D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 164, in install
    ensure_subpack()
  File "D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 37, in ensure_subpack
    repo = git.Repo(os.path.dirname(__file__))
  File "D:\sdxl\ComfyUI\python_embeded\lib\site-packages\git\repo\base.py", line 265, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main

Cannot import D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main module for custom nodes: D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main
D:\sdxl\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions-main\extensions
D:\sdxl\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions

Import times for custom nodes:
   0.0 seconds: D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ksampler_sdxl.py
   0.0 seconds: D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Bmad-DirtyUndoRedo
   0.0 seconds: D:\sdxl\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions-main
   0.0 seconds: D:\sdxl\ComfyUI\ComfyUI\custom_nodes\AIT-main
   0.0 seconds: D:\sdxl\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.3 seconds (IMPORT FAILED): D:\sdxl\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main
````

Thank you so much for your work

**Comment by ltdrdata** [comment]
Your installation method isn't valid.
I recommend you that install through ComfyUI-Manager.

**Comment by jilt** [comment]
Thank you!
