### ISSUE TITLE
Error when using 'Open in SAM detector' with directml installed for amd support

### ISSUE THREAD

**Issue by felkami** [ltdrdata/ComfyUI-Impact-Pack#110]
card: AMD Ryzen 2700
Using comfyui standalone and torch-directml
comfyui initiated with the --directml switch only
comfyui is latest version with python dependencies updated. No other nodes installed except manager and impact-pack

From the 'Load Image' widget, right click and select 'Open in SAM Detector'
put a blue dot anywhere on picture and click 'Detect'

Error is generated:
```
ComfyUI-Impact-Pack: Loading SAM model 'C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\ComfyUI\models'
ComfyUI-Impact-Pack: SAM model loaded.
Error handling request
Traceback (most recent call last):
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\ComfyUI\server.py", line 42, in cache_control
    response: web.Response = await handler(request)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 151, in sam_detect
    detected_masks = core.sam_predict(sam_predictor, points, plabs, None, threshold)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 218, in sam_predict
    cur_masks, scores, _ = predictor.predict(point_coords=point_coords, point_labels=point_labels, box=box)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\predictor.py", line 154, in predict
    masks, iou_predictions, low_res_masks = self.predict_torch(
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\predictor.py", line 222, in predict_torch
    sparse_embeddings, dense_embeddings = self.model.prompt_encoder(
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 155, in forward
    point_embeddings = self._embed_points(coords, labels, pad=(boxes is None))
  File "C:\Users\pmaso\Documents\Standalone Programs\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\prompt_encoder.py", line 89, in _embed_points
    point_embedding[labels == 0] += self.point_embeddings[0].weight
RuntimeError: The size of tensor a (0) must match the size of tensor b (256) at non-singleton dimension 1
```

**Comment by ltdrdata** [comment]
update to latest version.
and edit impact-pack.ini such as below.

```
[default]
dependency_version = 9
mmdet_skip = True
sam_editor_cpu = True
sam_editor_model = sam_vit_b_01ec64.pth
```

You can set `sam_editor_cpu = True`

**Comment by felkami** [comment]
This worked! Thank you. You're amazing. <3
