### ISSUE TITLE
Hi, I have an issue for DetailerForEach Node

### ISSUE THREAD

**Issue by Clelstyn** [ltdrdata/ComfyUI-Impact-Pack#127]
Hi, Itdrdata.

I got an issue after the last update. Any help?

!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\AI\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 668, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 593, in do_detail
    enhanced_pil = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 182, in enhance_detail
    refined_latent = nodes.KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise)[0]
  File "E:\AI\ComfyUI\nodes.py", line 1207, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "E:\AI\ComfyUI\nodes.py", line 1177, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\hacky.py", line 22, in informative_sample
    raise e
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\hacky.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "E:\AI\ComfyUI\comfy\sample.py", line 82, in sample
    models, inference_memory = get_additional_models(positive, negative, model.model_dtype())
  File "E:\AI\ComfyUI\comfy\sample.py", line 56, in get_additional_models
    control_nets = set(get_models_from_cond(positive, "control") + get_models_from_cond(negative, "control"))
  File "E:\AI\ComfyUI\comfy\sample.py", line 50, in get_models_from_cond
    if model_type in c[1]:
  File "E:\AI\ComfyUI\venv\lib\site-packages\torch\_tensor.py", line 1061, in __contains__
    raise RuntimeError(
RuntimeError: Tensor.__contains__ only supports Tensor or scalar, but you passed in a <class 'str'>.

![workflow (2)](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/141990218/7b940e3a-ecbb-4a81-b9f2-522fcfea66e0)

This is a simple inpaint workflow using the DetailerForEach node.
When I run it after specifying the mask region, I get the the error in the DetailerForEach node.

**Comment by ltdrdata** [comment]
How did you connect `Text box`'s `STRING` output to ToBasicPipe?
It isn't allowed..

ToBasicPipe requires `CONDITIONING` not a text.

**Comment by Clelstyn** [comment]
<img width="539" alt="image" src="https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/141990218/94e47232-6e82-4995-9579-16004204a5b7">
It actually hides behind the node.
It's not a Text box's STRING that's connected to the ToBasicPipe, it's CONDITIONING

**Comment by Clelstyn** [comment]
Oh, I think I've fixed this.

The problem seems to be with the Text to Conditioning node that connects to the ToBasicPipe.

I think this is probably another custom node.

I replaced it with the default node, the CLIP Text Encode (Prompt) node, and it worked fine.

Thanks.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/141990218/dffaac49-8374-4855-b1fb-52542572abd8)
