### ISSUE TITLE
SAM Editor error

### ISSUE THREAD

**Issue by Lunedor** [ltdrdata/ComfyUI-Impact-Pack#129]
When I open an image with SAM editor I got following error and it is not select anything in image;

FETCH DATA from: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json
ComfyUI-Impact-Pack: Loading SAM model '/content/drive/MyDrive/ComfyUI/models'
ComfyUI-Impact-Pack: SAM model loaded. 
Exception in thread Thread-3 (async_prepare_sam):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_server.py", line 70, in async_prepare_sam
    sam_model = sam_model_registry[model_kind](checkpoint=model_name)
  File "/usr/local/lib/python3.10/dist-packages/segment_anything/build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
  File "/usr/local/lib/python3.10/dist-packages/segment_anything/build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 797, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/usr/local/lib/python3.10/dist-packages/torch/serialization.py", line 283, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory

**Comment by ltdrdata** [comment]
It seems your SAM model file is corrupted. Remove it(ComfyUI/models/sams) and install through ComfyUI-Manager's "install models" menu.

**Comment by Lunedor** [comment]
Thank you so much, that solved the problem.

**Comment by Lunedor** [comment]
Thank you so much, that solved the problem.
