### ISSUE TITLE
Install Error (Github Repo)

### ISSUE THREAD

**Issue by aaron9412** [ltdrdata/ComfyUI-Impact-Pack#134]
Please see the following output. Some issue with a github repository name maybe?
Windows 10, had impact pack installed before (updating from around May2023).
Just ran comfyui update script.

Please help. Thank you! -Aaron

D:\>cd D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main

D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main>..\..\..\python_embeded\python.exe install.py
### ComfyUI-Impact-Pack: Updating subpack
Traceback (most recent call last):
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 177, in <module>
    install()
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 164, in install
    ensure_subpack()
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\install.py", line 37, in ensure_subpack
    repo = git.Repo(os.path.dirname(__file__))
  File "D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\git\repo\base.py", line 265, in __init__
    raise InvalidGitRepositoryError(epath)
git.exc.InvalidGitRepositoryError: D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main

D:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main>

**Comment by ltdrdata** [comment]
You should not install by download.
Install through git clone otherwise use ComfyUI-Manager

**Comment by aaron9412** [comment]
Oh.. yeah that does it. Sorry I didn't know there was a difference. Thank you for your time ltdrdata.
