### ISSUE TITLE
Numerous errors occurred after the update

### ISSUE THREAD

**Issue by hahajaja** [ltdrdata/ComfyUI-Impact-Pack#142]
```
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: Updating subpack
Traceback (most recent call last):
  File "D:\ComfyUI\ComfyUI\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 39, in <module>
    do_install()
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 33, in do_install
    spec.loader.exec_module(impact_install)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 177, in <module>
    install()
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 164, in install
    ensure_subpack()
  File "D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 40, in ensure_subpack
    repo.git.submodule('update', '--init', '--recursive')
  File "D:\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 741, in <lambda>
    return lambda *args, **kwargs: self._call_process(name, *args, **kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 1315, in _call_process
    return self.execute(call, **exec_kwargs)
  File "D:\stable-diffusion-webui\venv\lib\site-packages\git\cmd.py", line 1109, in execute
    raise GitCommandError(redacted_command, status, stderr_value, stdout_value)
git.exc.GitCommandError: Cmd('git') failed due to: exit code(254)
  cmdline: git submodule update --init --recursive
  stderr: '      0 [main] sh 750 dofork: child -1 - forked process 16716 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
1016287 [main] sh 750 dofork: child -1 - forked process 1820 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh 751 dofork: child -1 - forked process 16524 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
1019127 [main] sh 751 dofork: child -1 - forked process 13636 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
3027249 [main] sh 751 dofork: child -1 - forked process 16128 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
7043342 [main] sh 751 dofork: child -1 - forked process 1632 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
15052973 [main] sh 751 dofork: child -1 - forked process 11876 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable
      0 [main] sh (8388) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1751408/0x1771408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
18101325 [main] sh 750 dofork: child -1 - forked process 8388 died unexpectedly, retry 0, exit code 0xC0000142, errno 11/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
19115710 [main] sh 750 dofork: child -1 - forked process 11228 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      1 [main] sh (11620) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1751408/0x17F1408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
21122173 [main] sh 750 dofork: child -1 - forked process 11620 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (16312) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1751408/0x1761408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
25129386 [main] sh 750 dofork: child -1 - forked process 16312 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
33137866 [main] sh 750 dofork: child -1 - forked process 7412 died unexpectedly, retry 0, exit code 0xC0000142, errno 11/mingw64/libexec/git-core/git-sh-setup: fork: Resource temporarily unavailable'

Cannot import D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: Cmd('git') failed due to: exit code(254)
  cmdline: git submodule update --init --recursive
  stderr: '      0 [main] sh 750 dofork: child -1 - forked process 16716 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
1016287 [main] sh 750 dofork: child -1 - forked process 1820 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
      0 [main] sh 751 dofork: child -1 - forked process 16524 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
1019127 [main] sh 751 dofork: child -1 - forked process 13636 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
3027249 [main] sh 751 dofork: child -1 - forked process 16128 died unexpectedly, retry 0, exit code 0xC0000142, errno 11C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
7043342 [main] sh 751 dofork: child -1 - forked process 1632 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: retry: Resource temporarily unavailable
15052973 [main] sh 751 dofork: child -1 - forked process 11876 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
C:/Program Files/Git/mingw64/libexec/git-core\git-submodule: fork: Resource temporarily unavailable
      0 [main] sh (8388) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1751408/0x1771408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
18101325 [main] sh 750 dofork: child -1 - forked process 8388 died unexpectedly, retry 0, exit code 0xC0000142, errno 11/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
19115710 [main] sh 750 dofork: child -1 - forked process 11228 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      1 [main] sh (11620) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1751408/0x17F1408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
21122173 [main] sh 750 dofork: child -1 - forked process 11620 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
      0 [main] sh (16312) C:\Program Files\Git\usr\bin\sh.exe: *** fatal error - cygheap base mismatch detected - 0x1751408/0x1761408.
This problem is probably due to using incompatible versions of the cygwin DLL.
Search for cygwin1.dll using the Windows Start->Find/Search facility
and delete all but the most recent version.  The most recent version *should*
reside in x:\cygwin\bin, where 'x' is the drive on which you have
installed the cygwin distribution.  Rebooting is also suggested if you
are unable to find another cygwin DLL.
25129386 [main] sh 750 dofork: child -1 - forked process 16312 died unexpectedly, retry 0, exit code 0xC0000142, errno 11
/mingw64/libexec/git-core/git-sh-setup: fork: retry: Resource temporarily unavailable
33137866 [main] sh 750 dofork: child -1 - forked process 7412 died unexpectedly, retry 0, exit code 0xC0000142, errno 11/mingw64/libexec/git-core/git-sh-setup: fork: Resource temporarily unavailable'
```

**Comment by ltdrdata** [comment]
delete `D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack` dir and
goto `D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\` in cmd

and then execute this
```
git reset --hard
git submodule update --init --recursive
```

Check the message. If there are no errors, give restarting ComfyUI a try, and if there are errors, please leave a message.

**Comment by ltdrdata** [comment]
To address the installation issue, I've made changes to the internal structure. Try reinstalling the Impact Pack, and it should no longer cause any problems.

**Comment by hahajaja** [comment]
Thx! ^_^
