### ISSUE TITLE
New error stopping initialization (windows, venv)

### ISSUE THREAD

**Issue by rgthree** [ltdrdata/ComfyUI-Impact-Pack#144]
Not sure what my previous working version was, but when I updated ComfUI-Impact-Pack no longer initializes with an error in `__init__.py`

```
### ComfyUI-Impact-Pack: Check dependencies
Traceback (most recent call last):
  File "C:\Users\rgthree\dev\stable-diffusion\comfyui\nodes.py", line 1698, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rgthree\dev\stable-diffusion\comfyui\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 38, in <module>
    do_install()
  File "C:\Users\rgthree\dev\stable-diffusion\comfyui\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 32, in do_install
    spec.loader.exec_module(impact_install)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\rgthree\dev\stable-diffusion\comfyui\custom_nodes\ComfyUI-Impact-Pack\install.py", line 188, in <module>
    install()
  File "C:\Users\rgthree\dev\stable-diffusion\comfyui\custom_nodes\ComfyUI-Impact-Pack\install.py", line 143, in install
    ensure_pip_packages_first()
  File "C:\Users\rgthree\dev\stable-diffusion\comfyui\custom_nodes\ComfyUI-Impact-Pack\install.py", line 81, in ensure_pip_packages_first
    subprocess.run(pip_install + ['openmim'], cwd=subpack_path)
  File "C:\Users\rgthree\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\rgthree\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\rgthree\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
NotADirectoryError: [WinError 267] The directory name is invalid
```

**Comment by rgthree** [comment]
(I've gotten around this by manually running the steps in that function, and then commenting it all out for Comfy's Startup).

**Comment by ltdrdata** [comment]
This issue is fixed

**Comment by ltdrdata** [comment]
This issue is fixed
