### ISSUE TITLE
I get an error when segmenting hands

### ISSUE THREAD

**Issue by mikheys** [ltdrdata/ComfyUI-Impact-Pack#153]
I'm trying to reproduce pipelines, but I get an error when segmenting the hands:
------------------------------------------
Detailer: segment upscale for ((79.41634, 55.34247)) | crop region (397, 276) x 1.9349510544749915 -> (768, 534)
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1733, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "C:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 621, in do_detail
    enhanced_pil, cnet_pil = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "C:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 228, in enhance_detail
    positive, cnet_pil = control_net_wrapper.apply(positive, upscaled_image)
  File "C:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1270, in apply
    image = self.preprocessor.apply(image)
  File "C:\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\segs_support.py", line 37, in apply
    return obj.estimate_pose(image, detect_hand, detect_body, detect_face)[0]
KeyError: 0
------------------------------------------
What could possibly be wrong? As I understand 534 is not a multiple of 64, although there may be something else wrong.
[- hand_fix.zip](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/12566592/-.hand_fix.zip)

**Comment by ltdrdata** [comment]
This is fixed. Update your `Inspire Pack`.
