### ISSUE TITLE
Today update has a problem "IndexError: tuple index out of range"

### ISSUE THREAD

**Issue by ffdown** [ltdrdata/ComfyUI-Impact-Pack#154]
```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\AI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 2206, in sample_adv
    return super().sample(sampler_state, model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "E:\AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 642, in sample
    samples = sample_latent_image(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "E:\AI\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 548, in sample_latent_image
    samples = KSamplerAdvanced().sample(model, add_noise, seed, steps, cfg, sampler_name, scheduler,
  File "E:\AI\ComfyUI\nodes.py", line 1270, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
  File "E:\AI\ComfyUI\nodes.py", line 1206, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "E:\AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\hacky.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "E:\AI\ComfyUI\comfy\sample.py", line 93, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "E:\AI\ComfyUI\comfy\samplers.py", line 740, in sample
    samples = getattr(k_diffusion_sampling, "sample_{}".format(self.sampler))(self.model_k, noise, sigmas, extra_args=extra_args, callback=k_callback, disable=disable_pbar)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\ComfyUI\comfy\k_diffusion\sampling.py", line 695, in sample_dpmpp_3m_sde_gpu
    return sample_dpmpp_3m_sde(model, x, sigmas, extra_args=extra_args, callback=callback, disable=disable, eta=eta, s_noise=s_noise, noise_sampler=noise_sampler)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\ComfyUI\comfy\k_diffusion\sampling.py", line 655, in sample_dpmpp_3m_sde
    denoised = model(x, sigmas[i] * s_in, **extra_args)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI\comfy\samplers.py", line 321, in forward
    out = self.inner_model(x, sigma, cond=cond, uncond=uncond, cond_scale=cond_scale, cond_concat=cond_concat, model_options=model_options, seed=seed)
  File "C:\Users\user\AppData\Roaming\Python\Python310\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI\comfy\k_diffusion\external.py", line 125, in forward
    eps = self.get_eps(input * c_in, self.sigma_to_t(sigma), **kwargs)
  File "E:\AI\ComfyUI\comfy\k_diffusion\external.py", line 151, in get_eps
    return self.inner_model.apply_model(*args, **kwargs)
  File "E:\AI\ComfyUI\comfy\samplers.py", line 309, in apply_model
    out = sampling_function(self.inner_model.apply_model, x, timestep, uncond, cond, cond_scale, cond_concat, model_options=model_options, seed=seed)
  File "E:\AI\ComfyUI\comfy\samplers.py", line 287, in sampling_function
    cond, uncond = calc_cond_uncond_batch(model_function, cond, uncond, x, timestep, max_total_area, cond_concat, model_options)
  File "E:\AI\ComfyUI\comfy\samplers.py", line 241, in calc_cond_uncond_batch
    c['control'] = control.get_control(input_x, timestep_, c, len(cond_or_uncond))
  File "E:\AI\ComfyUI\comfy\controlnet.py", line 139, in get_control
    control_prev = self.previous_controlnet.get_control(x_noisy, t, cond, batched_number)
  File "E:\AI\ComfyUI\comfy\controlnet.py", line 153, in get_control
    self.cond_hint = comfy.utils.common_upscale(self.cond_hint_original, x_noisy.shape[3] * 8, x_noisy.shape[2] * 8, 'nearest-exact', "center").to(self.control_model.dtype).to(self.device)
  File "E:\AI\ComfyUI\comfy\utils.py", line 351, in common_upscale
    old_width = samples.shape[3]
IndexError: tuple index out of range
```

ReCreate node not fix that.

**Comment by ltdrdata** [comment]
Share me the workflow. I'll check it.

**Comment by ffdown** [comment]
> Share me the workflow. I'll check it.

[Pastebin](https://pastebin.com/8gsmQtrR)

**Comment by ltdrdata** [comment]
It's not the impact pack issue. you need to report it to efficient nodes.
https://github.com/LucianoCirino/efficiency-nodes-comfyui

`hacky.py` serves the sole purpose of making error messages that occur when mixing incompatible models and clips easier for users to understand, without affecting the existing functionality in any way.

**Comment by ffdown** [comment]
> It's not the impact pack issue. you need to report it to efficient nodes. https://github.com/LucianoCirino/efficiency-nodes-comfyui
> 
> `hacky.py` serves the sole purpose of making error messages that occur when mixing incompatible models and clips easier for users to understand, without affecting the existing functionality in any way.

thanks
