### ISSUE TITLE
Installation issue

### ISSUE THREAD

**Issue by slowjonny** [ltdrdata/ComfyUI-Impact-Pack#169]
Hello there,
I'm having trouble installing the ComfyUI Impact Pack and the Inspire Pack via the Comfy UI Manager. I have tried uninstalling and reinstalling and trying installing via the git. But the same issues happen each time.
Thanks in advance for your help.

Here's the log file...

*** ComfyUI start up time: 2023-09-18 12:02:25.927835

Prestartup times for custom nodes:
   0.0 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\rgthree-comfy-main
   0.0 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 11264 MB, total RAM 64658 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2080 Ti : cudaMallocAsync
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.7.4)
Traceback (most recent call last):
  File "D:\pinokio\api\comfyui.pinokio.git\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 66, in <module>
    import impact.impact_server  # to load server api
  File "D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 243, in <module>
    server.PromptServer.instance.add_on_prompt_handler(onprompt)
AttributeError: 'PromptServer' object has no attribute 'add_on_prompt_handler'

Cannot import D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: 'PromptServer' object has no attribute 'add_on_prompt_handler'
### Loading: ComfyUI-Inspire-Pack (V0.14)
Traceback (most recent call last):
  File "D:\pinokio\api\comfyui.pinokio.git\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\__init__.py", line 24, in <module>
    imported_module = importlib.import_module(".{}".format(module_name), __name__)
  File "D:\pinokio\bin\python\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack\lora_block_weight.py", line 3, in <module>
    import comfy.lora
ModuleNotFoundError: No module named 'comfy.lora'

Cannot import D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack module for custom nodes: No module named 'comfy.lora'
### ComfyUI Revision: 1336 [443402c3]
Registered sys.path: ['D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\comfy', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\env\\lib\\site-packages\\git\\ext\\gitdb', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI', 'D:\\pinokio\\bin\\python\\python310.zip', 'D:\\pinokio\\bin\\python\\DLLs', 'D:\\pinokio\\bin\\python\\lib', 'D:\\pinokio\\bin\\python', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\env', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\env\\lib\\site-packages', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\env\\lib\\site-packages\\win32', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\env\\lib\\site-packages\\win32\\lib', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\env\\lib\\site-packages\\Pythonwin', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'D:\\pinokio\\api\\comfyui.pinokio.git\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', '../..']
[32m[1mrgthree's comfy nodes:[0m[1m Loaded 14 exciting nodes.[0m

Import times for custom nodes:
   0.0 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Image-Selector
   0.0 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\mikey_nodes
   0.0 seconds (IMPORT FAILED): D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\rgthree-comfy-main
   0.0 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.2 seconds (IMPORT FAILED): D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.2 seconds: D:\pinokio\api\comfyui.pinokio.git\ComfyUI\custom_nodes\ComfyUI-Manager

Starting server

**Comment by ltdrdata** [comment]
Your ComfyUI version is too old.
Update ComfyUI to latest version.
