### ISSUE TITLE
No module named 'impact.special_samplers'

### ISSUE THREAD

**Issue by qeoakes** [ltdrdata/ComfyUI-Impact-Pack#170]
Looks like a commit about an hour ago broke the ability for (me) to load the Impact Pack.

### Loading: ComfyUI-Impact-Pack (V4.8)
Traceback (most recent call last):
  File "H:\comfyui\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "H:\comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 99, in <module>
    from impact.special_samplers import *
ModuleNotFoundError: No module named 'impact.special_samplers'

Cannot import H:\comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'impact.special_samplers'
jjk_util loding

**Comment by noxouille** [comment]
I have the same issue.

**Comment by ghost** [comment]
Same issue
`### Loading: ComfyUI-Impact-Pack (V4.8)
Traceback (most recent call last):
  File "/home/scott/Various/ComfyUI/nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/scott/Various/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 99, in <module>
    from impact.special_samplers import *
ModuleNotFoundError: No module named 'impact.special_samplers'`

**Comment by 49RpK5dY** [comment]
Same here. Python 3.9.5 in docker if that matters.

**Comment by NicolasCampailla** [comment]
Same issue for me

**Comment by lord-lethris** [comment]
Same here 

```
### Loading: ComfyUI-Impact-Pack (V4.8)
Traceback (most recent call last):
  File "D:\apps\SD-WebUI\ComfyUI\nodes.py", line 1725, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\apps\SD-WebUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 99, in <module>
    from impact.special_samplers import *
ModuleNotFoundError: No module named 'impact.special_samplers'

Cannot import D:\apps\SD-WebUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'impact.special_samplers'
```

**Comment by ltdrdata** [comment]
It is just patched.. My fault...
