### ISSUE TITLE
Follow your step in the video in Youtube https://www.youtube.com/watch?v=DoyqCjKdojY

### ISSUE THREAD

**Issue by bartly** [ltdrdata/ComfyUI-Impact-Pack#174]
Traceback (most recent call last):
  File "/mnt/workspace/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/mnt/workspace/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/mnt/workspace/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 727, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 634, in do_detail
    enhanced_pil, cnet_pil = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 230, in enhance_detail
    refined_latent = ksampler_wrapper(model, seed, steps, cfg, sampler_name, scheduler, positive, negative,
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 47, in ksampler_wrapper
    nodes.KSampler().sample(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/mnt/workspace/ComfyUI/nodes.py", line 1211, in sample
    return common_ksampler(model, seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise)
  File "/mnt/workspace/ComfyUI/nodes.py", line 1181, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
  File "/mnt/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/hacky.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)
  File "/mnt/workspace/ComfyUI/comfy/sample.py", line 95, in sample
    samples = sampler.sample(noise, positive_copy, negative_copy, cfg=cfg, latent_image=latent_image, start_step=start_step, last_step=last_step, force_full_denoise=force_full_denoise, denoise_mask=noise_mask, sigmas=sigmas, callback=callback, disable_pbar=disable_pbar, seed=seed)
  File "/mnt/workspace/ComfyUI/comfy/samplers.py", line 637, in sample
    pre_run_control(self.model_wrap, negative + positive)
  File "/mnt/workspace/ComfyUI/comfy/samplers.py", line 481, in pre_run_control
    x[1]['control'].pre_run(model.inner_model.inner_model, percent_to_timestep_function)
  File "/mnt/workspace/ComfyUI/comfy/controlnet.py", line 269, in pre_run
    comfy.utils.set_attr(self.control_model, k, self.control_weights[k].to(dtype).to(comfy.model_management.get_torch_device()))
  File "/mnt/workspace/ComfyUI/comfy/utils.py", line 243, in set_attr
    obj = getattr(obj, name)
  File "/usr/local/lib/python3.10/dist-packages/torch/nn/modules/module.py", line 1614, in __getattr__
    raise AttributeError("'{}' object has no attribute '{}'".format(
AttributeError: 'ModuleList' object has no attribute '1'

**Comment by ltdrdata** [comment]
First, your Impact Pack is an old version. Please update all, ComfyUI and the Impact Pack, Inspire Pack and try again.
