### ISSUE TITLE
help ComfyUI-Impact-Pack module for custom nodes: 'PromptServer' object has no attribute 'add_on_prompt_handler'

### ISSUE THREAD

**Issue by caterilr** [ltdrdata/ComfyUI-Impact-Pack#177]
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 66, in <module>
    import impact.impact_server  # to load server api
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 243, in <module>
    server.PromptServer.instance.add_on_prompt_handler(onprompt)
AttributeError: 'PromptServer' object has no attribute 'add_on_prompt_handler'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: 'PromptServer' object has no attribute 'add_on_prompt_handler'

**Comment by ltdrdata** [comment]
Update your ComfyUI to latest version.

**Comment by caterilr** [comment]
ok,thanks
