### ISSUE TITLE
Help,I've upgraded to the latest version and I'm still getting errors

### ISSUE THREAD

**Issue by caterilr** [ltdrdata/ComfyUI-Impact-Pack#178]
### Loading: ComfyUI-Impact-Pack (V4.9.5)
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1693, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 66, in <module>
    import impact.impact_server  # to load server api
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 243, in <module>
    server.PromptServer.instance.add_on_prompt_handler(onprompt)
AttributeError: 'PromptServer' object has no attribute 'add_on_prompt_handler'

Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: 'PromptServer' object has no attribute 'add_on_prompt_handler'
### ComfyUI Revision: 1338 [e3d0a9a4]

Import times for custom nodes:
   0.3 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds (IMPORT FAILED): E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json

**Comment by ltdrdata** [comment]
Make sure the version of your "ComfyUI" not custom nodes. If you did it, already. It means updating is failed.

goto ComfyUI dir in cmd.

git reset --hard
git pull

**Comment by caterilr** [comment]
ok

**Comment by caterilr** [comment]
Error occurred when executing CLIPSegDetectorProvider:

object of type 'NoneType' has no len()

File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 96, in get_output_data
output_is_list = [False] * len(results[0])
It's already installed successfully, thanks, but this error came up again during use

**Comment by caterilr** [comment]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI_windows_portable\ComfyUI\execution.py", line 96, in get_output_data
    output_is_list = [False] * len(results[0])
TypeError: object of type 'NoneType' has no len()

**Comment by caterilr** [comment]
> Make sure the version of your "ComfyUI" not custom nodes. If you did it, already. It means updating is failed.
> 
> goto ComfyUI dir in cmd.
> 
> git reset --hard git pull

The problem has been resolved. Thank you for your answer
