### ISSUE TITLE
Error occurred when executing MaskToSEGS:cannot select an axis to squeeze out which has size not equal to one

### ISSUE THREAD

**Issue by tudal** [ltdrdata/ComfyUI-Impact-Pack#195]
White using even simples usage of node MaskToSEGS im instantly getting this error suddenly:

```
Error occurred when executing MaskToSEGS:

cannot select an axis to squeeze out which has size not equal to one

File "C:\m\pf\ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
File "C:\m\pf\ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
File "C:\m\pf\ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
File "C:\m\pf\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1856, in doit
result = core.mask_to_segs(mask, combined, crop_factor, bbox_fill, drop_size)
File "C:\m\pf\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 653, in mask_to_segs
mask = np.squeeze(mask, axis=1)
File "<__array_function__ internals>", line 180, in squeeze
File "C:\m\pf\ComfyUI\python_embeded\lib\site-packages\numpy\core\fromnumeric.py", line 1545, in squeeze
return squeeze(axis=axis)
```
I have everything updated

**Comment by ltdrdata** [comment]
Your `Impact Pack` is an **outdated** version. Please update both `ComfyUI` and the `Impact Pack` to the latest versions.
If you've already attempted the update, your update is failing. Please uninstall and reinstall.

If the update has been completed successfully, the ComfyUI startup message should display the version as follows:
```
### Loading: ComfyUI-Impact-Pack (V4.13.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.2)
### Loading: ComfyUI-Inspire-Pack (V0.21)
### Loading: ComfyUI-Manager (V0.32)
### ComfyUI Revision: 1513 on 'Main' [2ef459b1] | Released on '2023-10-01'
```

**Comment by tudal** [comment]
ah yea, my bad

**Comment by tudal** [comment]
ah yea, my bad

**Comment by ghost** [comment]
Got the same issue, even though I'm up to date.

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/drive/MyDrive/beinass/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/beinass/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/beinass/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/beinass/custom_nodes/ComfyUI-Impact-Pack/modules/impact/segs_nodes.py", line 925, in doit
    result = core.mask_to_segs(mask, combined, crop_factor, bbox_fill, drop_size)
  File "/content/drive/MyDrive/beinass/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 919, in mask_to_segs
    mask = np.squeeze(mask, axis=1)
  File "<__array_function__ internals>", line 180, in squeeze
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 1545, in squeeze
    return squeeze(axis=axis)
ValueError: cannot select an axis to squeeze out which has size not equal to one
```

```
### Loading: ComfyUI-Manager (V1.5)
### ComfyUI Revision: 1737 [39e75862] | Released on '2023-11-26'
### Loading: ComfyUI-Impact-Pack (V4.34.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
```

Workflow attached.
![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/29675001/d5d211f6-da18-4bfa-99bb-434ed22a1835)
