### ISSUE TITLE
Loading aborted due to error reloading workflow data

### ISSUE THREAD

**Issue by mysteriousHerb** [ltdrdata/ComfyUI-Impact-Pack#207]
Loading aborted due to error reloading workflow data

TypeError: Cannot read properties of undefined (reading 'type')
TypeError: Cannot read properties of undefined (reading 'type')
    at nodeType.onConnectionsChange (http://127.0.0.1:8188/extensions/ComfyUI-Impact-Pack/impact-pack.js:323:107)
    at LGraphNode.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2521:12)
    at LGraph.configure (http://127.0.0.1:8188/lib/litegraph.core.js:2240:26)
    at LGraph.configure (http://127.0.0.1:8188/scripts/app.js:1191:22)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/reroutePrimitive.js:14:29)
    at LGraph.configure (http://127.0.0.1:8188/extensions/ComfyUI-Custom-Scripts/js/snapToGrid.js:53:21)
    at ComfyApp.loadGraphData (http://127.0.0.1:8188/scripts/app.js:1441:15)
    at ComfyApp.setup (http://127.0.0.1:8188/scripts/app.js:1288:10)
    at async http://127.0.0.1:8188/:14:4
This may be due to the following script:
/extensions/ComfyUI-Impact-Pack/impact-pack.js

O_O it destroyed my nice arrangement as well (panic mode)

**Comment by ltdrdata** [comment]
That should be fixed on 3bcfabe5374ecc3517ca388b15b8835409c473c0
