### ISSUE TITLE
how to skip first detecter when threshold too high?

### ISSUE THREAD

**Issue by alenknight** [ltdrdata/ComfyUI-Impact-Pack#214]
not really a bug... i'm assuming this is functioning as designed... but i'm not sure how to handle this.
in my workflow, when i set a SEGM detector threshold too high, it throws an error and stops the entire workflow.  Is there a way around this?  i saw if i use bbox w/ SAM.... those seem to nicely go to the fallback opt image.  

but aside from just setting the threshold really low... is there a way to get the process to by pass this issue when failing?  the fallback_opt node isn't picking up...

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/a2c4c923-17a4-4247-881a-03f176a26790)

**Comment by ltdrdata** [comment]
Your `Impact Pack` is outdated. Update it first. If ComfyUI is also an older version, please update ComfyUI as well. The latest `Impact Pack` requires the latest ComfyUI.

**Comment by alenknight** [comment]
> Your `Impact Pack` is outdated. Update it first. If ComfyUI is also an older version, please update ComfyUI as well. The latest `Impact Pack` requires the latest ComfyUI.

thanks for reviewing.  updated.  still doing it. same error.
 
![Screenshot 2023-10-13 at 12 32 54 AM](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/bd2a2260-9b7a-4f2c-b766-5a78b65b9392)

**Comment by ltdrdata** [comment]
> > Your `Impact Pack` is outdated. Update it first. If ComfyUI is also an older version, please update ComfyUI as well. The latest `Impact Pack` requires the latest ComfyUI.
> 
> thanks for reviewing. updated. still doing it. same error.
> 
> ![Screenshot 2023-10-13 at 12 32 54 AM](https://user-images.githubusercontent.com/22153900/274796114-bd2a2260-9b7a-4f2c-b766-5a78b65b9392.jpg)

When looking at the location where the error message appears, your Impact Pack version is still outdated. Check the following two versions, especially the subpack version:

```
### Loading: ComfyUI-Impact-Pack (V4.18.7)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.4)
```

**Comment by alenknight** [comment]
hmmmm.... how do I check the versions ... in the format you are showing?  sorry I thought just the branch names would work... I updated again with git pull... and it's still throwing same error.
here's the 'git show -v'

![Screenshot 2023-10-15 at 6 28 05 AM](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/dc3d2559-402f-4786-9447-2d9fab92c3b7)

**Comment by ltdrdata** [comment]
> hmmmm.... how do I check the versions ... in the format you are showing? sorry I thought just the branch names would work... I updated again with git pull... and it's still throwing same error. here's the 'git show -v'
> 
> ![Screenshot 2023-10-15 at 6 28 05 AM](https://user-images.githubusercontent.com/22153900/275319859-dc3d2559-402f-4786-9447-2d9fab92c3b7.jpg)

Please show the issue log for the updated version again. Since you just updated it, please provide a capture after the update.
It's crucial to precisely identify the location of the error in the updated version.

**Comment by alenknight** [comment]
sure.  I just updated again as I saw there was new version you posted as well.... same error still.
here's the log of the command terminal from startup to render and failure :
```
C:\AI\ComfyUI>.\python_embeded\python.exe -s ComfyUI\main.py --listen --windows-standalone-build
** ComfyUI start up time: 2023-10-15 15:39:53.138081

Prestartup times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Adding extra search path checkpoints C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path configs C:\AI\stable-diffusion-webui\models/Stable-diffusion
Adding extra search path vae C:\AI\stable-diffusion-webui\models/VAE
Adding extra search path loras C:\AI\stable-diffusion-webui\models/Lora
Adding extra search path loras C:\AI\stable-diffusion-webui\models/LyCORIS
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/ESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/RealESRGAN
Adding extra search path upscale_models C:\AI\stable-diffusion-webui\models/SwinIR
Adding extra search path embeddings C:\AI\stable-diffusion-webui\embeddings
Adding extra search path hypernetworks C:\AI\stable-diffusion-webui\models/hypernetworks
Adding extra search path controlnet C:\AI\stable-diffusion-webui\models/ControlNet
Web extensions folder found at C:\AI\ComfyUI\ComfyUI\web\extensions\ComfyLiterals
Using xformers cross attention
### Loading: ComfyUI-Impact-Pack (V4.23.2)
## ComfyUI-Impact-Pack: Updating dependencies
### ComfyUI-Impact-Pack: Check dependencies
Requirement already satisfied: ultralytics!=8.0.177 in c:\ai\comfyui\python_embeded\lib\site-packages (from -r requirements.txt (line 1)) (8.0.186)
Requirement already satisfied: matplotlib>=3.3.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.8.0)
Requirement already satisfied: numpy>=1.22.2 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.23.5)
Requirement already satisfied: opencv-python>=4.6.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.8.0.76)
Requirement already satisfied: pillow>=7.1.2 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (9.5.0)
Requirement already satisfied: pyyaml>=5.3.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (6.0.1)
Requirement already satisfied: requests>=2.23.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.31.0)
Requirement already satisfied: scipy>=1.4.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.11.2)
Requirement already satisfied: torch>=1.8.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.0.1+cu118)
Requirement already satisfied: torchvision>=0.9.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.15.2+cu118)
Requirement already satisfied: tqdm>=4.64.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.66.1)
Requirement already satisfied: pandas>=1.1.4 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.1)
Requirement already satisfied: seaborn>=0.11.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.12.2)
Requirement already satisfied: psutil in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (5.9.5)
Requirement already satisfied: py-cpuinfo in c:\ai\comfyui\python_embeded\lib\site-packages (from ultralytics!=8.0.177->-r requirements.txt (line 1)) (9.0.0)
Requirement already satisfied: contourpy>=1.0.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.1.1)
Requirement already satisfied: cycler>=0.10 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.42.1)
Requirement already satisfied: kiwisolver>=1.0.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.4.5)
Requirement already satisfied: packaging>=20.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (23.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.1)
Requirement already satisfied: python-dateutil>=2.7 in c:\ai\comfyui\python_embeded\lib\site-packages (from matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3.post1)
Requirement already satisfied: tzdata>=2022.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from pandas>=1.1.4->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.2.0)
Requirement already satisfied: idna<4,>=2.5 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.4)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.26.16)
Requirement already satisfied: certifi>=2017.4.17 in c:\ai\comfyui\python_embeded\lib\site-packages (from requests>=2.23.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2023.7.22)
Requirement already satisfied: filelock in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.12.2)
Requirement already satisfied: typing-extensions in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (4.7.1)
Requirement already satisfied: sympy in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.12)
Requirement already satisfied: networkx in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1)
Requirement already satisfied: jinja2 in c:\ai\comfyui\python_embeded\lib\site-packages (from torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (3.1.2)
Requirement already satisfied: colorama in c:\ai\comfyui\python_embeded\lib\site-packages (from tqdm>=4.64.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (0.4.6)
Requirement already satisfied: six>=1.5 in c:\ai\comfyui\python_embeded\lib\site-packages (from python-dateutil>=2.7->matplotlib>=3.3.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.16.0)
Requirement already satisfied: MarkupSafe>=2.0 in c:\ai\comfyui\python_embeded\lib\site-packages (from jinja2->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (2.1.3)
Requirement already satisfied: mpmath>=0.19 in c:\ai\comfyui\python_embeded\lib\site-packages (from sympy->torch>=1.8.0->ultralytics!=8.0.177->-r requirements.txt (line 1)) (1.3.0)
DEPRECATION: torchsde 0.2.5 has a non-standard dependency specifier numpy>=1.19.*; python_version >= "3.7". pip 23.3 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of torchsde or contact the author to suggest that they release a version with a conforming dependency specifiers. Discussion can be found at https://github.com/pypa/pip/issues/12063
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: Updating subpack
[ComfyUI-Impact-Pack]: Dependency installation has failed. Please install manually.
[WinError 5] Access is denied: 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack\\.git\\objects\\25\\6f88a9cd0c835bfba7593869af71f0dce886d8'
e: module 'sys' has no attribute '__comfyui_manager_register_message_collapse'
### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.3)
### Loading: ComfyUI-Inspire-Pack (V0.28)
### Loading: ComfyUI-Manager (V0.34)
### ComfyUI Revision: 1561 [536799d1] | Released on '2023-10-11'
Failed to auto update `Quality of Life Suit`
QualityOfLifeSuit_Omar92_DIR: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Comfyroll Custom Nodes: Loaded
Registered sys.path: ['C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\__init__.py', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_pycocotools', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_oneformer', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_mmpkg', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_midas_repo', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\custom_detectron2', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src\\controlnet_aux', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\comfyui_controlnet_aux\\src', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI_Comfyroll_CustomNodes\\comfy', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Custom-Scripts', 'C:\\AI\\ComfyUI\\python_embeded\\lib\\site-packages\\git\\ext\\gitdb', WindowsPath('C:/AI/ComfyUI/ComfyUI'), 'C:\\AI\\ComfyUI\\ComfyUI\\comfy', 'C:\\AI\\ComfyUI\\ComfyUI', 'C:\\AI\\ComfyUI\\python_embeded\\python310.zip', 'C:\\AI\\ComfyUI\\python_embeded', 'C:\\AI\\ComfyUI\\python_embeded\\lib\\site-packages', 'C:\\AI\\ComfyUI\\python_embeded\\lib\\site-packages\\win32', 'C:\\AI\\ComfyUI\\python_embeded\\lib\\site-packages\\win32\\lib', 'C:\\AI\\ComfyUI\\python_embeded\\lib\\site-packages\\Pythonwin', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\modules', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\..\\..', 'C:\\AI\\ComfyUI\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack', '../..']
FizzleDorf Custom Nodes: Loaded
Total VRAM 24576 MB, total RAM 32703 MB
xformers version: 0.0.21
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3090 : cudaMallocAsync
VAE dtype: torch.bfloat16
C:\AI\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions\extensions
C:\AI\ComfyUI\ComfyUI\web\extensions\failfast-comfyui-extensions

[rgthree] Loaded 15 exciting nodes.
[rgthree] Optimizing ComfyUI recursive execution. If queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json

Searge-SDXL v4.2 in C:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 196 nodes successfully.

        "Failure is the opportunity to begin again more intelligently." - Henry Ford


Import times for custom nodes:
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\mosaic_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\invert_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Pseudo_HDR_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\invert_image_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\image_to_contrast_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\brightness_contrast_ally_modified.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\image_to_mask_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\brightness_contrast_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\imageflip_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\monocromatic_clip_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\histogram_equalization.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\vae_decode_preview.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\crop_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\gaussian_blur_node.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sharpness_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\saturation_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\gaussian_blur_ally.py
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-SDXL-EmptyLatentImage
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_JPS-Nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyLiterals
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\stability-ComfyUI-nodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_NestedNodeBuilder
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\facerestore_cf
   0.1 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.2 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.4 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI_FizzNodes
   0.5 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\SeargeSDXL
   0.6 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\comfyui-reactor-node
   1.8 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   4.3 seconds: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://0.0.0.0:8188
FETCH DATA from: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
QualityOfLifeSuit_Omar92::NSP ready
FETCH DATA from: C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt
model_type EPS
adm 2816
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
making attention of type 'vanilla-xformers' with 512 in_channels
building MemoryEfficientAttnBlock with 512 in_channels...
missing {'cond_stage_model.clip_g.transformer.text_model.embeddings.position_ids', 'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
CLIP: Rebecca_Fergus0n:0.5, Rebecca_Ferguson:0.5, light freckles, dark shot, photo of cute 24 y.o blonde woman, perfect eyes, skin moles, short hair, looks at viewer, cinematic shot, hard shadows
Requested to load SDXLClipModel
Loading 1 new model
Requested to load SDXL
Loading 1 new model
100%|██████████████████████████████████████████████████████████████████████████████████| 20/20 [00:07<00:00,  2.64it/s]
100%|██████████████████████████████████████████████████████████████████████████████████| 24/24 [00:13<00:00,  1.81it/s]

0: 640x640 (no detections), 10.0ms
Speed: 3.0ms preprocess, 10.0ms inference, 0.0ms postprocess per image at shape (1, 3, 640, 640)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\AI\ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 106, in doit
    segs = segm_detector.detect(image, threshold, dilation, crop_factor, drop_size)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 148, in detect
    detected_results = inference_segm(self.bbox_model, core.tensor2pil(image), threshold)
  File "C:\AI\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 68, in inference_segm
    segms = pred[0].masks.data.cpu().numpy()
AttributeError: 'NoneType' object has no attribute 'data'

Prompt executed in 37.97 seconds
```


and the issue screenshot again
![Screenshot 2023-10-15 at 3 47 37 PM](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/22153900/22797849-b7e0-4efb-a189-1d73d02a1d25)

**Comment by ltdrdata** [comment]
> `### Loading: ComfyUI-Impact-Pack (Subpack: V0.2.3)`

Your subpack version is outdated version.
I don't understand why it isn't updated.
Anyway goto `custom_nodes/ComfyUI-Impact-Pack/impact_subpack`.
And `git pull`.

**Comment by alenknight** [comment]
Very odd indeed!  doing repeated `git pull` even in the subfolders.... still not bringing in the right version.  now I see how to check from the terminal window too.

I went and deleted the whole custom impact-pack node, and reinstalled it... brought in the v0.2.4 as you mentioned.  
NOW it's working.  so odd.  

thank you again!

**Comment by ltdrdata** [comment]
> Very odd indeed! doing repeated `git pull` even in the subfolders.... still not bringing in the right version. now I see how to check from the terminal window too.
> 
> I went and deleted the whole custom impact-pack node, and reinstalled it... brought in the v0.2.4 as you mentioned. NOW it's working. so odd.
> 
> thank you again!

It seems that some file were modified mistakenly
