### ISSUE TITLE
Problem Installing

### ISSUE THREAD

**Issue by henry808** [ltdrdata/ComfyUI-Impact-Pack#216]
In ComfyUI on windows 11, I installed through Manager first and that did not work and I installed with Git and it did not work either.
I see this error in the ComfyUI startup script (this error shows up after installing through manager or through git clone, so the same exact error happens.):
```
### Loading: ComfyUI-Impact-Pack (V4.18.6)
Traceback (most recent call last):
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1647, in load_custom_node
module_spec.loader.exec_module(module)
File "<frozen importlib._bootstrap_external>", line 883, in exec_module
File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 66, in <module>
import impact.impact_server # to load server api
File "C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 305, in <module>
server.PromptServer.instance.add_on_prompt_handler(onprompt)
AttributeError: 'PromptServer' object has no attribute 'add_on_prompt_handler'
Cannot import C:\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: 'PromptServer' object has no attribute 'add_on_prompt_handler'
```

I do not see the impact nodes in the custom node menu, so the install failed.

**Comment by ltdrdata** [comment]
Your ComfyUI is outdated. Please update your ComfyUI.

**Comment by henry808** [comment]
Thanks. Yes. That was it. Manager was not updating it properly, but I was able to with the included bat and it works now.
