### ISSUE TITLE
how about add lora block weight and lora support in text box in image refiner

### ISSUE THREAD

**Issue by xueqing0622** [ltdrdata/ComfyUI-Impact-Pack#217]
how about add lora block weight and lora support in text box in image refiner
because:
1 hard to search lora (No search function, it's inconvenient to have to drop down the bar）
2 only support two loras
3 need LBW to control more
4 maybe make textbox positive bigger
5 make like wildcardEncode add lora button?

**Comment by ltdrdata** [comment]
This is implemented. mask detailer components uses ImpactWildcardEncode's  prompt interpreting feature.
You can use LBW syntax.

**Comment by xueqing0622** [comment]
I don't know why,  image refiner easy to get error after I regenerate few times :


Error handling request
Traceback (most recent call last):
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 58, in cors_middleware
    response = await handler(request)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 60, in imagerefiner_generate
    base_pil = get_image_from_fileitem(x['image']).convert('RGBA')
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 31, in get_image_from_fileitem
    image_path = get_path_from_fileitem(image)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 17, in get_path_from_fileitem
    image_path = image['subfolder'] + "/"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
Error handling request
Traceback (most recent call last):
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 58, in cors_middleware
    response = await handler(request)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 60, in imagerefiner_generate
    base_pil = get_image_from_fileitem(x['image']).convert('RGBA')
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 31, in get_image_from_fileitem
    image_path = get_path_from_fileitem(image)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 17, in get_path_from_fileitem
    image_path = image['subfolder'] + "/"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'

**Comment by xueqing0622** [comment]
seems  no support embedding in negative prompt too:

Error handling request
Traceback (most recent call last):
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_protocol.py", line 433, in _handle_request
    resp = await request_handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_app.py", line 504, in _handle
    resp = await handler(request)
  File "F:\ComfyUI\python_embeded\lib\site-packages\aiohttp\web_middlewares.py", line 117, in impl
    return await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 46, in cache_control
    response: web.Response = await handler(request)
  File "F:\ComfyUI\ComfyUI\server.py", line 58, in cors_middleware
    response = await handler(request)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\custom_server.py", line 69, in imagerefiner_generate
    result = ir.generate(base_pil.convert('RGB'), mask_pil, prompt_data)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 174, in generate
    input_data_all = prepare_input(class_def, merged_pil, mask_pil, prompt_data)
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 95, in prepare_input
    basic_pipe = make_basic_pipe(model, clip, vae, v['positive'], v['negative'])
  File "F:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Workflow-Component\image_refiner\imagerefiner.py", line 50, in make_basic_pipe
    negative = comfy_nodes.CLIPTextEncode().encode(clip, negative)[0]
  File "F:\ComfyUI\ComfyUI\nodes.py", line 56, in encode
    cond, pooled = clip.encode_from_tokens(tokens, return_pooled=True)
  File "F:\ComfyUI\ComfyUI\comfy\sd.py", line 120, in encode_from_tokens
    cond, pooled = self.cond_stage_model.encode_token_weights(tokens)
  File "F:\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 489, in encode_token_weights
    out, pooled = getattr(self, self.clip).encode_token_weights(token_weight_pairs)
  File "F:\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 18, in encode_token_weights
    out, pooled = self.encode(to_encode)
  File "F:\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 179, in encode
    return self(tokens)
  File "F:\ComfyUI\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "F:\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 142, in forward
    tokens = self.set_up_textual_embeddings(tokens, backup_embeds)
  File "F:\ComfyUI\ComfyUI\comfy\sd1_clip.py", line 126, in set_up_textual_embeddings
    new_embedding.weight[:token_dict_size] = current_embeds.weight[:-1]
RuntimeError: a view of a leaf Variable that requires grad is being used in an in-place operation.
