### ISSUE TITLE
Loading SubPack failed

### ISSUE THREAD

**Issue by iamshenkui** [ltdrdata/ComfyUI-Impact-Pack#250]
when I was loading the ImpackPack, I got such error:

### ComfyUI-Impact-Pack: Updating subpack
Traceback (most recent call last):
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1348, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1283, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1329, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1278, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1038, in _send_output
    self.send(msg)
  File "/root/miniconda3/lib/python3.10/http/client.py", line 976, in send
    self.connect()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 1448, in connect
    super().connect()
  File "/root/miniconda3/lib/python3.10/http/client.py", line 942, in connect
    self.sock = self._create_connection(
  File "/root/miniconda3/lib/python3.10/socket.py", line 845, in create_connection
    raise err
  File "/root/miniconda3/lib/python3.10/socket.py", line 833, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/install.py", line 27, in <module>
    download_url("https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8s.pt",
  File "/root/miniconda3/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 134, in download_url
    url = _get_redirect_url(url, max_hops=max_redirect_hops)
  File "/root/miniconda3/lib/python3.10/site-packages/torchvision/datasets/utils.py", line 82, in _get_redirect_url
    with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 216, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 519, in open
    response = self._open(req, data)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 536, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 496, in _call_chain
    result = func(*args)
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1391, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "/root/miniconda3/lib/python3.10/urllib/request.py", line 1351, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

what should I do?

**Comment by ltdrdata** [comment]
It seems that you have network related environment issue.

Download file from these urls:

https://huggingface.co/Bingsu/adetailer/resolve/main/hand_yolov8s.pt

https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt

and move to 

ComfyUI/models/ultralytics/bbox

In case of an error from a different file URL, you should also copy the file in the same way.

Download this url to ComfyUI/models/ultralytics/segm

https://huggingface.co/Bingsu/adetailer/resolve/main/person_yolov8m-seg.pt
