### ISSUE TITLE
Facedetailer Error

### ISSUE THREAD

**Issue by ultimatech-cn** [ltdrdata/ComfyUI-Impact-Pack#279]
I have workflow for batch image generating and use facedetailer node
When excuting following error will be reported 

```

> The above exception was the direct cause of the following exception:
> Traceback (most recent call last):
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\execution.py", line 153, in recursive_execute
>     output_data, output_ui = get_output_data(obj, input_data_all)
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\execution.py", line 83, in get_output_data
>     return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\execution.py", line 76, in map_node_over_list
>     results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 423, in doit
>     enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 375, in enhance_face
>     segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 100, in detect
>     detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
>   File "E:\DEV\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 19, in tensor2pil
>     return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8))
>   File "E:\DEV\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\Image.py", line 3092, in fromarray
>     raise TypeError(msg) from e
> TypeError: Cannot handle this data type: (1, 1, 1248, 3), |u1

```

**Comment by ltdrdata** [comment]
Read this.
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md

It seems that I need to improve to display an appropriate error message for this case.
