### ISSUE TITLE
Cannot import ComfyUI-Impact-Pack module for custom nodes: Failed to import transformers.pipelines because of the following error 

### ISSUE THREAD

**Issue by onglaoxiteen** [ltdrdata/ComfyUI-Impact-Pack#289]
## Loading: ComfyUI-Impact-Pack (V4.30.8)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1353, in _get_module
    return importlib.import_module("." + module_name, self.__name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/local/lib/python3.10/dist-packages/transformers/pipelines/__init__.py", line 28, in <module>
    from ..image_processing_utils import BaseImageProcessor
  File "/usr/local/lib/python3.10/dist-packages/transformers/image_processing_utils.py", line 28, in <module>
    from .image_transforms import center_crop, normalize, rescale
  File "/usr/local/lib/python3.10/dist-packages/transformers/image_transforms.py", line 47, in <module>
    import tensorflow as tf
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/__init__.py", line 38, in <module>
    from tensorflow.python.tools import module_util as _module_util
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/__init__.py", line 42, in <module>
    from tensorflow.python.saved_model import saved_model
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/saved_model/saved_model.py", line 20, in <module>
    from tensorflow.python.saved_model import builder
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/saved_model/builder.py", line 23, in <module>
    from tensorflow.python.saved_model.builder_impl import _SavedModelBuilder
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/saved_model/builder_impl.py", line 20, in <module>
    from google.protobuf.any_pb2 import Any
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/any_pb2.py", line 19, in <module>
    _builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'google.protobuf.any_pb2', globals())
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/builder.py", line 108, in BuildTopDescriptorsAndMessages
    module[name] = BuildMessage(msg_des)
  File "/usr/local/lib/python3.10/dist-packages/google/protobuf/internal/builder.py", line 85, in BuildMessage
    message_class = _reflection.GeneratedProtocolMessageType(
TypeError: A Message class can only inherit from Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1735, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 105, in <module>
    from impact.hf_nodes import *
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/hf_nodes.py", line 1, in <module>
    from transformers import pipeline
  File "<frozen importlib._bootstrap>", line 1075, in _handle_fromlist
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1343, in __getattr__
    module = self._get_module(self._class_to_module[name])
  File "/usr/local/lib/python3.10/dist-packages/transformers/utils/import_utils.py", line 1355, in _get_module
    raise RuntimeError(
RuntimeError: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
A Message class can only inherit from Message

## Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: Failed to import transformers.pipelines because of the following error (look up to see its traceback):
A Message class can only inherit from Message

# Systems Info

- `transformers` version: 4.35.2
- Platform: Linux-5.15.120+-x86_64-with-glibc2.35
- Python version: 3.10.12
- Huggingface_hub version: 0.19.3
- Safetensors version: 0.4.0
- Accelerate version: 0.24.1
- Accelerate config: 	not found
- PyTorch version (GPU?): 2.0.0+cu118 (True)
- Tensorflow version (GPU?): 2.14.0 (True)
- Flax version (CPU?/GPU?/TPU?): 0.7.5 (gpu)
- Jax version: 0.4.20
- JaxLib version: 0.4.20
- Using GPU in script?: <fill in>
- Using distributed or parallel set-up in script?: <fill in>

**Comment by ltdrdata** [comment]
This issue seems to be related to protobuf. Have you installed something like a reactor node?
Installing a reactor node typically brings along packages that often lead to such issues.

**Comment by onglaoxiteen** [comment]
> This issue seems to be related to protobuf. Have you installed something like a reactor node? Installing a reactor node typically brings along packages that often lead to such issues.

Thank God You're Here, Impact-Pack is back, i installed ReActor and disable it so it out of my mind, Uninstall ReActor and something like roop,facerestore (idk) bring it back

**Comment by alenknight** [comment]
lol i just had this issue too.  removed reactor and started working again.
