### ISSUE TITLE
Detailer_hook error

### ISSUE THREAD

**Issue by dreamscapeai** [ltdrdata/ComfyUI-Impact-Pack#294]
Hello, i've connected all the nodes correctly following video tutorial but I have this error.
This is for a simple face detailer of a generation txt2image.

Thank for your help !

ERROR:root:Traceback (most recent call last):
  File "C:\Users\Admin\Documents\1_ComfyUI\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\Admin\Documents\1_ComfyUI\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\Admin\Documents\1_ComfyUI\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\Admin\Documents\1_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 994, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File "C:\Users\Admin\Documents\1_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 375, in enhance_face
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
TypeError: UltraBBoxDetector.detect() got an unexpected keyword argument 'detailer_hook'

![image error](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/142077967/06921994-dce0-4438-a1c2-71f9a8d4e7c8)

**Comment by ltdrdata** [comment]
Your version is outdated.
Please update to latest version.
If it doesn't work. remove `ComfyUI-Impact-Pack/impact_subpack` and restart ComfyUI.
