### ISSUE TITLE
The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete

### ISSUE THREAD

**Issue by rpr13** [ltdrdata/ComfyUI-Impact-Pack#297]
Hi, I cannot install pack correctly.

Traceback:

```
### ComfyUI-Impact-Pack: Check basic models
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
---------------------------------
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 408, in <module>

    import impact.subpack_nodes
### Loading: ComfyUI-Manager (V1.1)
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
  File "D:\Applications\StabilityMatrix\Data\Packages\ComfyUI\venv\lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
AttributeError: 'Logger' object has no attribute 'encoding'
### ComfyUI Revision: 1703 [31c5ea7b] | Released on '2023-11-20'
```

**Comment by ltdrdata** [comment]
Update `ComfyUI-Manager` to V1.1.2.
This is fixed.

**Comment by rpr13** [comment]
thanks
