### ISSUE TITLE
fix: symbol not found in flat namespace '__ZN2at3mps9MPSStream6commitEb'

### ISSUE THREAD

**Issue by jjangga0214** [ltdrdata/ComfyUI-Impact-Pack#30]
Hi!

When I install it, I saw the success message.

```bash
### ComfyUI-Impact-Pack: Check basic models
Installation was successful.
After restarting ComfyUI, please refresh the browser.
FECTH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
```

But when rebooting ComfyUI, this error happens.

```bash
### ComfyUI-Impact-Pack: Check basic models
Traceback (most recent call last):
  File "/Users/ocean/main/ComfyUI/nodes.py", line 1422, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/Users/ocean/main/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 47, in <module>
    import impact.impact_server  # to load server api
  File "/Users/ocean/main/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_server.py", line 8, in <module>
    import impact.core as core
  File "/Users/ocean/main/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 3, in <module>
    from mmdet.apis import (inference_detector, init_detector)
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmdet/apis/__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmdet/apis/det_inferencer.py", line 21, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmdet/evaluation/__init__.py", line 3, in <module>
    from .metrics import *  # noqa: F401,F403
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmdet/evaluation/metrics/__init__.py", line 3, in <module>
    from .coco_metric import CocoMetric
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmdet/evaluation/metrics/coco_metric.py", line 18, in <module>
    from mmdet.structures.mask import encode_mask_results
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmdet/structures/mask/__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmdet/structures/mask/structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmcv/ops/active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: dlopen(/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmcv/_ext.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__ZN2at3mps9MPSStream6commitEb'

Cannot import /Users/ocean/main/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: dlopen(/Users/ocean/miniconda3/envs/comfyui/lib/python3.10/site-packages/mmcv/_ext.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '__ZN2at3mps9MPSStream6commitEb'

Import times for custom nodes:
   0.0 seconds: /Users/ocean/main/ComfyUI/custom_nodes/sampler_rescalecfg.py
   0.1 seconds: /Users/ocean/main/ComfyUI/custom_nodes/ComfyUI-Manager
   7.3 seconds (IMPORT FAILED): /Users/ocean/main/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
```

I wonder the cause 🧐

Thanks.

**Info**:

- OS: macOS Ventura 13.4.1 (22F82)
- HW: Apple M1 Max
- python: 3.10.10
- pip: 23.0.1
- env: a miniconda environment dedicated to only ComfyUI

**Comment by ltdrdata** [comment]
try reinstall dependencies..
pycocotools and mmdet, mmcv, mmengine

pip/mim installer doesn't check the integrity of the installed package.
And I found that sometimes the installed dependencies were broken on binary level.

**Comment by jjangga0214** [comment]
@ltdrdata Thanks for the reply :)

However, the issue still happens.

1. I uninstalled(removed the dir) ComfyUI-Impact-Pack
2. I reinstalled dependencies manually.
```bash
pip install openmim segment-anything pycocotools onnxruntime 
mim install mmcv==2.0.0 mmdet==3.0.0 mmengine==0.7.2
```
3. I re-downloaded (cloned) ComfyUI-Impact-Pack
4. The same error appears.

**Comment by jjangga0214** [comment]
I found `mmdet` and `mmcv` are too sensitive and frequently broken while installation. 
A1111 extension [adetailer](https://github.com/Bing-su/adetailer) intentionally avoids using them just for this reason, and it has no installation issue.
It also has good detection accuracy. 
Why don't you drop `mmdet` and `mmcv`, like adetailer?

**Comment by ltdrdata** [comment]
> I found `mmdet` and `mmcv` are too sensitive and frequently broken while installation. A1111 extension [adetailer](https://github.com/Bing-su/adetailer) intentionally avoids using them just for this reason, and it has no installation issue. It also has good detection accuracy. Why don't you drop `mmdet` and `mmcv`, like adetailer?

I am considering it too.

**Comment by tildebyte** [comment]
Slight tangent, but I'd look at 'openmim' with great suspicion as well...

(during install)
```python
  File "D:\ComfyUI\.venv\lib\site-packages\mim\commands\install.py", line 73, in cli
    exit(exit_code)
    ^^^^
```

Like, seriously, `exit` is not a Python keyword, and `sys` isn't being imported anywhere. This is Mickey Mouse sh!t.

Importing 'sys' and using `sys.exit` *of course* fixes it...

**Comment by ltdrdata** [comment]
> I found `mmdet` and `mmcv` are too sensitive and frequently broken while installation. A1111 extension [adetailer](https://github.com/Bing-su/adetailer) intentionally avoids using them just for this reason, and it has no installation issue. It also has good detection accuracy. Why don't you drop `mmdet` and `mmcv`, like adetailer?

Finally, I added this.
Now mmdet dependent nodes are optional.

https://www.youtube.com/watch?v=t-JjsEvPX7o
