### ISSUE TITLE
ComfyUI-Manager (V1.1.2) still error

### ISSUE THREAD

**Issue by blueroutecn** [ltdrdata/ComfyUI-Impact-Pack#300]
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "/home/llm/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 408, in <module>
    import impact.subpack_nodes
  File "/home/llm/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "/home/llm/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 10, in <module>
    from ultralytics import YOLO
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/ultralytics/models/__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/ultralytics/models/rtdetr/__init__.py", line 3, in <module>
    from .model import RTDETR
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/ultralytics/models/rtdetr/model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "/home/llm/ComfyUI/myenv/lib/python3.10/sitComfyUI-Manager (V1.1.2)e-packages/ultralytics/engine/model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/ultralytics/cfg/__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, SETTINGS,
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 270, in <module>
    set_logging(LOGGING_NAME, verbose=VERBOSE)  # run before defining LOGGER
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 232, in set_logging
    logging.config.dictConfig({
  File "/usr/lib/python3.10/logging/config.py", line 811, in dictConfig
    dictConfigClass(config).configure()
  File "/usr/lib/python3.10/logging/config.py", line 538, in configure
    _clearExistingHandlers()
  File "/usr/lib/python3.10/logging/config.py", line 275, in _clearExistingHandlers
    logging.shutdown(logging._handlerList[:])
  File "/usr/lib/python3.10/logging/__init__.py", line 2183, in shutdown
    h.close()
  File "/home/llm/ComfyUI/myenv/lib/python3.10/site-packages/absl/logging/__init__.py", line 944, in close
    self.stream.close()
AttributeError: 'Logger' object has no attribute 'close'
---------------------------------
### ComfyUI Revision: 1727 [c0883d85] | Released on '2023-11-21'
Davemane42 Custom Nodes: Loaded

**Comment by ltdrdata** [comment]
What is your ultralytics version?
`pip list`

**Comment by blueroutecn** [comment]
pip list|grep ultralytics
ultralytics                  8.0.189

**Comment by ltdrdata** [comment]
`pip install -U ultralytics` 
And update ComfyUI-Manager to V1.1.3
What error messages are displayed.

**Comment by blueroutecn** [comment]
thx

**Comment by ltdrdata** [comment]
> thx

Is it resolved?

**Comment by blueroutecn** [comment]
I can run,Thx.
