### ISSUE TITLE
UltralyticsDetectorProvider Node Missing - AttributeError: 'Logger' object has no attribute 'encoding'

### ISSUE THREAD

**Issue by chudabega** [ltdrdata/ComfyUI-Impact-Pack#305]
I'm unable to get the UltralyticsDetectorProvider node to install properly in windows.

I attempted to install with the manager and manually, it didn't show any errors until starting ComfyUI.

The following appears to run successfully:
python -s custom_nodes\ComfyUI-Impact-Pack\install.py

Using -m causes another crash:
python -s -m custom_nodes\ComfyUI-Impact-Pack\install.py
Error while finding module specification for 'custom_nodes\\ComfyUI-Impact-Pack\\install.py' (ModuleNotFoundError: No module named 'custom_nodes\\ComfyUI-Impact-Pack\\install'). Try using 'custom_nodes\ComfyUI-Impact-Pack\install' instead of 'custom_nodes\ComfyUI-Impact-Pack\install.py' as the module name.

The error I am receiving during ComfyUI starting seems to be introduced on November 14th with
17b81e1da45bc1321640a3bbc131f203af89c95c 

But even in revisions before then the UltralyticsDetectorProvider node is still red/missing.

Here is the crash I am receiving when starting ComfyUI:
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 408, in <module>
    import impact.subpack_nodes
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "C:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ComfyUI\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'encoding'

**Comment by ltdrdata** [comment]
Update `ComfyUI-Manager` to latest version.

**Comment by chudabega** [comment]
Thanks after pulling the latest version of ComfyUI-Manager, and uninstalling then reinstalling the ComfyUI Impact Pack, it appears to be working.
