### ISSUE TITLE
The new update is having one issue in Subpack as checked now !

### ISSUE THREAD

**Issue by jags111** [ltdrdata/ComfyUI-Impact-Pack#306]
Here is the update on the error

### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['D:\\AI\\ComfyUI_windows_portable_nvidia_cu118_or_cpu\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
WARNING: Ignoring invalid distribution -ip (c:\users\sunde\appdata\roaming\python\python310\site-packages)
WARNING: No metadata found in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages
WARNING: No metadata found in d:\ai\comfyui_windows_portable_nvidia_cu118_or_cpu\comfyui_windows_portable\python_embeded\lib\site-packages
WARNING: Ignoring invalid distribution -ip (c:\users\sunde\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\sunde\appdata\roaming\python\python310\site-packages)
WARNING: Ignoring invalid distribution -ip (c:\users\sunde\appdata\roaming\python\python310\site-packages)

[notice] A new release of pip is available: 23.2.1 -> 23.3.1
[notice] To update, run: D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\python.exe -m pip install --upgrade pip
req_path: D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 408, in <module>
    import impact.subpack_nodes
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 10, in <module>
    from ultralytics import YOLO
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\models\rtdetr\model.py", line 5, in <module>
    from ultralytics.engine.model import Model
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import get_cfg
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\cfg\__init__.py", line 11, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, SETTINGS, SETTINGS_YAML,
  File "D:\AI\ComfyUI_windows_portable_nvidia_cu118_or_cpu\ComfyUI_windows_portable\python_embeded\lib\site-packages\ultralytics\utils\__init__.py", line 103, in <module>
    cv2.setNumThreads(0)  # prevent OpenCV from multithreading (incompatible with PyTorch DataLoader)
AttributeError: module 'cv2' has no attribute 'setNumThreads'
---------------------------------

### Loading: ComfyUI-Inspire-Pack (V0.47)
jjk_util loding
### ComfyUI Revision: 1712 [72741105] | Released on '2023-11-21'
--------------

Is my error local or is it something to do with path mismatch. not sure..

Thanks

**Comment by jags111** [comment]
As per your feedback the issue is caused by openCV version mismatch .. reinstalling the python_embeded\python.exe -m pip install opencv-python==4.7.0.72 from ComfyUI root almost removed many issues. So the main question is how the new version of openCV is almost throwing so much errors. Thanks for the suggestions and closing same.
