### ISSUE TITLE
Mask -> SEGS: ValueError: cannot select an axis to squeeze out which has size not equal to one

### ISSUE THREAD

**Issue by ghost** [ltdrdata/ComfyUI-Impact-Pack#323]
Got the same issue, even though I'm up to date.

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/drive/MyDrive/beinass/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/beinass/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/beinass/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/beinass/custom_nodes/ComfyUI-Impact-Pack/modules/impact/segs_nodes.py", line 925, in doit
    result = core.mask_to_segs(mask, combined, crop_factor, bbox_fill, drop_size)
  File "/content/drive/MyDrive/beinass/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 919, in mask_to_segs
    mask = np.squeeze(mask, axis=1)
  File "<__array_function__ internals>", line 180, in squeeze
  File "/usr/local/lib/python3.10/dist-packages/numpy/core/fromnumeric.py", line 1545, in squeeze
    return squeeze(axis=axis)
ValueError: cannot select an axis to squeeze out which has size not equal to one
```

```
### Loading: ComfyUI-Manager (V1.5)
### ComfyUI Revision: 1737 [39e75862] | Released on '2023-11-26'
### Loading: ComfyUI-Impact-Pack (V4.34.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
```

Workflow attached.
![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/29675001/d5d211f6-da18-4bfa-99bb-434ed22a1835)

_Originally posted by @gergovari in https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/195#issuecomment-1826858931_

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/f28a88cb-01d4-4118-bcc1-6140fc508743)

Update to V4.35 and
Use `Mask To SEGS for AnimateDiff` instead of `Mask To SEGS`.
