### ISSUE TITLE
New Mask -> SEGS for AD bug

### ISSUE THREAD

**Issue by ghost** [ltdrdata/ComfyUI-Impact-Pack#332]
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "/content/drive/MyDrive/beinass/execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/content/drive/MyDrive/beinass/execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/content/drive/MyDrive/beinass/execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/content/drive/MyDrive/beinass/custom_nodes/ComfyUI-Impact-Pack/modules/impact/segs_nodes.py", line 974, in doit
    return MaskToSEGS().doit(result_mask, False, crop_factor, False, drop_size, fill_inside)
NameError: name 'fill_inside' is not defined
```

![workflow](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/29675001/7a03b474-d1ea-44b1-9b88-014f547f6a86)

**Comment by ltdrdata** [comment]
This is fixed. Thx.
