### ISSUE TITLE
 ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

### ISSUE THREAD

**Issue by fengyingbanbo** [ltdrdata/ComfyUI-Impact-Pack#355]
The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 435, in <module>
    import impact.subpack_nodes
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in <module>
    raise e
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in <module>
    from ultralytics import YOLO
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'encoding'

**Comment by ltdrdata** [comment]
Update ComfyUI-Manager to latest version.
Your ComfyUI-Manager is outdated.

**Comment by fengyingbanbo** [comment]
yes,it's ok now
