### ISSUE TITLE
OOM error when using Impact KSampler

### ISSUE THREAD

**Issue by FaRihr** [ltdrdata/ComfyUI-Impact-Pack#364]
```
** ComfyUI startup time: 2023-12-13 09:11:31.645153
** Platform: Windows
** Python version: 3.11.6 (tags/v3.11.6:8b6ee5b, Oct  2 2023, 14:57:12) [MSC v.1935 64 bit (AMD64)]
** Python executable: D:\stable-diffusion\comfy\python_embeded\python.exe
** Log path: D:\stable-diffusion\comfy\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 12282 MB, total RAM 32530 MB
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4070 Ti : cudaMallocAsync
VAE dtype: torch.bfloat16
Using pytorch cross attention
### Loading: ComfyUI-Impact-Pack (V4.45.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.3.2)
### Loading: ComfyUI-Inspire-Pack (V0.49.1)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V1.11.5)
### ComfyUI Revision: 1810 [b0aab1e4] | Released on '2023-12-11'
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[34mComfyroll Custom Nodes: [92mLoaded[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider'][0m
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
DWPose: Onnxruntime with acceleration providers detected

[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m

[32m[1m[rgthree] Loaded 20 exciting nodes.[0m

[34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `D:\stable-diffusion\comfy\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m197[0m [32mnodes successfully.[0m

	[3m[93m"The best way to predict the future is to create it."[0m[3m - Peter Drucker[0m


Import times for custom nodes:
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\sdxl-recommended-res-calc
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\LoadLoraWithTags
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\SD-Latent-Upscaler
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI_Cutoff
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\comfyui-fitsize
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Latent-Modifiers
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.1 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.3 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\comfyui-dynamicprompts
   0.3 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.4 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   1.2 seconds: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\was-node-suite-comfyui

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
got prompt

DWPose: Using yolox_l.onnx for bbox detection and dw-ll_ucoco_384.onnx for pose estimation
DWPose: Caching ONNXRuntime session yolox_l.onnx...
DWPose: Caching ONNXRuntime session dw-ll_ucoco_384.onnx...
DWPose: Bbox 15140.58ms
DWPose: Pose 2904.93ms on 1 people

model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
New prompt: Photo of a medieval warrior in heavy steel armor standing on a battlefield with a broken sword in his hand
Requested to load SDXLClipModel
Loading 1 new model
model_type EPS
adm 2816
Using pytorch attention in VAE
Working with z of shape (1, 4, 32, 32) = 4096 dimensions.
Using pytorch attention in VAE
missing {'cond_stage_model.clip_l.text_projection', 'cond_stage_model.clip_l.logit_scale'}
left over keys: dict_keys(['cond_stage_model.clip_l.transformer.text_model.embeddings.position_ids'])
Requested to load SDXLClipModel
Loading 1 new model
[] []
Requested to load SDXL
Requested to load ControlNet
Loading 2 new models
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\stable-diffusion\comfy\ComfyUI\execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\special_samplers.py", line 581, in sample
    latent = nodes.KSamplerAdvanced().sample(model, add_noise, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, start_at_step, end_at_step, return_with_leftover_noise, denoise)[0]
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\nodes.py", line 1333, in sample
    return common_ksampler(model, noise_seed, steps, cfg, sampler_name, scheduler, positive, negative, latent_image, denoise=denoise, disable_noise=disable_noise, start_step=start_at_step, last_step=end_at_step, force_full_denoise=force_full_denoise)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\nodes.py", line 1269, in common_ksampler
    samples = comfy.sample.sample(model, noise, steps, cfg, sampler_name, scheduler, positive, negative, latent_image,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 22, in informative_sample
    raise e
  File "D:\stable-diffusion\comfy\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\sample_error_enhancer.py", line 9, in informative_sample
    return original_sample(*args, **kwargs)  # This code helps interpret error messages that occur within exceptions but does not have any impact on other operations.
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\comfy\sample.py", line 93, in sample
    real_model, positive_copy, negative_copy, noise_mask, models = prepare_sampling(model, noise.shape, positive, negative, noise_mask)
                                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\comfy\sample.py", line 86, in prepare_sampling
    comfy.model_management.load_models_gpu([model] + models, model.memory_required([noise_shape[0] * 2] + list(noise_shape[1:])) + inference_memory)
  File "D:\stable-diffusion\comfy\ComfyUI\comfy\model_management.py", line 410, in load_models_gpu
    cur_loaded_model = loaded_model.model_load(lowvram_model_memory)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\comfy\model_management.py", line 293, in model_load
    raise e
  File "D:\stable-diffusion\comfy\ComfyUI\comfy\model_management.py", line 289, in model_load
    self.real_model = self.model.patch_model(device_to=patch_model_to) #TODO: do something with loras and offloading to CPU
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\ComfyUI\comfy\model_patcher.py", line 202, in patch_model
    self.model.to(device_to)
  File "D:\stable-diffusion\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1160, in to
    return self._apply(convert)
           ^^^^^^^^^^^^^^^^^^^^
  File "D:\stable-diffusion\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\stable-diffusion\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  File "D:\stable-diffusion\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 810, in _apply
    module._apply(fn)
  [Previous line repeated 2 more times]
  File "D:\stable-diffusion\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 833, in _apply
    param_applied = fn(param)
                    ^^^^^^^^^
  File "D:\stable-diffusion\comfy\python_embeded\Lib\site-packages\torch\nn\modules\module.py", line 1158, in convert
    return t.to(device, dtype if t.is_floating_point() or t.is_complex() else None, non_blocking)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 4.84 GiB
Requested               : 7.03 MiB
Device limit            : 11.99 GiB
Free (according to CUDA): 4.82 GiB
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

Prompt executed in 39.23 seconds

Stopped server
```
I don't know if this is an error with your pack or something else, but obviously it's a bug as the memory limit is way above the requested amount.
BTW, how can I properly set the PyTorch limit, as that one's way out of hand for some reason

**Comment by ltdrdata** [comment]
It's not a Impact Pack issue. Impact KSampler is just a wrapper of built-in KSampler.
