### ISSUE TITLE
DetailerDebug (SEGS): scale_tensor is not defined

### ISSUE THREAD

**Issue by MikkoMMM** [ltdrdata/ComfyUI-Impact-Pack#385]
I used the workflow (for DreamShaper XL) found in https://pastebin.com/NjGG1t0W, and I believe the node DetailerDebug (SEGS) is where it failed with this in the log:

```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "execution.py", line 153, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "execution.py", line 83, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "execution.py", line 76, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1284, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps,
  File "custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 189, in do_detail
    segs = core.segs_scale_match(segs, image.shape)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 702, in segs_scale_match
    cropped_image = scale_tensor(new_w, new_h, torch.from_numpy(cropped_image))
                    ^^^^^^^^^^^^
NameError: name 'scale_tensor' is not defined
```

**Comment by ltdrdata** [comment]
This is fixed on V4.48.5
