### ISSUE TITLE
(IMPORT FAILED) Subpack - path appears to be incomplete

### ISSUE THREAD

**Issue by titanito** [ltdrdata/ComfyUI-Impact-Pack#388]
**I have installed ComfyUI-Impact-Pack and the subpack correctly, however it gives me an error, What I can do?**

### Loading: ComfyUI-Impact-Pack (V4.46)
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['D:\\IA\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
'Logger' object has no attribute 'encoding'

!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
        https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!

### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack

  The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
  Recommended to delete the path and restart ComfyUI.
  If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.

---------------------------------
Traceback (most recent call last):
  File "D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 439, in <module>
    import impact.subpack_nodes
  File "D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
  File "D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 15, in <module>
    raise e
  File "D:\IA\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subcore.py", line 11, in <module>
    from ultralytics import YOLO
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\__init__.py", line 5, in <module>
    from ultralytics.models import RTDETR, SAM, YOLO
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\__init__.py", line 3, in <module>
    from .rtdetr import RTDETR
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\__init__.py", line 3, in <module>
    from .model import RTDETR
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\models\rtdetr\model.py", line 10, in <module>
    from ultralytics.engine.model import Model
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\engine\model.py", line 8, in <module>
    from ultralytics.cfg import TASK2DATA, get_cfg, get_save_dir
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\cfg\__init__.py", line 10, in <module>
    from ultralytics.utils import (ASSETS, DEFAULT_CFG, DEFAULT_CFG_DICT, DEFAULT_CFG_PATH, LOGGER, RANK, ROOT, RUNS_DIR,
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 265, in <module>
    LOGGER = set_logging(LOGGING_NAME, verbose=VERBOSE)  # define globally (used in train.py, val.py, predict.py, etc.)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\IA\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\__init__.py", line 233, in set_logging
    if WINDOWS and sys.stdout.encoding != 'utf-8':
                   ^^^^^^^^^^^^^^^^^^^
AttributeError: 'Logger' object has no attribute 'encoding'

**Comment by ltdrdata** [comment]
Your ComfyUI-Manager is outdated.

Make sure

```
### Loading: ComfyUI-Manager (V1.15)
```

**Comment by titanito** [comment]
It is updated, that is not the reason for the problem

**Comment by ltdrdata** [comment]
> It is updated, that is not the reason for the problem

I am pretty sure. That is the problem. Because that issue is caused by outdated ComfyUI-Manager.

Logger module doesn't exist on latest ComfyUI-Manager.

If your issue is persistent.

You are failing to update ComfyUI-Manager.

Make sure ComfyUI-Manager version info.
That should be V1.15.
