### ISSUE TITLE
Error occurred when executing SEGSDetailerForAnimateDiff

### ISSUE THREAD

**Issue by wingaturumqi** [ltdrdata/ComfyUI-Impact-Pack#422]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\sd-webui-aki\comfyui\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\sd-webui-aki\comfyui\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\sd-webui-aki\comfyui\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\sd-webui-aki\comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\segs_nodes.py", line 201, in doit
    segs = SEGSDetailerForAnimateDiff.do_detail(image_frames, segs, guide_size, guide_size_for, max_size, seed, steps, cfg, sampler_name,
  File "D:\sd-webui-aki\comfyui\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\segs_nodes.py", line 191, in do_detail
    new_cropped_image = enhanced_image_tensor.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

**Comment by ltdrdata** [comment]
Your Impact Pack is an outdated version. Try again after updating.

**Comment by wingaturumqi** [comment]
thks ,I try the newest vision,but it happend again,

**Comment by ltdrdata** [comment]
> thks ,I try the newest vision,but it happend again,

Show me the new log.
