### ISSUE TITLE
Face Detailer Exception when passing New Image Batch

### ISSUE THREAD

**Issue by Malbathla** [ltdrdata/ComfyUI-Impact-Pack#427]
After Updating (Comfy & All Custom Nodes) when I attempt to use the New MakeImageBatch and Pass it to the FaceDetailer it generates the below error.

[2024-01-12 01:00] Loading 1 new model
[2024-01-12 01:00] Loads SAM model: E:\AI\ComfyUI_windows_portable\ComfyUI\models\sams\sam_vit_b_01ec64.pth (device:AUTO)
[2024-01-12 01:00] 0: 384x640 1 face, 101.6ms
[2024-01-12 01:00] Speed: 58.7ms preprocess, 101.6ms inference, 718.6ms postprocess per image at shape (1, 3, 384, 640)
[2024-01-12 01:00] semd to cuda:0
[2024-01-12 01:00] ERROR:root:!!! Exception during processing !!!
[2024-01-12 01:00] ERROR:root:Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 154, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 84, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 77, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 498, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 438, in enhance_face
    sam_mask = core.make_sam_mask(sam_model_opt, segs, image, sam_detection_hint, sam_dilation,
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 499, in make_sam_mask
    predictor.set_image(image, "RGB")
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 112, in forward
    x = blk(x)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 174, in forward
    x = self.attn(x)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 234, in forward
    attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 358, in add_decomposed_rel_pos
    attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 8.78 GiB
Requested               : 768.00 MiB
Device limit            : 12.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

(Checking as this is running, I am not even approaching my GPU memory limit - and have rendered more GPU memory intensive images in the past)

I am Batching 3x (1344x768) Images .. When I remove the new node and only pass a single Image all works as expected.

Along with this I am getting numerous errors when attempting to load any workflows with FaceDetailer in them (all reroutes are breaking and messing the entire workflow) - not sure if related as there are times when attempting to link to an input on the FaceDetailer it will not link and instead selects the Detailer node and it requires a complete refresh of the browser (and the above mentioned resoute errors) to release it.

I have updated all Custom Nodes and ComfyUI, I have closed ComfyUi several times and restarted it - but the issue above is still there and I am unable to load any workflows that contain the New Impact nodes or facedetailer - I have also 'fixed/Reloaded' facedetailer several times to try to resolve this.

**Comment by Malbathla** [comment]
I removed the MakeImageBatch node but the problem still occured with just a single image attached to the FaceDetailer.  I then realised I had not removed the splitter at the end of the workflow - and once I removed that the FaceDetailer node functioned correctly without the above error. ???

ComfyUI: 1895\[977eda\] (2024-01-11)
Manager: V1.25.4
Not sure how to check Impact version I have - but I have the new nodes so recent as of 24hrs ago

**Comment by ltdrdata** [comment]
> I removed the MakeImageBatch node but the problem still occured with just a single image attached to the FaceDetailer. I then realised I had not removed the splitter at the end of the workflow - and once I removed that the FaceDetailer node functioned correctly without the above error. ???
> 
> ComfyUI: 1895[977eda] (2024-01-11) Manager: V1.25.4 Not sure how to check Impact version I have - but I have the new nodes so recent as of 24hrs ago

You can check impact pack version on startup log.

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/10da1d81-d8a2-4dc6-92e8-c158c5f58d9a)

**Comment by Malbathla** [comment]
Thanks

[2024-01-12 12:36] ### Loading: ComfyUI-Impact-Pack (V4.62)
[2024-01-12 12:36] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[2024-01-12 12:36] [Impact Pack] Wildcards loading done.
[2024-01-12 12:36] ### Loading: ComfyUI-Inspire-Pack (V0.58.2)
[2024-01-12 12:36] ### Loading: ComfyUI-Manager (V1.25.4)
[2024-01-12 12:36] ### ComfyUI Revision: 1895 [977eda19] | Released on '2024-01-11'

I notice I have a different Comfy Revision .. could this be a comfy problem and not Impact pack?

**Comment by ltdrdata** [comment]
> 977eda19

That's simply because I use a more recent version. Not a big deal. 
Change device mode of SAMLoader to CPU or set `--disable-smart-memory`

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/15fe9920-7d8d-4e4e-b0be-56b84ce74f79)

Since the current memory usage calculation of SAMLoader is beyond the scope of ComfyUI's core memory calculation, using smart memory can be problematic if it doesn't effectively clear VRAM in most cases.
I am aware of this issue and plan to address it for improvement.

**Comment by Malbathla** [comment]
Thank you again .. I have just run ComfyUI update prior to launching (previously I was doing it all via manager but did it this way to check versions etc) and I am now on the same revision.  Yes I have always just left it set at AUTO so will try changing it specifically and see how it goes (so yes - more a Comfy Core issue :) )

Awesome nodes btw.  Thank You

Update: Changing it to CPU seems to have resolved it and I can now FaceDetail Image Batch without the exception above (AUTO or GPU Prefer both crash for me)

**Comment by Malbathla** [comment]
👍

**Comment by Malbathla** [comment]
👍

**Comment by ltdrdata** [comment]
I just updated to reflect memory management. Keep the option set to "auto" once and check if there are any issues.

**Comment by Malbathla** [comment]
Unfortunately it still threw an exception

![version](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/84999459/521ba541-5060-4b03-88be-34cfe36e10f2)
![Setting](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/84999459/b49c4020-3c86-4086-b40e-9b6be8c8ffe6)
![Error](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/84999459/55d25340-46a6-4f3c-92c9-4afced3dee33)

I did notice that the currently allocated has increased - even after a complete restart of my system to ensure there was no other processes in the background.

The FaceDetailer starts - detects the first face and then throws the exception

> 0: 384x640 1 face, 99.5ms
> Speed: 32.5ms preprocess, 99.5ms inference, 437.2ms postprocess per image at shape (1, 3, 384, 640)
> semd to cuda:0
> ERROR:root:!!! Exception during processing !!!

I rebuilt my workflow with FaceDetailerPipe .. but checking it throws the same error regardless of Pipe version on Not

**Comment by ltdrdata** [comment]
Now, if VRAM acquisition fails due to lack of free space, SAM model is not moved to the GPU. Try it again.
(V4.65.2)

**Comment by Malbathla** [comment]
[2024-01-14 00:40] ### Loading: ComfyUI-Impact-Pack (V4.66.1)
[2024-01-14 00:40] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.4)
[2024-01-14 00:40] ### Loading: ComfyUI-Inspire-Pack (V0.59)
[2024-01-14 00:40] [Impact Pack] Wildcards loading done.
[2024-01-14 00:40] ### Loading: ComfyUI-Manager (V1.26)
[2024-01-14 00:40] ### ComfyUI Revision: 1901 [56d9496b] | Released on '2024-01-12'

On initially loading the workflow - I changed to AUTO and once again got the exception .. however this only seemed to occur the first time running the prompt since it it loading everything .. after closing the exception I simply hit Queue again and it went through the FaceDetailer correctly with no error.  I have checked and it still shows as being AUTO and have run several prompts through it with no further exceptions.

Closing ComfyUI and restarting it I again get the exception on first run .. but once I close the exception modal I just hit queue prompt again and all is good *shrug*  

(I assume this is what you mean about not moved to GPU if it fails)

Hope that helps

**Comment by ltdrdata** [comment]
Specifically, which node is experiencing Out Of Memory (OOM)?

**Comment by Malbathla** [comment]
It appears to be FaceDetailer & FaceDetailerPipe .. But only when I first run the workflow after a clean ComfyUI start .. Once I close the Exception message I can hit Queue Prompt immediately and it will run fine with no errors.

(I am not doing Video processing btw - standard images (x3) Batched into FaceDetailer and split again after)

Based on the Console output below it appears to be triggering by FaceDetailer but actually be --> 'segment_anything\modeling\image_encoder.py", line 358, in add_decomposed_rel_pos' and not FaceDetailer directly *shrug* Anyway I hope this helps in some way (and that you can make sense of the console dump).. I can however run Exception free by setting the SAM Loader to CPU so I'm not stressed about the problem

Looking at the console

```
Requested to load SDXLRefinerClipModel
Loading 1 new model
Loads SAM model: E:\AI\ComfyUI_windows_portable\ComfyUI\models\sams\sam_vit_b_01ec64.pth (device:AUTO)
[Impact Pack] WARN: FaceDetailer is not a node designed for video detailing. If you intend to perform video detailing, please use Detailer For AnimateDiff.

0: 384x640 1 face, 100.9ms
Speed: 29.4ms preprocess, 100.9ms inference, 839.4ms postprocess per image at shape (1, 3, 384, 640)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 155, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 85, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\execution.py", line 78, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1222, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 448, in enhance_face
    sam_mask = core.make_sam_mask(sam_model_opt, segs, image, sam_detection_hint, sam_dilation,
  File "E:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 503, in make_sam_mask
    predictor.set_image(image, "RGB")
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\predictor.py", line 60, in set_image
    self.set_torch_image(input_image_torch, image.shape[:2])
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\utils\_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\predictor.py", line 89, in set_torch_image
    self.features = self.model.image_encoder(input_image)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 112, in forward
    x = blk(x)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 174, in forward
    x = self.attn(x)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\torch\nn\modules\module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 234, in forward
    attn = add_decomposed_rel_pos(attn, q, self.rel_pos_h, self.rel_pos_w, (H, W), (H, W))
  File "E:\AI\ComfyUI_windows_portable\python_embeded\lib\site-packages\segment_anything\modeling\image_encoder.py", line 358, in add_decomposed_rel_pos
    attn.view(B, q_h, q_w, k_h, k_w) + rel_h[:, :, :, :, None] + rel_w[:, :, :, None, :]
torch.cuda.OutOfMemoryError: Allocation on device 0 would exceed allowed memory. (out of memory)
Currently allocated     : 8.99 GiB
Requested               : 768.00 MiB
Device limit            : 12.00 GiB
Free (according to CUDA): 0 bytes
PyTorch limit (set by user-supplied memory fraction)
                        : 17179869184.00 GiB

```

**Comment by ltdrdata** [comment]
In the previous patch, I primarily attempted based on the available VRAM capacity. However, in new patch, I have made modifications to ensure that in cases where the transfer to VRAM fails due to a mismatch with the predicted surplus capacity, the execution will not crash but instead operate normally in CPU.
