### ISSUE TITLE
Cannot Import ComfyUI-Impact-Pack module for custom nodes: attempted relative import beyond top-level package

### ISSUE THREAD

**Issue by cyberopt** [ltdrdata/ComfyUI-Impact-Pack#458]
I installed the ComfyUI-Impact-Pack via the ComfyUI Manager. When I reloaded ComfyUI, I received an error stating the ComfyUI-Impact-Pack failed to import. below is the logged result of the the error:

Traceback (most recent call last):
  File "/.../.../ComfyUI/nodes.py", line 1810, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/.../.../ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 72, in <module>
    import impact.impact_server  # to load server api
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../.../ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_server.py", line 13, in <module>
    import impact.core as core
  File "/.../.../ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 1, in <module>
    from segment_anything import SamPredictor
  File "/.../.../ComfyUI/custom_nodes/comfyui_controlnet_aux/src/controlnet_aux/segment_anything/__init__.py", line 17, in <module>
    from ..util import HWC3, resize_image
ImportError: attempted relative import beyond top-level package

Cannot import /.../.../ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: attempted relative import beyond top-level package

**Comment by ltdrdata** [comment]
Your controlnet aux custom node is outdated version.
