### ISSUE TITLE
ultralytics detector node load error

### ISSUE THREAD

**Issue by amao2001** [ltdrdata/ComfyUI-Impact-Pack#466]
when i start comfyui but the ultralytics detector node load error. i am sure the comfyui-manager is the last version. the whole startup information below
** ComfyUI startup time: 2024-02-04 09:53:05.608860
[2024-02-04 09:53] ** Platform: Linux
[2024-02-04 09:53] ** Python version: 3.10.12 (main, Jul  5 2023, 18:54:27) [GCC 11.2.0]
[2024-02-04 09:53] ** Python executable: /home/ganloss/miniconda3/envs/comfyui/bin/python
[2024-02-04 09:53] ** Log path: /mnt/ganloss/comfyui/ComfyUI/comfyui.log
[2024-02-04 09:53] 
Prestartup times for custom nodes:
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Marigold
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/rgthree-comfy
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-02-04 09:53] 
[2024-02-04 09:53] Total VRAM 7972 MB, total RAM 32018 MB
/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
[2024-02-04 09:53] xformers version: 0.0.24
[2024-02-04 09:53] Set vram state to: LOW_VRAM
[2024-02-04 09:53] Device: cuda:0 NVIDIA GeForce RTX 2070 : cudaMallocAsync
[2024-02-04 09:53] VAE dtype: torch.float32
[2024-02-04 09:53] Using xformers cross attention
[2024-02-04 09:53] Adding extra search path checkpoints /mnt/ganloss/sdwebui/stable-diffusion-webui/models/Stable-diffusion
[2024-02-04 09:53] Adding extra search path configs /mnt/ganloss/sdwebui/stable-diffusion-webui/models/Stable-diffusion
[2024-02-04 09:53] Adding extra search path vae /mnt/ganloss/sdwebui/stable-diffusion-webui/models/VAE
[2024-02-04 09:53] Adding extra search path loras /mnt/ganloss/sdwebui/stable-diffusion-webui/models/Lora
[2024-02-04 09:53] Adding extra search path loras /mnt/ganloss/sdwebui/stable-diffusion-webui/models/LyCORIS
[2024-02-04 09:53] Adding extra search path upscale_models /mnt/ganloss/sdwebui/stable-diffusion-webui/models/ESRGAN
[2024-02-04 09:53] Adding extra search path upscale_models /mnt/ganloss/sdwebui/stable-diffusion-webui/models/RealESRGAN
[2024-02-04 09:53] Adding extra search path upscale_models /mnt/ganloss/sdwebui/stable-diffusion-webui/models/SwinIR
[2024-02-04 09:53] Adding extra search path embeddings /mnt/ganloss/sdwebui/stable-diffusion-webui/embeddings
[2024-02-04 09:53] Adding extra search path hypernetworks /mnt/ganloss/sdwebui/stable-diffusion-webui/models/hypernetworks
[2024-02-04 09:53] Adding extra search path controlnet /mnt/ganloss/sdwebui/stable-diffusion-webui/extensions/sd-webui-controlnet/models
[2024-02-04 09:53] ### Loading: Workspace Manager (V1.0.0)
[2024-02-04 09:53] ### Loading: ComfyUI-Impact-Pack (V4.73.3)
[2024-02-04 09:53] 'NoneType' object is not iterable
[2024-02-04 09:53] 
!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
	https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!
[2024-02-04 09:53] 
[2024-02-04 09:53] ### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
[2024-02-04 09:53] ### ComfyUI-Impact-Pack: Check dependencies
[2024-02-04 09:53] ### ComfyUI-Impact-Pack: Updating subpack
[2024-02-04 09:53] [Impact Pack] EXECUTE: ['/home/ganloss/miniconda3/envs/comfyui/bin/python', 'install.py'] in '/mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
[2024-02-04 09:53] /home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
[2024-02-04 09:53]   _torch_pytree._register_pytree_node(
[2024-02-04 09:53] [2024-02-04 09:53] req_path: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
[2024-02-04 09:53] req_path: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
[2024-02-04 09:53] req_path: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
[2024-02-04 09:53] ### ComfyUI-Impact-Pack: Check basic models
[2024-02-04 09:53] [Impact Pack] Wildcards loading done.
[2024-02-04 09:53] 'NoneType' object is not iterable
[2024-02-04 09:53] 
!!!!!

[ComfyUI-Impact-Subpack] If this error occurs, please check the following link:
	https://github.com/ltdrdata/ComfyUI-Impact-Pack/blob/Main/troubleshooting/TROUBLESHOOTING.md

!!!!!
[2024-02-04 09:53] 
[2024-02-04 09:53] ### ComfyUI-Impact-Pack: (IMPORT FAILED) Subpack
[2024-02-04 09:53] 
[2024-02-04 09:53]   The module at the `custom_nodes/ComfyUI-Impact-Pack/impact_subpack` path appears to be incomplete.
[2024-02-04 09:53]   Recommended to delete the path and restart ComfyUI.
[2024-02-04 09:53]   If the issue persists, please report it to https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues.
[2024-02-04 09:53] 
---------------------------------
Traceback (most recent call last):
[2024-02-04 09:53]   File "/mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 474, in <module>
    import impact.subpack_nodes
[2024-02-04 09:53]   File "/mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subpack_nodes.py", line 4, in <module>
    import impact.subcore as subcore
[2024-02-04 09:53]   File "/mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 15, in <module>
    raise e
[2024-02-04 09:53]   File "/mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 11, in <module>
    from ultralytics import YOLO
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/data/base.py", line 18, in <module>
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM_BAR_FORMAT
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 840, in <module>
    SETTINGS = SettingsManager()  # initialize settings
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 780, in __init__
    self.load()
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 794, in load
    self.update(yaml_load(self.file))
[2024-02-04 09:53]   File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 802, in update
    new = dict(*args, **kwargs)
[2024-02-04 09:53] TypeError: 'NoneType' object is not iterable
[2024-02-04 09:53] [2024-02-04 09:53] ---------------------------------
[2024-02-04 09:53] 
[2024-02-04 09:53] Adding /mnt/ganloss/comfyui/ComfyUI/custom_nodes to sys.path
[2024-02-04 09:53] 
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
[2024-02-04 09:53] Loaded efficiency nodes from /mnt/ganloss/comfyui/ComfyUI/custom_nodes/efficiency-nodes-comfyui
[2024-02-04 09:53] Loaded ControlNetPreprocessors nodes from /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui_controlnet_aux
[2024-02-04 09:53] [Errno 2] No such file or directory: '/mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet/control/control.py/__init__.py'
[2024-02-04 09:53] Could not find AnimateDiff nodes
[2024-02-04 09:53] Loaded IPAdapter nodes from /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
[2024-02-04 09:53] Loaded VideoHelperSuite from /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
[2024-02-04 09:53] [34mWAS Node Suite: [0mBlenderNeko's Advanced CLIP Text Encode found, attempting to enable `CLIPTextEncode` support.[0m
[2024-02-04 09:53] [34mWAS Node Suite: [0m`CLIPTextEncode (BlenderNeko Advanced + NSP)` node enabled under `WAS Suite/Conditioning` menu.[0m
[2024-02-04 09:53] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[2024-02-04 09:53] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `/mnt/ganloss/comfyui/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[2024-02-04 09:53] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m212[0m [32mnodes successfully.[0m
[2024-02-04 09:53] 
	[3m[93m"Success is not just about making money. It's about making a difference."[0m[3m - Unknown[0m
[2024-02-04 09:53] 
[2024-02-04 09:53] [92m[tinyterraNodes] [32mLoaded[0m
[2024-02-04 09:53] [34mDavemane42 Custom Nodes: [92mLoaded[0m
[2024-02-04 09:53] ### Loading: ComfyUI-Manager (V2.7)
[2024-02-04 09:53] ### ComfyUI Revision: 1951 [d0e2354c] | Released on '2024-02-02'
[2024-02-04 09:53] ------------------------------------------------
[2024-02-04 09:53] [34mComfyroll Custom Nodes v1.50 : [92m 150 Nodes Loaded[0m
[2024-02-04 09:53] ------------------------------------------------
INFO:comfyui-prompt-control:Use STYLE:weight_interpretation:normalization at the start of a prompt to use advanced encodings
[2024-02-04 09:53] INFO:comfyui-prompt-control:Weight interpretations available: comfy,A1111,compel,comfy++,down_weight,perp
[2024-02-04 09:53] INFO:comfyui-prompt-control:Normalization types available: none,mean,length,length+mean
[2024-02-04 09:53] [34mFizzleDorf Custom Nodes: [92mLoaded[0m
[2024-02-04 09:53] 
[2024-02-04 09:53] [32m[1m[rgthree] Loaded 22 exciting nodes.[0m
[2024-02-04 09:53] [32m[rgthree] Optimizing ComfyUI recursive execution. [33mIf queueing and/or re-queueing seems broken, change "patch_recursive_execution" to false in rgthree_config.json [0m
[2024-02-04 09:53] 
[2024-02-04 09:53] Total VRAM 7972 MB, total RAM 32018 MB
[2024-02-04 09:53] xformers version: 0.0.24
[2024-02-04 09:53] Set vram state to: LOW_VRAM
[2024-02-04 09:53] Device: cuda:0 NVIDIA GeForce RTX 2070 : cudaMallocAsync
[2024-02-04 09:53] VAE dtype: torch.float32
[2024-02-04 09:53] Torch version: 2.2.0+cu121
[2024-02-04 09:53] ### Loading: ComfyUI-Inspire-Pack (V0.63)
[2024-02-04 09:53] 
Import times for custom nodes:
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/efficiency-nodes-comfyui
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/kohya-hires-fix.py
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/highresfix.py
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/sdxl-recommended-res-calc
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/style_aligned_comfy
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_Noise
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/sigmas_tools_and_the_golden_scheduler
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-RAVE
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_ADV_CLIP_emb
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfy_clip_blip_node
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui-portrait-master
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/a-person-mask-generator
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_Dave_CustomNode
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui_controlnet_aux
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui-workspace-manager
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-VideoHelperSuite
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui-inpaint-nodes
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Flowty-LDSR
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_FizzNodes
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/steerable-motion
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Advanced-ControlNet
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Frame-Interpolation
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/rgthree-comfy
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Loopchain
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/clipseg.py
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-AnimateDiff-Evolved
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_essentials
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui-svd-temporal-controlnet
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-KJNodes
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Manager
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui-reactor-node
[2024-02-04 09:53]    0.0 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
[2024-02-04 09:53]    0.1 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-MotionCtrl
[2024-02-04 09:53]    0.1 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Marigold
[2024-02-04 09:53]    0.1 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/Comfyui_Lama
[2024-02-04 09:53]    0.2 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI_tinyterraNodes
[2024-02-04 09:53]    0.2 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui-art-venture
[2024-02-04 09:53]    0.2 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfyui-prompt-control
[2024-02-04 09:53]    0.7 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-LaMA-Preprocessor
[2024-02-04 09:53]    0.7 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/was-node-suite-comfyui
[2024-02-04 09:53]    1.8 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/comfy_controlnet_preprocessors
[2024-02-04 09:53]    7.2 seconds: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Impact-Pack
[2024-02-04 09:53] 
[2024-02-04 09:53] Starting server
[2024-02-04 09:53] 
[2024-02-04 09:53] To see the GUI go to: http://0.0.0.0:8188
[2024-02-04 09:53] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-02-04 09:53] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-02-04 09:53] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-02-04 09:53] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-02-04 09:53] FETCH DATA from: /mnt/ganloss/comfyui/ComfyUI/custom_nodes/ComfyUI-Manager/extension-node-map.json

**Comment by ltdrdata** [comment]
Execute this.

```
/home/ganloss/miniconda3/envs/comfyui/bin/python -c "from ultralytics import YOLO"
```

What message is displayed?

**Comment by amao2001** [comment]
i got this message below
/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/transformers/utils/generic.py:441: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  _torch_pytree._register_pytree_node(
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/__init__.py", line 5, in <module>
    from ultralytics.hub import start
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/hub/__init__.py", line 5, in <module>
    from ultralytics.data.utils import HUBDatasetStats
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/data/__init__.py", line 3, in <module>
    from .base import BaseDataset
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/data/base.py", line 18, in <module>
    from ultralytics.utils import DEFAULT_CFG, LOCAL_RANK, LOGGER, NUM_THREADS, TQDM_BAR_FORMAT
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 840, in <module>
    SETTINGS = SettingsManager()  # initialize settings
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 780, in __init__
    self.load()
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 794, in load
    self.update(yaml_load(self.file))
  File "/home/ganloss/miniconda3/envs/comfyui/lib/python3.10/site-packages/ultralytics/utils/__init__.py", line 802, in update
    new = dict(*args, **kwargs)
TypeError: 'NoneType' object is not iterable

**Comment by ltdrdata** [comment]
Show me the result of this.
`/home/ganloss/miniconda3/envs/comfyui/bin/python -m pip freeze`

**Comment by amao2001** [comment]
absl-py==1.4.0
accelerate==0.26.1
addict==2.4.0
aiofiles==23.2.1
aiohttp==3.8.5
aiosignal==1.3.1
albumentations==0.5.2
altair==5.2.0
annotated-types==0.5.0
antlr4-python3-runtime==4.8
anyio==4.2.0
astunparse==1.6.3
async-timeout==4.0.2
attrs==23.1.0
audioread==3.0.1
av==11.0.0
basicsr==1.4.2
boltons==23.0.0
braceexpand==0.1.7
cachetools==5.3.1
certifi==2023.7.22
cffi==1.15.1
chardet==5.2.0
charset-normalizer==3.2.0
click==8.1.6
clip @ git+https://github.com/openai/CLIP.git@a1d071733d7111c9c014f024669f959182114e33
clip-interrogator==0.6.0
cmake==3.27.0
color-matcher==0.5.0
colorama==0.4.6
coloredlogs==15.0.1
colorlog==6.8.0
contourpy==1.1.0
cryptography==41.0.7
cssselect2==0.7.0
cycler==0.11.0
Cython==3.0.7
ddt==1.7.0
decorator==4.4.2
decord==0.6.0
diffusers==0.25.0
dill==0.3.7
distro==1.9.0
docutils==0.20.1
easydict==1.9
einops==0.6.1
exceptiongroup==1.2.0
fairscale==0.4.4
fastapi==0.109.0
ffmpy @ git+https://github.com/WASasquatch/ffmpy.git@f000737698b387ffaeab7cd871b0e9185811230d
filelock==3.12.2
fire==0.5.0
flatbuffers==23.5.26
fonttools==4.41.1
freetype-py==2.4.0
frozenlist==1.4.0
fsspec==2023.6.0
ftfy==6.1.1
future==0.18.3
fvcore==0.1.5.post20221221
gast==0.5.4
gitdb==4.0.10
GitPython==3.1.32
google-auth==2.23.3
google-auth-oauthlib==1.0.0
google-pasta==0.2.0
gradio==3.37.0
gradio_client==0.8.0
grpcio==1.59.0
h11==0.14.0
h5py==3.10.0
httpcore==1.0.2
httpx==0.26.0
huggingface-hub==0.20.2
humanfriendly==10.0
hydra-core==1.1.0
idna==3.4
imageio==2.14.1
imageio-ffmpeg==0.4.7
img2texture @ git+https://github.com/WASasquatch/img2texture.git@a546609a915caf1dcb84a15bf44b5b639ad924e6
imgaug==0.4.0
importlib-metadata==6.8.0
importlib-resources==6.1.1
insightface==0.7.3
install==1.3.5
iopath==0.1.10
Jinja2==3.1.2
joblib==1.3.2
jsonschema==4.20.0
jsonschema-specifications==2023.12.1
keras==2.14.0
kiwisolver==1.4.4
kornia==0.5.0
lark==1.1.8
lazy_loader==0.3
libclang==16.0.6
librosa==0.9.2
lightning-utilities==0.10.1
linkify-it-py==2.0.2
lit==16.0.6
llvmlite==0.42.0
lmdb==1.4.1
lxml==4.9.3
mapbox-earcut==1.0.1
Markdown==3.4.4
markdown-it-py==2.2.0
MarkupSafe==2.1.3
matplotlib==3.7.2
matrix-client==0.4.0
mdit-py-plugins==0.3.3
mdurl==0.1.2
mediapipe==0.10.3
ml-dtypes==0.2.0
model-index==0.1.11
moviepy==1.0.3
mpmath==1.3.0
multidict==6.0.4
mypy-extensions==1.0.0
networkx==3.1
numba==0.59.0
numexpr==2.8.7
numpy==1.26.3
nvidia-cublas-cu12==12.1.3.1
nvidia-cuda-cupti-cu12==12.1.105
nvidia-cuda-nvrtc-cu12==12.1.105
nvidia-cuda-runtime-cu12==12.1.105
nvidia-cudnn-cu12==8.9.2.26
nvidia-cufft-cu12==11.0.2.54
nvidia-curand-cu12==10.3.2.106
nvidia-cusolver-cu12==11.4.5.107
nvidia-cusparse-cu12==12.1.0.106
nvidia-nccl-cu12==2.19.3
nvidia-nvjitlink-cu12==12.3.101
nvidia-nvtx-cu12==12.1.105
oauthlib==3.2.2
omegaconf==2.1.2
onnx==1.14.1
onnxruntime==1.15.1
onnxruntime-gpu==1.16.3
open-clip-torch==2.23.0
openai==1.7.1
opencv-contrib-python==4.8.0.74
opencv-python==4.8.0.74
opencv-python-headless==4.7.0.72
opendatalab==0.0.9
openmim==0.3.9
opt-einsum==3.3.0
ordered-set==4.1.0
orjson==3.9.10
packaging==23.1
pandas==2.0.3
peft==0.7.1
piexif==1.1.3
pilgram==1.2.1
Pillow==9.5.0
platformdirs==3.10.0
plotly==5.18.0
pooch==1.7.0
portalocker==2.7.0
prettytable==3.6.0
proglog==0.1.10
protobuf==3.20.3
psutil==5.9.5
py-cpuinfo==9.0.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycocoevalcap==1.2
pycocotools==2.0.7
pycollada==0.7.2
pycparser==2.21
pycryptodome==3.18.0
pydantic==2.5.3
pydantic_core==2.14.6
pydub==0.25.1
pyglet==2.0.9
Pygments==2.15.1
PyMatting==1.1.8
PyOpenGL==3.1.0
pyOpenSSL==23.3.0
pyparsing==3.0.9
pyre-extensions==0.0.29
pyrender==0.1.45
python-dateutil==2.8.2
python-multipart==0.0.6
pytorch-lightning==1.9.0
pytz==2023.3
PyWavelets==1.4.1
PyYAML==6.0.1
referencing==0.32.0
regex==2023.6.3
rembg==2.0.50
reportlab==4.0.4
requests==2.31.0
requests-oauthlib==1.3.1
resampy==0.4.2
rich==13.5.0
rpds-py==0.16.2
rsa==4.9
Rtree==1.1.0
safetensors==0.3.1
scikit-image==0.20.0
scikit-learn==1.3.1
scipy==1.11.1
seaborn==0.12.2
segment-anything==1.0
semantic-version==2.10.0
sentencepiece==0.1.99
shapely==2.0.2
shellingham==1.5.4
simple-lama-inpainting==0.1.2
simpleeval==0.9.13
six==1.16.0
smmap==5.0.0
smplx==0.1.28
sniffio==1.3.0
sounddevice==0.4.6
soundfile==0.12.1
spaces==0.19.4
starlette==0.35.1
svg.path==6.3
svglib==1.5.1
sympy==1.12
tabulate==0.9.0
taichi==1.6.0
taming-transformers-rom1504==0.0.6
tb-nightly==2.15.0a20231017
tenacity==8.2.3
tensorboard==2.14.1
tensorboard-data-server==0.7.1
tensorflow==2.14.0
tensorflow-estimator==2.14.0
tensorflow-io-gcs-filesystem==0.34.0
termcolor==2.3.0
threadpoolctl==3.2.0
tifffile==2023.7.18
timm==0.4.12
tinycss2==1.2.1
tokenizers==0.15.0
tomli==2.0.1
tomlkit==0.12.0
toolz==0.12.0
torch==2.2.0+cu121
torchaudio==2.2.0
torchdiffeq==0.2.3
torchmetrics==1.3.0.post0
torchsde==0.2.6
torchvision==0.17.0
tqdm==4.65.0
trampoline==0.1.2
transformers==4.36.2
trimesh==3.21.7
triton==2.2.0
typer==0.9.0
typing-inspect==0.9.0
typing_extensions==4.9.0
tzdata==2023.3
uc-micro-py==1.0.2
ultralytics==8.0.145
urllib3==1.26.18
uvicorn==0.26.0
watchdog==3.0.0
wcwidth==0.2.6
webdataset==0.2.57
webencodings==0.5.1
websockets==11.0.3
Werkzeug==3.0.0
wget==3.2
wldhx.yadisk-direct==0.0.6
wrapt==1.14.1
xformers==0.0.24
xxhash==3.4.1
yacs==0.1.8
yapf==0.40.1
yarl==1.9.2
zipp==3.16.2

**Comment by ltdrdata** [comment]
Execute this and try again.
`/home/ganloss/miniconda3/envs/comfyui/bin/python -m pip install opencv-python-headless==4.8.0.74`

**Comment by amao2001** [comment]
install opencv-python-headless==4.8.0.74
(comfyui) ganloss@AI:/mnt/ganloss/comfyui/ComfyUI$ pip list | grep opencv
opencv-contrib-python        4.8.0.74
opencv-python                4.8.0.74
opencv-python-headless       4.8.0.74

but the same error
