### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by Study098** [ltdrdata/ComfyUI-Impact-Pack#472]
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\modules\impact\animatediff_nodes.py", line 146, in doit
    enhanced_seg, cnet_images = SEGSDetailerForAnimateDiff().do_detail(image_frames, single_seg, guide_size, guide_size_for, max_size, seed, steps, cfg, sampler_name, scheduler,
  File "E:\ComfyUI\Blender_ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack-Main\modules\impact\animatediff_nodes.py", line 68, in do_detail
    cropped_image_frames = cropped_image_frames.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

Prompt executed in 21.35 seconds

**Comment by ltdrdata** [comment]
This is fixed.
