### ISSUE TITLE
Error in FaceDetailer after ComfyUI update

### ISSUE THREAD

**Issue by Tromazing** [ltdrdata/ComfyUI-Impact-Pack#477]
Using ComfyUI through Stability Matrix:

ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\StableDiffusion\Packages\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\StableDiffusion\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1249, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File "D:\StableDiffusion\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 468, in enhance_face
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for_bbox, max_size, seed, steps, cfg,
  File "D:\StableDiffusion\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 247, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "D:\StableDiffusion\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 233, in enhance_detail
    latent_image = to_latent_image(upscaled_image, vae)
  File "D:\StableDiffusion\Packages\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 498, in to_latent_image
    pixels = nodes.VAEEncode.vae_encode_crop_pixels(pixels)
AttributeError: type object 'VAEEncode' has no attribute 'vae_encode_crop_pixels'

**Comment by ltdrdata** [comment]
This is fixed.
