### ISSUE TITLE
AttributeError: 'ControlNetAdvancedWrapper' object has no attribute 'doit_ipadapter'

### ISSUE THREAD

**Issue by dchatel** [ltdrdata/ComfyUI-Impact-Pack#491]
It seems to be caused by the following node.
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/1372055/0ff0f542-b281-41a2-ac9c-7f5de39a7d9c)
```
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "G:\ai\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "G:\ai\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "G:\ai\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 366, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 249, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "G:\ai\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 228, in enhance_detail
    model, cnet_pils2 = control_net_wrapper.doit_ipadapter(model)
AttributeError: 'ControlNetAdvancedWrapper' object has no attribute 'doit_ipadapter'
```

Apparently, on `core.py` between lines 1545 and 1641, where ControlNet wrappers are defined, only ControlNetWrapper has doit_adapter. The Advanced version does not have it.

**Comment by abhinavzspace** [comment]
I am facing exactly the same issue.

```
Detailer: segment upscale for ((247.95923, 302.70422)) | crop region (371, 454) x 2.2565764438712916 -> (837, 1024)
ERROR:root:!!! Exception during processing !!!
ERROR:root:Traceback (most recent call last):
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\Users\abhinav\projects\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\Users\abhinav\projects\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1440, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps, cfg,
  File "C:\Users\abhinav\projects\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 249, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
  File "C:\Users\abhinav\projects\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 228, in enhance_detail
    model, cnet_pils2 = control_net_wrapper.doit_ipadapter(model)
AttributeError: 'ControlNetAdvancedWrapper' object has no attribute 'doit_ipadapter'
```

**Comment by ltdrdata** [comment]
This is fixed.
