### ISSUE TITLE
add node `UltralyticsDetectorProvider` will break down all the ComfyUI

### ISSUE THREAD

**Issue by ponymushama** [ltdrdata/ComfyUI-Impact-Pack#501]
When install ComfyUI-Impact-Pack I meet this error.

I use Apple M2 Max

My OS is macOS Sonoma 14.3.1 (23D60)

Then add node `UltralyticsDetectorProvider` will break down ComfyUI.

```
Install custom node 'ComfyUI Impact Pack'
install: ['https://github.com/ltdrdata/ComfyUI-Impact-Pack']
Download: git clone 'https://github.com/ltdrdata/ComfyUI-Impact-Pack'
100%|███████████| 2460.0/2460.0 [00:04<00:00, 573.30it/s]
Install: pip packages

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'segment-anything']

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'scikit-image']

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'piexif']

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'transformers']

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'opencv-python-headless']

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'GitPython']
   Install: install script

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', 'install.py']
[!] Traceback (most recent call last):
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1348, in do_open
[!]     h.request(req.get_method(), req.selector, req.data, headers,
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1286, in request
[!]     self._send_request(method, url, body, headers, encode_chunked)
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1332, in _send_request
[!]     self.endheaders(body, encode_chunked=encode_chunked)
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1281, in endheaders
[!]     self._send_output(message_body, encode_chunked=encode_chunked)
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1041, in _send_output
[!]     self.send(msg)
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 979, in send
[!]     self.connect()
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/http/client.py", line 1458, in connect
[!]     self.sock = self._context.wrap_socket(self.sock,
[!]                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 517, in wrap_socket
[!]     return self.sslsocket_class._create(
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1075, in _create
[!]     self.do_handshake()
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/ssl.py", line 1346, in do_handshake
[!]     self._sslobj.do_handshake()
[!] ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)
[!]
[!] During handling of the above exception, another exception occurred:
[!]
[!] Traceback (most recent call last):
[!]   File "/Users/ponymushama/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/install.py", line 23, in <module>
[!]     download_url("https://huggingface.co/Bingsu/adetailer/resolve/main/face_yolov8m.pt",
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 122, in download_url
[!]     url = _get_redirect_url(url, max_hops=max_redirect_hops)
[!]           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/torchvision/datasets/utils.py", line 66, in _get_redirect_url
[!]     with urllib.request.urlopen(urllib.request.Request(url, headers=headers)) as response:
[!]          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 216, in urlopen
[!]     return opener.open(url, data, timeout)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 519, in open
[!]     response = self._open(req, data)
[!]                ^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 536, in _open
[!]     result = self._call_chain(self.handle_open, protocol, protocol +
[!]              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 496, in _call_chain
[!]     result = func(*args)
[!]              ^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1391, in https_open
[!]     return self.do_open(http.client.HTTPSConnection, req,
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/urllib/request.py", line 1351, in do_open
[!]     raise URLError(err)
[!] urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1002)>
 ### ComfyUI-Impact-Pack: Check dependencies
 ### ComfyUI-Impact-Pack: Updating subpack
 [Impact Pack] EXECUTE: ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', 'install.py'] in '/Users/ponymushama/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
 req_path: /Users/ponymushama/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
 req_path: /Users/ponymushama/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
 req_path: /Users/ponymushama/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
 ### ComfyUI-Impact-Pack: Check basic models
Installation was successful.

## ComfyUI-Manager: EXECUTE => ['/Library/Frameworks/Python.framework/Versions/3.11/bin/python3', '-m', 'pip', 'install', 'ultralytics']
                                      After restarting ComfyUI, please refresh the browser.
```

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-Manager/issues/102#issuecomment-1806510017
