### ISSUE TITLE
Regional sampler stopped working after an update

### ISSUE THREAD

**Issue by mysticfall** [ltdrdata/ComfyUI-Impact-Pack#509]
With the latest ComfyUI(`03e6e81629b`) and Impack Pack(`47741a00677e`), I get the following error when I run a workflow with a regional sampler node:

```
ERROR:root:Traceback (most recent call last):
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/special_samplers.py", line 389, in doit
    new_latent_image = regional_prompt.sampler.sample_advanced(False, seed, adv_steps, new_latent_image, i, i + 1, True,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_sampling.py", line 184, in sample_advanced
    latent_image = separated_sample(model, add_noise, seed, steps, cfg, sampler_name, scheduler,
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_sampling.py", line 113, in separated_sample
    res = nodes_custom_sampler.SamplerCustom().sample(model, add_noise, seed, cfg, positive, negative, impact_sampler, sigmas, latent_image)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 271, in sample
    samples = comfy.sample.sample_custom(model, noise, cfg, sampler, sigmas, positive, negative, latent_image, noise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=noise_seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/sample.py", line 113, in sample_custom
    samples = comfy.samplers.sample(real_model, noise, positive_copy, negative_copy, cfg, model.load_device, sampler, sigmas, model_options=model.model_options, latent_image=latent_image, denoise_mask=noise_mask, callback=callback, disable_pbar=disable_pbar, seed=seed)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/mysticfall/workspace/ComfyUI/comfy/samplers.py", line 608, in sample
    samples = sampler.sample(model_wrap, sigmas, extra_args, callback, noise, latent_image, denoise_mask, disable_pbar)
              ^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'sample'
```

It looks like the argument order of some of the involved method was changed, so the CFG value was passed where it expects a sampler instance.

**Comment by ltdrdata** [comment]
I added constraints to pip to ensure that scipy is version 1.11.4 or higher.

**Comment by ltdrdata** [comment]
Let me check later.

**Comment by ltdrdata** [comment]
I have no problem. What workflow do you use?

**Comment by mysticfall** [comment]
Strange... I'll try to strip it down and share it here.

**Comment by ltdrdata** [comment]
I think some widget values seem to be incorrect.

**Comment by mysticfall** [comment]
@ltdrdata // I think you're right. I just deleted everything redundant to make a minimal reproducible case but now the error is gone.

The original workflow contained group nodes which included a sampler setup for each region. I exposed the CFG as an input so they could be shared across the groups.

The workflow worked fine the last time I checked it a month ago. But it looks like something about the widgets got mixed up afterwards.

At any rate, it's apparent that the problem is on my end. So I'll close this issue now.

Thanks for the help!

**Comment by mysticfall** [comment]
For anyone who may encounter a similar issue in future: Upon further testing, simply converting the CFG input on the group node to a widget value and back to an input resolved the problem.

Maybe the group node manages its inputs according to their original indexes. So, when the underlying node gets an additional widget parameter hence changing the index of the existing ones, it seems to get confused.
