### ISSUE TITLE
AttributeError: 'SAMWrapper' object has no attribute 'image_encoder'

### ISSUE THREAD

**Issue by mr-asa** [ltdrdata/ComfyUI-Impact-Pack#547]
2-3 days ago some changes were made and the connection with segment_anything repository stopped working.

![2024-04-08_19-31](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/15904951/f75edc19-7ba9-47a6-8fbc-0f4932f075d3)

Error
```shell
Loads SAM model: F:\ComfyUI\models\sams\sam_vit_b_01ec64.pth (device:AUTO)
final text_encoder_type: bert-base-uncased
!!! Exception during processing !!!
Traceback (most recent call last):
  File "F:\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI\custom_nodes\ComfyUI-0246\utils.py", line 381, in new_func
    res_value = old_func(*final_args, **kwargs)
  File "F:\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 325, in main
    (images, masks) = sam_segment(
  File "F:\ComfyUI\custom_nodes\comfyui_segment_anything\node.py", line 240, in sam_segment
    predictor = SamPredictorHQ(sam_model, sam_is_hq)
  File "F:\ComfyUI\custom_nodes\comfyui_segment_anything\sam_hq\predictor.py", line 22, in __init__
    super().__init__(sam_model=sam_model)
  File "f:\ComfyUI\venv\lib\site-packages\segment_anything\predictor.py", line 31, in __init__
    self.transform = ResizeLongestSide(sam_model.image_encoder.img_size)
AttributeError: 'SAMWrapper' object has no attribute 'image_encoder'
```

The author of that repository [refers to errors](https://github.com/storyicon/comfyui_segment_anything/issues/61) from this, but I can’t figure out what and how I should fix for it to work

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/45848d60-c995-4cc1-8db7-678b2473dbff)

You have to use `SAMModelLoader (segement anything)` instead of Impact Pack's SAMLoader.
They aren't compatible.

**Comment by mr-asa** [comment]
Thanks a lot! That's how it all works!
