### ISSUE TITLE
ComfyUI Impact Pack-IMPORT FAILED

### ISSUE THREAD

**Issue by awaxiaoyu** [ltdrdata/ComfyUI-Impact-Pack#551]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/125581307/f8763dca-0879-4279-8820-ee831431b1f8)
I have tried uninstalling reactor

**Comment by awaxiaoyu** [comment]
** ComfyUI startup time: 2024-04-14 15:18:06.292232
[2024-04-14 15:18] ** Platform: Windows
[2024-04-14 15:18] ** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
[2024-04-14 15:18] ** Python executable: G:\AI\Products\ComfyUI_windows_portable\python_embeded\python.exe
[2024-04-14 15:18] ** Log path: G:\AI\Products\ComfyUI_windows_portable\comfyui.log
[2024-04-14 15:18] 
#######################################################################
[2024-04-14 15:18] [ComfyUI-Manager] Starting dependency installation/(de)activation for the extension
[2024-04-14 15:18] 
[2024-04-14 15:18] 
## ComfyUI-Manager: CANCELED => ['G:\\AI\\Products\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'disable.py']
[2024-04-14 15:18] 
[ComfyUI-Manager] Startup script completed.
[2024-04-14 15:18] #######################################################################
[2024-04-14 15:18] 
[2024-04-14 15:18] 
Prestartup times for custom nodes:
[2024-04-14 15:18]    0.1 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-04-14 15:18] 
Total VRAM 12288 MB, total RAM 32578 MB
[2024-04-14 15:18] WARNING[XFORMERS]: xFormers can't load C++/CUDA extensions. xFormers was built for:
    PyTorch 2.0.1+cu118 with CUDA 1108 (you have 2.2.2+cu121)
    Python  3.10.11 (you have 3.11.8)
  Please reinstall xformers (see https://github.com/facebookresearch/xformers#installing-xformers)
  Memory-efficient attention, SwiGLU, sparse and more won't be available.
  Set XFORMERS_MORE_DETAILS=1 for more details
[2024-04-14 15:18] xformers version: 0.0.21
[2024-04-14 15:18] Set vram state to: NORMAL_VRAM
[2024-04-14 15:18] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-04-14 15:18] VAE dtype: torch.bfloat16
[2024-04-14 15:18] Using pytorch cross attention
[2024-04-14 15:18] ### Loading: ComfyUI-Impact-Pack (V4.87.5)
[2024-04-14 15:18] ### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
[2024-04-14 15:18] ### ComfyUI-Impact-Pack: Check dependencies
[2024-04-14 15:18] ### ComfyUI-Impact-Pack: Updating subpack
[2024-04-14 15:18] Traceback (most recent call last):
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\__init__.py", line 122, in <module>
    from ._shared import geometry
[2024-04-14 15:18] ImportError: cannot import name 'geometry' from 'skimage._shared' (G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\_shared\__init__.py)
[2024-04-14 15:18] 
During handling of the above exception, another exception occurred:

[2024-04-14 15:18] Traceback (most recent call last):
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 49, in <module>
    import impact.subpack_nodes  # This import must be done before cv2.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\impact\subpack_nodes.py", line 3, in <module>
    import impact.core as core
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 6, in <module>
    from skimage.measure import label
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\__init__.py", line 125, in <module>
    _raise_build_error(e)
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\__init__.py", line 102, in _raise_build_error
    raise ImportError(
[2024-04-14 15:18] ImportError: cannot import name 'geometry' from 'skimage._shared' (G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\_shared\__init__.py)
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 
[2024-04-14 15:18] 
During handling of the above exception, another exception occurred:

[2024-04-14 15:18] Traceback (most recent call last):
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 119, in ensure_subpack
    repo.remotes.origin.pull()
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\remote.py", line 1054, in pull
    res = self._get_fetch_info_from_stderr(proc, progress, kill_after_timeout=kill_after_timeout)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\remote.py", line 853, in _get_fetch_info_from_stderr
    proc.wait(stderr=stderr_text)
[2024-04-14 15:18]   File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\git\cmd.py", line 602, in wait
    raise GitCommandError(remove_password_if_present(self.args), status, errstr)
[2024-04-14 15:18] git.exc.GitCommandError: Cmd('git') failed due to: exit code(1)
  cmdline: git pull -v -- origin
  stderr: 'fatal: unable to access 'https://github.com/ltdrdata/ComfyUI-Impact-Subpack/': Failed to connect to github.com port 443 after 21096 ms: Couldn't connect to server'
[2024-04-14 15:18] [2024-04-14 15:18] [ComfyUI-Impact-Pack] Please turn off ComfyUI and remove 'G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack' and restart ComfyUI.
[2024-04-14 15:18] [Impact Pack] EXECUTE: ['G:\\AI\\Products\\ComfyUI_windows_portable\\python_embeded\\python.exe', 'install.py'] in 'G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
[2024-04-14 15:18] req_path: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
[2024-04-14 15:18] req_path: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
[2024-04-14 15:18] req_path: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
[2024-04-14 15:18] [Impact Pack] EXECUTE: ['G:\\AI\\Products\\ComfyUI_windows_portable\\python_embeded\\python.exe', '-s', '-m', 'pip', 'install', '-r', 'G:\\AI\\Products\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\requirements.txt'] in 'None'
[2024-04-14 15:18] ### ComfyUI-Impact-Pack: Check basic models
Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\__init__.py", line 122, in <module>
    from ._shared import geometry
ImportError: cannot import name 'geometry' from 'skimage._shared' (G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\_shared\__init__.py)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 72, in <module>
    import impact.impact_server  # to load server api
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 13, in <module>
    import impact.core as core
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 6, in <module>
    from skimage.measure import label
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\__init__.py", line 125, in <module>
    _raise_build_error(e)
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\__init__.py", line 102, in _raise_build_error
    raise ImportError(
ImportError: cannot import name 'geometry' from 'skimage._shared' (G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\_shared\__init__.py)
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 

[2024-04-14 15:18] Cannot import G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: cannot import name 'geometry' from 'skimage._shared' (G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\skimage\_shared\__init__.py)
It seems that scikit-image has not been built correctly.

Your install of scikit-image appears to be broken.
Try re-installing the package following the instructions at:
https://scikit-image.org/docs/stable/install.html 
[2024-04-14 15:18] Package diffusers is already installed.
[2024-04-14 15:18] G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\utils\outputs.py:63: UserWarning: torch.utils._pytree._register_pytree_node is deprecated. Please use torch.utils._pytree.register_pytree_node instead.
  torch.utils._pytree._register_pytree_node(
[2024-04-14 15:18] Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Malefish-Custom-Scripts\__init__.py", line 2, in <module>
    from .py.io.csv_prompts_loader import *
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Malefish-Custom-Scripts\py\io\csv_prompts_loader.py", line 4, in <module>
    import pandas as pd
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pandas\__init__.py", line 59, in <module>
    from pandas.core.api import (
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pandas\core\api.py", line 1, in <module>
    from pandas._libs import (
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\pandas\_libs\__init__.py", line 16, in <module>
    import pandas._libs.pandas_parser  # noqa: E501 # isort: skip # type: ignore[reportUnusedImport]
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pandas._libs.pandas_parser'

[2024-04-14 15:18] Cannot import G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Malefish-Custom-Scripts module for custom nodes: No module named 'pandas._libs.pandas_parser'
[2024-04-14 15:18] ### Loading: ComfyUI-Manager (V2.17)
[2024-04-14 15:18] ### ComfyUI Revision: 2127 [744ac944] | Released on '2024-04-13'
[2024-04-14 15:18] G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\_distutils_hack\__init__.py:26: UserWarning: Setuptools is replacing distutils.
  warnings.warn("Setuptools is replacing distutils.")
[2024-04-14 15:18] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-04-14 15:18] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-04-14 15:18] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-04-14 15:18] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-04-14 15:18] WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
[2024-04-14 15:18] [34mComfyroll Studio: [92mFailed to load Graphics nodes[0m
[2024-04-14 15:18] WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
[2024-04-14 15:18] [34mComfyroll Studio: [92mFailed to load Utility nodes[0m
[2024-04-14 15:18] WARNING: Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\__init__.py", line 21, in <module>
    from .node_mappings import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes\node_mappings.py", line 132, in <module>
    "CR Halftone Grid": CR_HalftoneGrid,
                    ^^^^^^^^^^^^^^^
NameError: name 'CR_HalftoneGrid' is not defined

[2024-04-14 15:18] WARNING: Cannot import G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes module for custom nodes: name 'CR_HalftoneGrid' is not defined
[2024-04-14 15:18] [36;20m[comfyui_controlnet_aux] | INFO -> Using ckpts path: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts[0m
[2024-04-14 15:18] [36;20m[comfyui_controlnet_aux] | INFO -> Using symlinks: False[0m
[2024-04-14 15:18] [36;20m[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider'][0m
[2024-04-14 15:18] 

Full error log from comfyui_controlnet_aux: 
Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\__init__.py", line 32, in load_nodes
    module = importlib.import_module(
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "<frozen importlib._bootstrap>", line 1204, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1176, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\node_wrappers\dwpose.py", line 5, in <module>
    from controlnet_aux.dwpose import DwposeDetector, AnimalposeDetector
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\__init__.py", line 15, in <module>
    from . import util
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\dwpose\util.py", line 3, in <module>
    import matplotlib
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    from . import _api, _version, cbook, _docstring, rcsetup
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\cbook.py", line 32, in <module>
    from matplotlib import _api, _c_internal_utils
ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\__init__.py)


[2024-04-14 15:18] 
[2024-04-14 15:18] [36;20m[comfyui_controlnet_aux] | INFO -> Some nodes failed to load:
	Failed to import module dwpose because ImportError: cannot import name '_c_internal_utils' from partially initialized module 'matplotlib' (most likely due to a circular import) (G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\matplotlib\__init__.py)

Check that you properly installed the dependencies.
If you think this is a bug, please report it on the github page (https://github.com/Fannovel16/comfyui_controlnet_aux/issues)[0m
[2024-04-14 15:18] WARNING: Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\__init__.py", line 57, in <module>
    from .ScheduledNodes import (
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes\ScheduledNodes.py", line 4, in <module>
    import numexpr
  File "G:\AI\Products\ComfyUI_windows_portable\python_embeded\Lib\site-packages\numexpr\__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__
ModuleNotFoundError: No module named 'numexpr.interpreter'

[2024-04-14 15:18] WARNING: Cannot import G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes module for custom nodes: No module named 'numexpr.interpreter'
[2024-04-14 15:18] WARNING: Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\__init__.py", line 1, in <module>
    from .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui\py\smZ_cfg_denoiser.py", line 7, in <module>
    from comfy.samplers import KSampler, CompVisVDenoiser, KSamplerX0Inpaint
ImportError: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (G:\AI\Products\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)

[2024-04-14 15:18] WARNING: Cannot import G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui module for custom nodes: cannot import name 'CompVisVDenoiser' from 'comfy.samplers' (G:\AI\Products\ComfyUI_windows_portable\ComfyUI\comfy\samplers.py)
[2024-04-14 15:18] WARNING: Traceback (most recent call last):
  File "G:\AI\Products\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 936, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1073, in get_code
  File "<frozen importlib._bootstrap_external>", line 1130, in get_data
FileNotFoundError: [Errno 2] No such file or directory: 'G:\\AI\\Products\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\lora-prompt-tool\\__init__.py'

[2024-04-14 15:18] WARNING: Cannot import G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\lora-prompt-tool module for custom nodes: [Errno 2] No such file or directory: 'G:\\AI\\Products\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\lora-prompt-tool\\__init__.py'
[2024-04-14 15:18] 
Import times for custom nodes:
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\AIGODLIKE-COMFYUI-TRANSLATION
[2024-04-14 15:18]    0.0 seconds (IMPORT FAILED): G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\lora-prompt-tool
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
[2024-04-14 15:18]    0.0 seconds (IMPORT FAILED): G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FizzNodes
[2024-04-14 15:18]    0.0 seconds (IMPORT FAILED): G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
[2024-04-14 15:18]    0.0 seconds (IMPORT FAILED): G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Malefish-Custom-Scripts
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2024-04-14 15:18]    0.0 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
[2024-04-14 15:18]    0.2 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-LCM
[2024-04-14 15:18]    0.3 seconds: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-04-14 15:18]    3.8 seconds (IMPORT FAILED): G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
[2024-04-14 15:18]   25.8 seconds (IMPORT FAILED): G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[2024-04-14 15:18] 
[2024-04-14 15:18] Starting server

[2024-04-14 15:18] To see the GUI go to: http://127.0.0.1:8188
[2024-04-14 15:18] FETCH DATA from: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
[2024-04-14 15:18] FETCH DATA from: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1514988643_custom-node-list.json
[2024-04-14 15:18] FETCH DATA from: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json
[2024-04-14 15:18] FETCH DATA from: G:\AI\Products\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\.cache\1742899825_extension-node-map.json

**Comment by ltdrdata** [comment]
Try update `scikit-image` through `Install pip packages`

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/ce896526-e831-4dcc-bb9d-b2b2425167bb)

**Comment by Dimaray** [comment]
Im getting a similar error...

[2024-06-15 09:37] ### Loading: ComfyUI-Impact-Pack (V5.12.2)
[2024-06-15 09:37] ### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
[2024-06-15 09:37] ### ComfyUI-Impact-Pack: Check dependencies
[2024-06-15 09:37] ### ComfyUI-Impact-Pack: Updating subpack
[2024-06-15 09:37] [Impact Pack] EXECUTE: ['A:\\#AI\\python_embeded\\python.exe', 'install.py'] in 'A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
[2024-06-15 09:37] req_path: A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
[2024-06-15 09:37] req_path: A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
[2024-06-15 09:37] req_path: A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
[2024-06-15 09:37] ### ComfyUI-Impact-Pack: Check basic models
[2024-06-15 09:37] Traceback (most recent call last):
  File "A:\#AI\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 72, in <module>
    import impact.impact_server  # to load server api
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 12, in <module>
    import impact.core as core
  File "A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 9, in <module>
    from comfy_extras.nodes_custom_sampler import Noise_RandomNoise
ImportError: cannot import name 'Noise_RandomNoise' from 'comfy_extras.nodes_custom_sampler' (A:\#AI\ComfyUI\comfy_extras\nodes_custom_sampler.py)
[2024-06-15 09:37] 
[2024-06-15 09:37] Cannot import A:\#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: cannot import name 'Noise_RandomNoise' from 'comfy_extras.nodes_custom_sampler' (A:\#AI\ComfyUI\comfy_extras\nodes_custom_sampler.py)
 
this is what i found in the log

**Comment by ltdrdata** [comment]
> Im getting a similar error...
> 
> [2024-06-15 09:37] ### Loading: ComfyUI-Impact-Pack (V5.12.2) [2024-06-15 09:37] ### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.) [2024-06-15 09:37] ### ComfyUI-Impact-Pack: Check dependencies [2024-06-15 09:37] ### ComfyUI-Impact-Pack: Updating subpack [2024-06-15 09:37] [Impact Pack] EXECUTE: ['A:\#AI\python_embeded\python.exe', 'install.py'] in 'A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack' [2024-06-15 09:37] req_path: A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt [2024-06-15 09:37] req_path: A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt [2024-06-15 09:37] req_path: A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt [2024-06-15 09:37] ### ComfyUI-Impact-Pack: Check basic models [2024-06-15 09:37] Traceback (most recent call last): File "A:#AI\ComfyUI\nodes.py", line 1887, in load_custom_node module_spec.loader.exec_module(module) File "", line 940, in exec_module File "", line 241, in _call_with_frames_removed File "A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack__init__.py", line 72, in import impact.impact_server # to load server api ^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 12, in import impact.core as core File "A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 9, in from comfy_extras.nodes_custom_sampler import Noise_RandomNoise ImportError: cannot import name 'Noise_RandomNoise' from 'comfy_extras.nodes_custom_sampler' (A:#AI\ComfyUI\comfy_extras\nodes_custom_sampler.py) [2024-06-15 09:37] [2024-06-15 09:37] Cannot import A:#AI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: cannot import name 'Noise_RandomNoise' from 'comfy_extras.nodes_custom_sampler' (A:#AI\ComfyUI\comfy_extras\nodes_custom_sampler.py)
> 
> this is what i found in the log

You have to update ComfyUI.

**Comment by Dimaray** [comment]
Already did thats what caused my error in the first place

**Comment by ltdrdata** [comment]
> Already did thats what caused my error in the first place

That means your updating is failing due to modfiied file, symbolic link and so on.
You have to check and update manually.,

![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/0f6b4cde-d01e-409c-bd02-d31ea10cf2c0)
