### ISSUE TITLE
[AttributeError: 'NoneType' object has no attribute 'headers'] when click 'Open in SAM Detector' menu.

### ISSUE THREAD

**Issue by 925-Studio** [ltdrdata/ComfyUI-Impact-Pack#554]
I'm facing a kind strange problem here. I always got the below error messages when try to use 'Open in SAM Detector' menu. It only appears once until I load another picture in the 'Load Image' node. But it seems still can process the function without errors. I've searched a lot but got no luck. Can anyone tell me what did go wrong? Thanks in advance.

```
Import times for custom nodes:
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/websocket_image_save.py
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/rgthree-comfy
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI_essentials
   0.0 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI_InstantID
   0.1 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI-Manager
   0.1 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/comfyui-reactor-node
   0.6 seconds: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://0.0.0.0:2001
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: /home/silver/Playgrounds/AI/sd-comfyui/custom_nodes/ComfyUI-Manager/extension-node-map.json
[INFO] ComfyUI-Impact-Pack: Loading SAM model '/home/silver/Playgrounds/AI/sd-comfyui/models'
[INFO] ComfyUI-Impact-Pack: SAM model loaded. 
Error handling request
Traceback (most recent call last):
  File "/home/silver/.local/lib/python3.10/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
  File "/home/silver/.local/lib/python3.10/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
  File "/home/silver/.local/lib/python3.10/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
  File "/home/silver/Playgrounds/AI/sd-comfyui/server.py", line 41, in cache_control
    response: web.Response = await handler(request)
  File "/home/silver/Playgrounds/AI/sd-comfyui/server.py", line 55, in cors_middleware
    response.headers['Access-Control-Allow-Origin'] = allowed_origin
AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by ltdrdata** [comment]
That seems your network configuration issue.

Try launch ComfyUI with `--enable-cors-header` option.

**Comment by 925-Studio** [comment]
> That seems your network configuration issue.
> 
> Try launch ComfyUI with `--enable-cors-header` option.

Thanks for the tip but unfortunately it doesn't help. I kind figured the network causes this problem but not your code. Anyway I will close this issue and thanks again.

**Comment by ltdrdata** [comment]
I found what was the issue. And this is fixed.

**Comment by 925-Studio** [comment]
> I found what was the issue. And this is fixed.

So great to hear this and I've already checked, the error is gone. Thanks for you work!
