### ISSUE TITLE
Error when selecting Open in SAM Detector

### ISSUE THREAD

**Issue by derpmagician** [ltdrdata/ComfyUI-Impact-Pack#557]
the error message appear, but the window for masking the image still works, i have the last version of Impact Pack

```
[INFO] ComfyUI-Impact-Pack: Loading SAM model 'E:\ComfyUI_windows_portable\ComfyUI\models'
[INFO] ComfyUI-Impact-Pack: SAM model loaded.
Error handling request
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\aiohttp\web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 41, in cache_control
    response: web.Response = await handler(request)
                             ^^^^^^^^^^^^^^^^^^^^^^
  File "E:\ComfyUI_windows_portable\ComfyUI\server.py", line 55, in cors_middleware
    response.headers['Access-Control-Allow-Origin'] = allowed_origin
    ^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'headers'
```

**Comment by ltdrdata** [comment]
This is fixed.
