### ISSUE TITLE
 module 'comfy.samplers' has no attribute 'CFGGuider'

### ISSUE THREAD

**Issue by ohcaidek** [ltdrdata/ComfyUI-Impact-Pack#560]
I tried install through git clone, on Manager, nothing work. I have no code skill and cant find anything about this CFGGuide on google, seem like it break another nodes too. I use Colab to run Comfyui

Total VRAM 15102 MB, total RAM 52218 MB
xformers version: 0.0.22.post7
Set vram state to: NORMAL_VRAM
Device: cuda:0 Tesla T4 : cudaMallocAsync
VAE dtype: torch.float32
Using xformers cross attention
Adding extra search path checkpoints /content/drive/MyDrive/SD/model
Adding extra search path configs /content/drive/MyDrive/sd/models/Stable-diffusion
Adding extra search path vae /content/drive/MyDrive/sd/stable-diffusion-webui/models/VAE
Adding extra search path loras /content/drive/MyDrive/sd/stable-diffusion-webui/models/Lora
Adding extra search path loras /content/drive/MyDrive/sd/models/LyCORIS
Adding extra search path upscale_models /content/drive/MyDrive/sd/models/ESRGAN
Adding extra search path upscale_models /content/drive/MyDrive/sd/models/RealESRGAN
Adding extra search path upscale_models /content/drive/MyDrive/sd/models/SwinIR
Adding extra search path embeddings /content/drive/MyDrive/sd/embeddings
Adding extra search path hypernetworks /content/drive/MyDrive/sd/models/hypernetworks
Adding extra search path controlnet /content/drive/MyDrive/sd/models/ControlNet
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 386, in <module>
    class Guider_Basic(comfy.samplers.CFGGuider):
AttributeError: module 'comfy.samplers' has no attribute 'CFGGuider'

Cannot import /content/drive/MyDrive/ComfyUI/comfy_extras/nodes_custom_sampler.py module for custom nodes: module 'comfy.samplers' has no attribute 'CFGGuider'
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_perpneg.py", line 54, in <module>
    class Guider_PerpNeg(comfy.samplers.CFGGuider):
AttributeError: module 'comfy.samplers' has no attribute 'CFGGuider'

Cannot import /content/drive/MyDrive/ComfyUI/comfy_extras/nodes_perpneg.py module for custom nodes: module 'comfy.samplers' has no attribute 'CFGGuider'
### ComfyUI Revision: 2141 [d09b5ef4] | Released on '2024-04-22'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
[Crystools INFO] Crystools version: 1.12.0
[Crystools INFO] CPU: Intel(R) Xeon(R) CPU @ 2.00GHz - Arch: x86_64 - OS: Linux 6.1.58+
[Crystools INFO] GPU/s:
[Crystools INFO] 0) Tesla T4
[Crystools INFO] NVIDIA Driver: 535.104.05
Searge-SDXL v4.3.1 in /content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL
### Loading: ComfyUI-Inspire-Pack (V0.69.3)
Use STYLE:weight_interpretation:normalization at the start of a prompt to use advanced encodings
Weight interpretations available: comfy,perp
Normalization types available: none
WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `/content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui/was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 211 nodes successfully.

	"Opportunities don't happen. You create them." - Chris Grosser

2024-04-24 12:48:39.707335: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-04-24 12:48:39.707388: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-04-24 12:48:39.708921: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-04-24 12:48:40.875579: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
NumExpr defaulting to 8 threads.
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/cgem156-ComfyUI/__init__.py", line 33, in <module>
    module = importlib.import_module(f"custom_nodes.cgem156-ComfyUI.scripts.{script}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/cgem156-ComfyUI/__init__.py", line 33, in <module>
    module = importlib.import_module(f"custom_nodes.cgem156-ComfyUI.scripts.{script}")
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/cgem156-ComfyUI/scripts/lora_xy/__init__.py", line 1, in <module>
    from .node import LoraLoaderModelOnlyXY, SamplerCustomXY, KSamplerXY, KSamplerAdvancedXY, PreviewXY
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/cgem156-ComfyUI/scripts/lora_xy/node.py", line 2, in <module>
    from comfy_extras.nodes_custom_sampler import SamplerCustom
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 386, in <module>
    class Guider_Basic(comfy.samplers.CFGGuider):
AttributeError: module 'comfy.samplers' has no attribute 'CFGGuider'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/cgem156-ComfyUI module for custom nodes: module 'comfy.samplers' has no attribute 'CFGGuider'
[ReActor] - STATUS - Running v0.4.2-b2 in ComfyUI
Torch version: 2.1.0+cu121

[rgthree] Loaded 37 extraordinary nodes.

Workspace manager - Openning file hash dict
### Loading: Workspace Manager (V1.0.0)
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui/__init__.py", line 9, in <module>
    from  .efficiency_nodes import NODE_CLASS_MAPPINGS
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui/efficiency_nodes.py", line 46, in <module>
    from .py import smZ_cfg_denoiser
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui/py/smZ_cfg_denoiser.py", line 11, in <module>
    from comfy_extras import nodes_custom_sampler
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 386, in <module>
    class Guider_Basic(comfy.samplers.CFGGuider):
AttributeError: module 'comfy.samplers' has no attribute 'CFGGuider'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui module for custom nodes: module 'comfy.samplers' has no attribute 'CFGGuider'
Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Easy-Use/__init__.py", line 19, in <module>
    imported_module = importlib.import_module(".py.{}".format(module_name), __name__)
  File "/usr/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Easy-Use/py/easyNodes.py", line 3222, in <module>
    from comfy_extras.nodes_custom_sampler import BasicGuider, DualCFGGuider, CFGGuider, KSamplerSelect, DisableNoise, RandomNoise, BasicScheduler, KarrasScheduler, ExponentialScheduler, PolyexponentialScheduler, SDTurboScheduler, VPScheduler, FlipSigmas
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 386, in <module>
    class Guider_Basic(comfy.samplers.CFGGuider):
AttributeError: module 'comfy.samplers' has no attribute 'CFGGuider'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Easy-Use module for custom nodes: module 'comfy.samplers' has no attribute 'CFGGuider'
[comfyui_controlnet_aux] | INFO -> Using ckpts path: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux/ckpts
[comfyui_controlnet_aux] | INFO -> Using symlinks: False
[comfyui_controlnet_aux] | INFO -> Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider', 'CoreMLExecutionProvider']
DWPose: Onnxruntime with acceleration providers detected
[comfy_mtb] | INFO -> loaded 68 nodes successfuly
[comfy_mtb] | INFO -> Some nodes (2) could not be loaded. This can be ignored, but go to http://127.0.0.1:8188/mtb if you want more information.
module 'comfy.samplers' has no attribute 'CFGGuider'
Loaded ControlNetPreprocessors nodes from /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux
Could not find AdvancedControlNet nodes
Could not find AnimateDiff nodes
Loaded IPAdapter nodes from /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
Could not find VideoHelperSuite nodes
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['/usr/bin/python3', 'install.py'] in '/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack'
req_path: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/requirements.txt
req_path: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/requirements.txt
### ComfyUI-Impact-Pack: Check basic models

ComfyUI finished loading, trying to launch cloudflared (if it gets stuck here cloudflared is having issues)

Traceback (most recent call last):
  File "/content/drive/MyDrive/ComfyUI/nodes.py", line 1864, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/__init__.py", line 72, in <module>
    import impact.impact_server  # to load server api
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_server.py", line 12, in <module>
    import impact.core as core
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/core.py", line 18, in <module>
    from impact import impact_sampling
  File "/content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_sampling.py", line 4, in <module>
    from comfy_extras import nodes_custom_sampler
  File "/content/drive/MyDrive/ComfyUI/comfy_extras/nodes_custom_sampler.py", line 386, in <module>
    class Guider_Basic(comfy.samplers.CFGGuider):
AttributeError: module 'comfy.samplers' has no attribute 'CFGGuider'

Cannot import /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack module for custom nodes: module 'comfy.samplers' has no attribute 'CFGGuider'

Import times for custom nodes:
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/websocket_image_save.py
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-portrait-master-zh-cn
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sdxl-recommended-res-calc
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sdxl_prompt_styler
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ControlNet-LLLite-ComfyUI
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Eagle-PNGInfo
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/image-resize-comfyui
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/lora-info
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/sd-dynamic-thresholding
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-ComfyRun
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_IPAdapter_plus
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Image-Saver
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-PhotoMaker-ZHO
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_essentials
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-layerdiffuse
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-portrait-master
   0.0 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/efficiency-nodes-comfyui
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_UltimateSDUpscale
   0.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-workspace-manager
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/Derfuu_ComfyUI_ModdedNodes
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/OneButtonPrompt
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/rgthree-comfy
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Custom-Scripts
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-KJNodes
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-prompt-control
   0.1 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Inspire-Pack
   0.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_segment_anything
   0.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui_controlnet_aux
   0.2 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Easy-Use
   0.2 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Manager
   0.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-reactor-node
   0.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI_Comfyroll_CustomNodes
   0.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfyui-art-venture
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/comfy_mtb
   0.6 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/SeargeSDXL
   0.8 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-InstantID
   1.5 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-SUPIR
   2.0 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/was-node-suite-comfyui
   2.4 seconds: /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Crystools
   3.0 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/cgem156-ComfyUI
   5.6 seconds (IMPORT FAILED): /content/drive/MyDrive/ComfyUI/custom_nodes/ComfyUI-Impact-Pack

WARNING: some comfy_extras/ nodes did not import correctly. This may be because they are missing some dependencies.

IMPORT FAILED: nodes_custom_sampler.py
IMPORT FAILED: nodes_perpneg.py

This issue might be caused by new missing dependencies added the last time you updated ComfyUI.
Please do a: pip install -r requirements.txt

**Comment by ltdrdata** [comment]
The ComfyUI you installed is in a state where multiple versions of the files are mixed up.
Make sure up to date.
