### ISSUE TITLE
MacOS encountered an error：Error occurred when executing FaceDetailer:  py-cpuinfo currently only works on X86 and some PPC and ARM CPUs. 

### ISSUE THREAD

**Issue by Lynds-007** [ltdrdata/ComfyUI-Impact-Pack#561]
Error occurred when executing FaceDetailer:  py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.

**Comment by Lynds-007** [comment]
Please help me,

**Comment by ltdrdata** [comment]
Is the basic workflow functioning without any issues?

**Comment by Utoko** [comment]
yes have the same error. like 2 month ago I used the Facedetailer, now it throws the error. Basic workflow works. M2 macos

**Comment by ltdrdata** [comment]
What is the stack trace?

**Comment by Utoko** [comment]
`Error occurred when executing FaceDetailer:

py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.

File "/Users/hildakuehnle/ComfyUI/execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/ComfyUI/execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/ComfyUI/execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 553, in doit
enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 487, in enhance_face
segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 127, in detect
detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 33, in inference_bbox
pred = model(image, conf=confidence, device=device)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/model.py", line 177, in __call__
return self.predict(source, stream, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/model.py", line 453, in predict
return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 168, in __call__
return list(self.stream_inference(source, model, *args, **kwargs)) # merge list of Result into one
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context
response = gen.send(None)
^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 216, in stream_inference
self.setup_model(model)
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 299, in setup_model
device=select_device(self.args.device, verbose=verbose),
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/utils/torch_utils.py", line 164, in select_device
s += f"CPU ({get_cpu_info()})\n"
^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/utils/torch_utils.py", line 70, in get_cpu_info
import cpuinfo # pip install py-cpuinfo
^^^^^^^^^^^^^^
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/cpuinfo/__init__.py", line 7, in
from cpuinfo.cpuinfo import *
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/cpuinfo/cpuinfo.py", line 1842, in
_check_arch()
File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/cpuinfo/cpuinfo.py", line 1798, in _check_arch
raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")`

the full error message

**Comment by ltdrdata** [comment]
Hmm... that's strange. Other Mac users have been using it without issues. It might be a version issue with ultralytics. Try updating to the latest version or downgrading.

Also, try setting up the environment using venv instead of conda.

**Comment by duguyixiaono1** [comment]
> `Error occurred when executing FaceDetailer:
> 
> py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
> 
> File "/Users/hildakuehnle/ComfyUI/execution.py", line 151, in recursive_execute output_data, output_ui = get_output_data(obj, input_data_all) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/ComfyUI/execution.py", line 81, in get_output_data return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/ComfyUI/execution.py", line 74, in map_node_over_list results.append(getattr(obj, func)(**slice_dict(input_data_all, i))) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 553, in doit enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face( ^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 487, in enhance_face segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 127, in detect detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 33, in inference_bbox pred = model(image, conf=confidence, device=device) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/model.py", line 177, in **call** return self.predict(source, stream, **kwargs) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/model.py", line 453, in predict return self.predictor.predict_cli(source=source) if is_cli else self.predictor(source=source, stream=stream) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 168, in **call** return list(self.stream_inference(source, model, *args, **kwargs)) # merge list of Result into one ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 35, in generator_context response = gen.send(None) ^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 216, in stream_inference self.setup_model(model) File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/engine/predictor.py", line 299, in setup_model device=select_device(self.args.device, verbose=verbose), ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/utils/torch_utils.py", line 164, in select_device s += f"CPU ({get_cpu_info()})\n" ^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/ultralytics/utils/torch_utils.py", line 70, in get_cpu_info import cpuinfo # pip install py-cpuinfo ^^^^^^^^^^^^^^ File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/cpuinfo/**init**.py", line 7, in from cpuinfo.cpuinfo import * File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/cpuinfo/cpuinfo.py", line 1842, in _check_arch() File "/Users/hildakuehnle/anaconda3/envs/comfyI/lib/python3.11/site-packages/cpuinfo/cpuinfo.py", line 1798, in _check_arch raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")`
> 
> the full error message

Same error occurred.

`>>> import platform
>>> print(platform.machine())
arm64`

**Comment by duguyixiaono1** [comment]
> Hmm... that's strange. Other Mac users have been using it without issues. It might be a version issue with ultralytics. Try updating to the latest version or downgrading.
> 
> Also, try setting up the environment using venv instead of conda.

it does not work. 
what can i do?

`
!!! Exception during processing!!! py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
Traceback (most recent call last):
  File "/Users/jamson/code_opensource/ComfyUI/execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/detectors.py", line 243, in doit
    return SimpleDetectorForEach.detect(bbox_detector, image, bbox_threshold, bbox_dilation, crop_factor, drop_size,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/detectors.py", line 224, in detect
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, crop_factor, drop_size, detailer_hook=detailer_hook)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 127, in detect
    detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/code_opensource/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 33, in inference_bbox
    pred = model(image, conf=confidence, device=device)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 173, in __call__
    return self.predict(source, stream, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/engine/model.py", line 556, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/engine/predictor.py", line 305, in setup_model
    device=select_device(self.args.device, verbose=verbose),
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/torch_utils.py", line 204, in select_device
    s += f"CPU ({get_cpu_info()})\n"
                 ^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/ultralytics/utils/torch_utils.py", line 104, in get_cpu_info
    import cpuinfo  # pip install py-cpuinfo
    ^^^^^^^^^^^^^^
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/__init__.py", line 7, in <module>
    from cpuinfo.cpuinfo import *
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1842, in <module>
    _check_arch()
  File "/Users/jamson/miniconda3/lib/python3.12/site-packages/cpuinfo/cpuinfo.py", line 1798, in _check_arch
    raise Exception("py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.")
Exception: py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.
`

**Comment by krummrey** [comment]
Ran into the same issue. M1 32GB. 
`py-cpuinfo currently only works on X86 and some PPC and ARM CPUs.`
Any way to fix that? 
Seems to be a fairly trivial check, maybe a default "work on CPU" if it fails?
