### ISSUE TITLE
The configuration model is not working

### ISSUE THREAD

**Issue by cgzs00** [ltdrdata/ComfyUI-Impact-Pack#570]
This is the configuration file information：
[default]
dependency_version = 20
mmdet_skip = True
sam_editor_cpu = False
sam_editor_model = sam_vit_h_4b8939.pth
custom_wildcards = C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\custom_wildcards
disable_gpu_opencv = True

This is comfyui error message：
FETCH DATA from: C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
#read_workflow_json_files_all C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
FETCH DATA from: C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json
#read_workflow_json_files_all C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\app\
[INFO] ComfyUI-Impact-Pack: Loading SAM model 'C:\Program Files\ComfyUI_windows_portable\ComfyUI\models'
[INFO] ComfyUI-Impact-Pack: SAM model loaded.
Exception in thread Thread-14 (async_prepare_sam):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "C:\Program Files\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 77, in async_prepare_sam
    sam_model = sam_model_registry[model_kind](checkpoint=model_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\segment_anything\build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
           ^^^^^^^^^^^
  File "C:\Program Files\ComfyUI_windows_portable\python_embeded\Lib\site-packages\segment_anything\build_sam.py", line 104, in _build_sam
    with open(checkpoint, "rb") as f:
         ^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Program Files\\ComfyUI_windows_portable\\ComfyUI\\models\\sams\\sam_vit_b_01ec64.pth'

The changed model information is not recognized and the default configuration information cannot be changed.

**Comment by ltdrdata** [comment]
This is fixed.
