### ISSUE TITLE
cannot import name 'Noise_EmptyNoise' from 'comfy_extras.nodes_custom_sampler'

### ISSUE THREAD

**Issue by Geeknasty** [ltdrdata/ComfyUI-Impact-Pack#572]
I'm probably missing something simple here, but for some reason I just can't get this to install.

It mentions (several dependencies are missing) but it seems to be running the install script and installing the pip packages.

Can anyone explain what I'm doing wrong?

```
[ComfyUI-Manager] Starting dependency installation/(de)activation for the extension

Install: pip packages for 'D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
   Install: install script for 'D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
 ### ComfyUI-Impact-Pack: Check dependencies
 ### ComfyUI-Impact-Pack: Updating subpack
 [Impact Pack] EXECUTE: ['D:\\SD-ComfyUI\\python_embeded\\python.exe', 'install.py'] in 'D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
 req_path: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
 req_path: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
 ### ComfyUI-Impact-Pack: Check basic models

[ComfyUI-Manager] Startup script completed.
```

```
### Loading: ComfyUI-Impact-Pack (V4.90.1)
### ComfyUI-Impact-Pack: Reinstall dependencies (several dependencies are missing.)
### ComfyUI-Impact-Pack: Check dependencies
### ComfyUI-Impact-Pack: Updating subpack
[Impact Pack] EXECUTE: ['D:\\SD-ComfyUI\\python_embeded\\python.exe', 'install.py'] in 'D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack'
req_path: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_subpack\requirements.txt
req_path: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\requirements.txt
### ComfyUI-Impact-Pack: Check basic models
Traceback (most recent call last):
  File "D:\SD-ComfyUI\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 72, in <module>
    import impact.impact_server  # to load server api
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 12, in <module>
    import impact.core as core
  File "D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 24, in <module>
    from impact import impact_sampling
  File "D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 104, in <module>
    from comfy_extras.nodes_custom_sampler import Noise_EmptyNoise, Noise_RandomNoise
ImportError: cannot import name 'Noise_EmptyNoise' from 'comfy_extras.nodes_custom_sampler' (D:\SD-ComfyUI\ComfyUI\comfy_extras\nodes_custom_sampler.py)

Cannot import D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: cannot import name 'Noise_EmptyNoise' from 'comfy_extras.nodes_custom_sampler' (D:\SD-ComfyUI\ComfyUI\comfy_extras\nodes_custom_sampler.py)
```

```
Import times for custom nodes:
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\SDXLAspectRatio.py
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\ControlNet-LLLite-ComfyUI
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\masquerade-nodes-comfyui
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\lora-info
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyMath
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Image-Saver
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\failfast-comfyui-extensions
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.1 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\comfy_mtb
   0.2 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.4 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\comfyui_segment_anything
   0.7 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI_tinyterraNodes
   1.3 seconds: D:\SD-ComfyUI\ComfyUI\custom_nodes\was-node-suite-comfyui
   4.0 seconds (IMPORT FAILED): D:\SD-ComfyUI\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
```
[comfyui.log](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/15139119/comfyui.log)
[pip list.txt](https://github.com/ltdrdata/ComfyUI-Impact-Pack/files/15139179/pip.list.txt)

**Comment by Geeknasty** [comment]
I figured it out. Sorry for opening this issue. It was my fault. I wasn't using the latest ComfyUI. There was a [commit ](<https://github.com/comfyanonymous/ComfyUI/commit/0542088ef895b4825df80fd3babf91513441af65>) 3 weeks ago that added Noise_EmptyNoise to comfy/sampler_helpers.py 

Somehow, my ComfyUI didn't update. I've got it all working now.
