### ISSUE TITLE
update and break

### ISSUE THREAD

**Issue by tester4488** [ltdrdata/ComfyUI-Impact-Pack#576]
```
Detailer: segment upscale for ((617.98413, 782.10547)) | crop region (869, 1024) x 1.000453118567352 -> (869, 1024)
!!! Exception during processing!!! module 'comfy.k_diffusion.sampling' has no attribute 'sample_ddim'
Traceback (most recent call last):
  File "E:\SD\ComfyUI_port_2\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1445, in doit
    DetailerForEach.do_detail(image, segs, model, clip, vae, guide_size, guide_size_for, max_size, seed, steps,
  File "E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 287, in do_detail
    enhanced_image, cnet_pils = core.enhance_detail(cropped_image, model, clip, vae, guide_size, guide_size_for_bbox, max_size,
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 275, in enhance_detail
    refined_latent = impact_sampling.ksampler_wrapper(model2, seed2, steps2, cfg2, sampler_name2, scheduler2, positive2, negative2,
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 202, in ksampler_wrapper
    refined_latent = separated_sample(model, True, seed, advanced_steps, cfg, sampler_name, scheduler, positive, negative, latent_image, start_at_step, end_at_step, False, sigma_ratio=sigma_factor)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 169, in separated_sample
    impact_sampler = ksampler(sampler_name, total_sigmas)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_sampling.py", line 103, in ksampler
    return samplers.ksampler(sampler_name, extra_options, inpaint_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "E:\SD\ComfyUI_port_2\ComfyUI\comfy\samplers.py", line 556, in ksampler
    sampler_function = getattr(k_diffusion_sampling, "sample_{}".format(sampler_name))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'comfy.k_diffusion.sampling' has no attribute 'sample_ddim'

Prompt executed in 1.86 seconds
```

![immagine](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/160387045/2ba55047-06f7-41b1-b408-ddc7d21fd097)

**Comment by tester4488** [comment]
### ComfyUI Revision: 2149 [059773a6] | Released on '2024-04-28'

**Comment by tester4488** [comment]
roll back

E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack>git branch
  Main
* tempo

E:\SD\ComfyUI_port_2\ComfyUI\custom_nodes\ComfyUI-Impact-Pack>git log -1
commit 8ffc4efcd6a12649ba5f524602dd24a74ea8145b (HEAD -> tempo)
Author: Dr.Lt.Data <dr.lt.data@gmail.com>
Date:   Tue Apr 9 21:16:29 2024 +0900

    fix: better compatibility with other nodes.

    https://github.com/ltdrdata/ComfyUI-Impact-Pack/issues/547

**Comment by tester4488** [comment]
ok 
![immagine](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/160387045/3197bcee-ca44-402e-8b12-981ebb1d431e)

commit https://github.com/ltdrdata/ComfyUI-Impact-Pack/commit/8ffc4efcd6a12649ba5f524602dd24a74ea8145b (HEAD -> tempo)  
works perfectly

**Comment by ltdrdata** [comment]
I just fixed it. Update and try again.

**Comment by tester4488** [comment]
![immagine](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/160387045/18261f3f-9cc8-4183-83b9-886095c73d97)

yes works but now the scheduler cant be pass by UE nodes, think becauza now the list its different
![immagine](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/160387045/b78f4c8f-09a5-4ab3-bc81-fc4de287bdd5)
![immagine](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/160387045/3f17c15d-97db-4673-ae75-273d7a488c90)

**Comment by ltdrdata** [comment]
![image](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/128333288/3ee896f3-45b2-456f-b797-7bb5da186841)

`Impact Scheduler Adapter` node is added.

**Comment by tester4488** [comment]
perfect works perfectly
![immagine](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/160387045/4b883fd5-b1b3-4193-bfee-092dccb0cd61)

thanks
