### ISSUE TITLE
[Bug?] Problems with ultralytics==8.2.5

### ISSUE THREAD

**Issue by curiousjp** [ltdrdata/ComfyUI-Impact-Pack#577]
Hi there,

I recently migrated a Comfy setup to a new WSL2 Ubuntu environment, and after reinstalling Impact, would run into problems detailing (logs at the bottom) that seem to arise from ultralytics' dependency on pandas. Downgrading from ultralytics 8.2.5 to 8.1.10 (known good on previous setup) seems to have resolved the issue - while not an Impact problem, I was wondering if any other users had experienced similar issues and whether it was pinning the version in requirements.txt

Thanks for all your hard work on this project.

```
!!! Exception during processing!!! numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
Traceback (most recent call last):
  File "/home/curious/ai/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/home/curious/ai/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/home/curious/ai/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/home/curious/ai/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 1301, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask, cnet_pil_list = FaceDetailer.enhance_face(
  File "/home/curious/ai/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/modules/impact/impact_pack.py", line 486, in enhance_face
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size, detailer_hook=detailer_hook)
  File "/home/curious/ai/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 106, in detect
    detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
  File "/home/curious/ai/ComfyUI/custom_nodes/ComfyUI-Impact-Pack/impact_subpack/impact/subcore.py", line 33, in inference_bbox
    pred = model(image, conf=confidence, device=device)
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 176, in __call__
    return self.predict(source, stream, **kwargs)
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/ultralytics/engine/model.py", line 445, in predict
    self.predictor.setup_model(model=self.model, verbose=is_cli)
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/ultralytics/engine/predictor.py", line 297, in setup_model
    self.model = AutoBackend(
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 124, in __init__
    ) = self._model_type(w)
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/ultralytics/nn/autobackend.py", line 644, in _model_type
    sf = list(export_formats().Suffix)  # export suffixes
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/ultralytics/engine/exporter.py", line 97, in export_formats
    import pandas  # scope for faster 'import ultralytics'
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/pandas/core/api.py", line 1, in <module>
    from pandas._libs import (
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/pandas/_libs/__init__.py", line 18, in <module>
    from pandas._libs.interval import Interval
  File "interval.pyx", line 1, in init pandas._libs.interval
  File "hashtable.pyx", line 1, in init pandas._libs.hashtable
  File "missing.pyx", line 1, in init pandas._libs.missing
  File "/home/curious/ai/ComfyUI/venv/lib/python3.10/site-packages/pandas/_libs/tslibs/__init__.py", line 39, in <module>
    from pandas._libs.tslibs import dtypes  # pylint: disable=import-self
  File "dtypes.pyx", line 1, in init pandas._libs.tslibs.dtypes
  File "ccalendar.pyx", line 1, in init pandas._libs.tslibs.ccalendar
ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use '<void>numpy._import_array' to disable if you are certain you don't need it).
```

**Comment by ltdrdata** [comment]
Thank you for the report. I just updated requirements to avoid 8.2.5.
