### ISSUE TITLE
Facedetailer fails with batches >1

### ISSUE THREAD

**Issue by GalaxyTimeMachine** [ltdrdata/ComfyUI-Impact-Pack#61]
As the title says. I had a similar problem with a WAS node, and he was able to change it to accept batches, so I'm hoping the same could be done for this.

The error:
```
Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\Image.py", line 3070, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 1120, 3), '|u1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 144, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 67, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 843, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask = FaceDetailer.enhance_face(
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 806, in enhance_face
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\subpack\impact\subcore.py", line 93, in detect
    detected_results = inference_bbox(self.bbox_model, core.tensor2pil(image), threshold)
  File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 14, in tensor2pil
    return Image.fromarray(np.clip(255. * image.cpu().numpy().squeeze(), 0, 255).astype(np.uint8))
  File "F:\ComfyUI_windows_portable\python_embeded\lib\site-packages\PIL\Image.py", line 3073, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 1120, 3), |u1
```

My face detailer workflow looks like this:
![Screenshot 2023-07-31 105456](https://github.com/ltdrdata/ComfyUI-Impact-Pack/assets/52193044/bc2f1cf3-36df-43b0-ad5c-2a6dfc8a0b58)

**Comment by ltdrdata** [comment]
https://github.com/ltdrdata/ComfyUI-extension-tutorials/blob/Main/ComfyUI-Impact-Pack/tutorial/batching-detailer.md
