### ISSUE TITLE
YAML parsing issue with Impact wildcard encoder

### ISSUE THREAD

**Issue by EnragedAntelope** [ltdrdata/ComfyUI-Impact-Pack#680]
Hi,
Thank you for all of your great work!
Lately, many "all in one" YAML files containing wildcards have been posted to CivitAI.

However several throw an error when Impact Wildcard processor loads at start of ComfyUI. Example: https://civitai.com/models/481009/dynamic-wildcard-unleashed-megapack-154-wildcards?modelVersionId=656889 . I confirmed via Notepad++ that it is UTF-8 encoded.

Here is the error:
`Exception in thread Thread-25 (wildcard_load):
Traceback (most recent call last):
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\reader.py", line 89, in peek
    return self.buffer[self.pointer+index]
           ~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\threading.py", line 1045, in _bootstrap_inner
    self.run()
  File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\threading.py", line 982, in run
    self._target(*self._args, **self._kwargs)
  File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 524, in wildcard_load
Flash Attention is available
    read_wildcard_dict(wildcards_path)
  File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 69, in read_wildcard_dict
    yaml_data = yaml.load(f, Loader=yaml.FullLoader)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\__init__.py", line 81, in load
    return loader.get_single_data()
           ^^^^^^^^^^^^^^### Loading: ComfyUI-Manager (V2.48.2)^
^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\constructor.py", line 49, in get_single_data
    node = self.get_single_node()
           ^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 36, in get_single_node
    document = self.compose_document()
               ^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 133, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\composer.py", line 110, in compose_sequence_node
    while not self.check_event(SequenceEndEvent):
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\parser.py", line 98, in check_event
    self.current_event = self.state()
                         ^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\parser.py", line 384, in parse_block_sequence_entry
    if not self.check_token(BlockEntryToken, BlockEndToken):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\scanner.py", line 116, in check_token
    self.fetch_more_tokens()
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\scanner.py", line 255, in fetch_more_tokens
    return self.fetch_plain()
           ^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\scanner.py", line 679, in fetch_plain
    self.tokens.append(self.scan_plain())
                       ^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\scanner.py", line 1290, in scan_plain
    ch = self.peek(length)
         ^^^^^^^^^^^^### ComfyUI Revision: 2413 [f82d09c9] | Released on '2024-07-27'^
^^^^
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\reader.py", line 91, in peek
    self.update(index+1)
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\reader.py", line 153, in update
    self.update_raw()
  File "D:\ComfyUI\venv\Lib\site-packages\yaml\reader.py", line 178, in update_raw
    data = self.stream.read(size)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\encodings\cp1252.py", line 23, in decode
    return codecs.charmap_decode(input,self.errors,decoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8d in position 6701: character maps to <undefined>`

I asked Claude AI what to do. It suggested:
```
This error appears to be related to encoding issues when trying to read a YAML file in your ComfyUI setup. The error suggests that there's a character in the file that can't be decoded using the default encoding (cp1252 in this case). Here's a breakdown of the issue and some potential solutions:

1. Encoding Problem: The error occurs when trying to read a file, likely a YAML configuration file for wildcards in the ComfyUI-Impact-Pack.

2. Specific Error: The 'charmap' codec can't decode byte 0x8d at position 6701 in the file.

To resolve this issue, you can try the following:

1. Check the File Encoding:
   - Open the YAML file (likely located in the ComfyUI-Impact-Pack directory) in a text editor that shows file encoding (like Notepad++ or VS Code).
   - Ensure it's saved in UTF-8 encoding.

2. Convert the File to UTF-8:
   - If the file is not in UTF-8, open it in a text editor and save it as UTF-8.

3. Modify the Python Script:
   - Locate the `read_wildcard_dict` function in the `wildcards.py` file.
   - Change how the file is opened to explicitly use UTF-8 encoding:

   ```python
   with open(wildcards_path, 'r', encoding='utf-8') as f:
       yaml_data = yaml.load(f, Loader=yaml.FullLoader)
   ```

4. Check for Invalid Characters:
   - Look around position 6701 in the file for any unusual or non-standard characters.
   - Remove or replace any problematic characters.

5. Update YAML Library:
   - Ensure you're using the latest version of the PyYAML library.
   - You can update it using pip: `pip install --upgrade pyyaml`

6. Use a Different YAML Parser:
   - If the problem persists, you might want to try a different YAML parser like `ruamel.yaml`, which has better Unicode support.

If you continue to face issues, you may want to share more details about the specific YAML file causing the problem (without revealing any sensitive information) or reach out to the ComfyUI-Impact-Pack maintainers for further assistance.
```

**Comment by ltdrdata** [comment]
After downloading and checking, I couldn't find any issues with those files (both allinone v21 and v21).
It seems that the file causing problems for you is a different one.

**Comment by ltdrdata** [comment]
Anway, I have fixed the part where potential issues could occur.

**Comment by ghost** [comment]
Thank you! Will test again later today, I appreciate the quick help!
