### ISSUE TITLE
Comfy-UI Impact Pact Failed Installation

### ISSUE THREAD

**Issue by DAWiguna** [ltdrdata/ComfyUI-Impact-Pack#726]
I just installed ComfyUI through Pinokio. It ran great!

Then I click Manager, Custom Nodes, and install Impact Pact. It always ended with this:

ENOENT: no such file or directory, stat 'D:\pinokio\api\comfy.git\{{input.event[0]}}'

The ComfyUI stopped altogether. Anyone has the same problem?

btw this was on terminal before ComfyUI stopped (and I have to reinstall thoroughly)

[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-02 19:11:00.318025
** Platform: Windows
** Python version: 3.10.14 | packaged by conda-forge | (main, Mar 20 2024, 12:40:08) [MSC v.1938 64 bit (AMD64)]
** Python executable: D:\pinokio\api\comfy.git\app\env\Scripts\python.exe
** ComfyUI Path: D:\pinokio\api\comfy.git\app
** Log path: D:\pinokio\api\comfy.git\app\comfyui.log
Prestartup times for custom nodes:
   1.3 seconds: D:\pinokio\api\comfy.git\app\custom_nodes\ComfyUI-Manager

Traceback (most recent call last):
  File "D:\pinokio\api\comfy.git\app\main.py", line 90, in <module>
    import execution
  File "D:\pinokio\api\comfy.git\app\execution.py", line 13, in <module>
    import nodes
  File "D:\pinokio\api\comfy.git\app\nodes.py", line 21, in <module>
    import comfy.diffusers_load
  File "D:\pinokio\api\comfy.git\app\comfy\diffusers_load.py", line 3, in <module>
    import comfy.sd
  File "D:\pinokio\api\comfy.git\app\comfy\sd.py", line 5, in <module>
    from comfy import model_management
  File "D:\pinokio\api\comfy.git\app\comfy\model_management.py", line 143, in <module>
    total_vram = get_total_memory(get_torch_device()) / (1024 * 1024)
  File "D:\pinokio\api\comfy.git\app\comfy\model_management.py", line 112, in get_torch_device
    return torch.device(torch.cuda.current_device())
  File "D:\pinokio\api\comfy.git\app\env\lib\site-packages\torch\cuda\__init__.py", line 778, in current_device
    _lazy_init()
  File "D:\pinokio\api\comfy.git\app\env\lib\site-packages\torch\cuda\__init__.py", line 284, in _lazy_init
    raise AssertionError("Torch not compiled with CUDA enabled")
AssertionError: Torch not compiled with CUDA enabled

(env) (base) D:\pinokio\api\comfy.git\app>

**Comment by ltdrdata** [comment]
You need to reinstall torch.
You torch installation is invalid.
