### ISSUE TITLE
open in sam detector is  error

### ISSUE THREAD

**Issue by Lyqxyz** [ltdrdata/ComfyUI-Impact-Pack#733]
[INFO] ComfyUI-Impact-Pack: Loading SAM model 'I:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\models'
[INFO] ComfyUI-Impact-Pack: SAM model loaded.
Exception in thread Thread-12 (async_prepare_sam):
Traceback (most recent call last):
  File "threading.py", line 1045, in _bootstrap_inner
  File "threading.py", line 982, in run
  File "I:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_server.py", line 77, in async_prepare_sam
    sam_model = sam_model_registry[model_kind](checkpoint=model_name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\segment_anything\build_sam.py", line 38, in build_sam_vit_b
    return _build_sam(
           ^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\segment_anything\build_sam.py", line 105, in _build_sam
    state_dict = torch.load(f)
                 ^^^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\ultralytics\utils\patches.py", line 86, in torch_load
    return _torch_load(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 1004, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "I:\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\python_embeded\Lib\site-packages\torch\serialization.py", line 456, in __init__
    super().__init__(torch._C.PyTorchFileReader(name_or_buffer))
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory
![aa9dc59d74180a64c43628467e2608f](https://github.com/user-attachments/assets/f9ca01bf-015c-4531-b97b-772e4e4e929d)

**Comment by ltdrdata** [comment]
It seems that your model file is invalid.

**Comment by Lyqxyz** [comment]
> It seems that your model file is invalid.
model alldownloaded   and   all other functions run very well，ultralytics version required?

**Comment by ltdrdata** [comment]
> > It seems that your model file is invalid.
> > model alldownloaded   and   all other functions run very well，ultralytics version required?

Check the sam model file.

**Comment by Lyqxyz** [comment]
> > > It seems that your model file is invalid.
> > > model alldownloaded   and   all other functions run very well，ultralytics version required?
> 
> Check the sam model file.



> > > It seems that your model file is invalid.
> > > model alldownloaded   and   all other functions run very well，ultralytics version required?
> 
> Check the sam model file.
All models have been downloaded, but there are still errors
![170294bd6f0381195a8c80e286edc1c](https://github.com/user-attachments/assets/a7108adb-719d-4b14-8581-1d1d23f7b137)

**Comment by ltdrdata** [comment]
What model did you selected?
