### ISSUE TITLE
[Bug] Concat Conditionings breaks after switching workflow

### ISSUE THREAD

**Issue by LukeG89** [ltdrdata/ComfyUI-Impact-Pack#755]
https://github.com/user-attachments/assets/2d7cc272-8f9c-4038-b152-6726b3eac906

Console errors (just a few because they are all the same):
```
impact-pack.js:541 Uncaught TypeError: Cannot read properties of undefined (reading 'options')
    at nodeType.onConnectionsChange (impact-pack.js:541:22)
    at ComfyNode.disconnectInput (litegraph.es.js:3959:18)
    at __LGraphCanvas.processMouseDown (litegraph.es.js:6000:33)
    at LGraphCanvas.processMouseDown (changeTracker.ts:179:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:102:27)
    at LGraphCanvas.processMouseDown (app.ts:1191:40)
nodeType.onConnectionsChange @ impact-pack.js:541
disconnectInput @ litegraph.es.js:3959
processMouseDown @ litegraph.es.js:6000
LGraphCanvas.processMouseDown @ changeTracker.ts:179
LGraphCanvas.processMouseDown @ simpleTouchSupport.ts:102
LGraphCanvas.processMouseDown @ app.ts:1191
Mostra 2 altri frame
Mostra meno
impact-pack.js:541 Uncaught TypeError: Cannot read properties of undefined (reading 'options')
    at nodeType.onConnectionsChange (impact-pack.js:541:22)
    at ComfyNode.disconnectInput (litegraph.es.js:3959:18)
    at __LGraphCanvas.processMouseDown (litegraph.es.js:6000:33)
    at LGraphCanvas.processMouseDown (changeTracker.ts:179:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:102:27)
    at LGraphCanvas.processMouseDown (app.ts:1191:40)
nodeType.onConnectionsChange @ impact-pack.js:541
disconnectInput @ litegraph.es.js:3959
processMouseDown @ litegraph.es.js:6000
LGraphCanvas.processMouseDown @ changeTracker.ts:179
LGraphCanvas.processMouseDown @ simpleTouchSupport.ts:102
LGraphCanvas.processMouseDown @ app.ts:1191
Mostra 2 altri frame
Mostra meno
impact-pack.js:541 Uncaught TypeError: Cannot read properties of undefined (reading 'options')
    at nodeType.onConnectionsChange (impact-pack.js:541:22)
    at ComfyNode.disconnectInput (litegraph.es.js:3959:18)
    at __LGraphCanvas.processMouseDown (litegraph.es.js:6000:33)
    at LGraphCanvas.processMouseDown (changeTracker.ts:179:34)
    at LGraphCanvas.processMouseDown (simpleTouchSupport.ts:102:27)
    at LGraphCanvas.processMouseDown (app.ts:1191:40)
nodeType.onConnectionsChange @ impact-pack.js:541
disconnectInput @ litegraph.es.js:3959
processMouseDown @ litegraph.es.js:6000
LGraphCanvas.processMouseDown @ changeTracker.ts:179
LGraphCanvas.processMouseDown @ simpleTouchSupport.ts:102
LGraphCanvas.processMouseDown @ app.ts:1191
Mostra 2 altri frame
Mostra meno
impact-pack.js:541 Uncaught TypeError: Cannot read properties of undefined (reading 'options')
    at nodeType.onConnectionsChange (impact-pack.js:541:22)
    at ComfyNode.connect (litegraph.es.js:3736:21)
    at __LGraphCanvas.processMouseUp (litegraph.es.js:6526:29)
    at LGraphCanvas.processMouseUp (changeTracker.ts:173:32)
nodeType.onConnectionsChange @ impact-pack.js:541
connect @ litegraph.es.js:3736
processMouseUp @ litegraph.es.js:6526
LGraphCanvas.processMouseUp @ changeTracker.ts:173
Mostra 2 altri frame
Mostra meno
```

Debug logs:
```
E:\>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build --preview-size 1024 --front-end-version Comfy-Org/ComfyUI_frontend@latest
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-09-24 22:29:55.694322
** Platform: Windows
** Python version: 3.11.9 (tags/v3.11.9:de54cf5, Apr  2 2024, 10:12:12) [MSC v.1938 64 bit (AMD64)]
** Python executable: E:\python_embeded\python.exe
** ComfyUI Path: E:\ComfyUI
** Log path: E:\comfyui.log

Prestartup times for custom nodes:
   1.2 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 8192 MB, total RAM 65277 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 3070 Ti Laptop GPU : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI\web_custom_versions\Comfy-Org_ComfyUI_frontend\1.2.63
E:\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Impact-Pack (V7.7)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
[Impact Pack] Wildcards loading done.
### Loading: ComfyUI-Manager (V2.51.1)
### ComfyUI Revision: 2727 [fdf37566] | Released on '2024-09-24'

Import times for custom nodes:
   0.0 seconds: E:\ComfyUI\custom_nodes\websocket_image_save.py
   0.2 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Manager
   0.5 seconds: E:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
FETCH DATA from: E:\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
```

**Comment by ltdrdata** [comment]
This is fixed
