### ISSUE TITLE
Fails to load AnyPipetoBasic

### ISSUE THREAD

**Issue by sanluis** [ltdrdata/ComfyUI-Impact-Pack#758]
### Loading: ComfyUI-Impact-Pack (V7.7.2)
Traceback (most recent call last):
  File "E:\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1993, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 103, in <module>
    "AnyPipeToBasic": AnyPipeToBasic,
                      ^^^^^^^^^^^^^^
NameError: name 'AnyPipeToBasic' is not defined

[Impact Pack] Wildcards loading done.Cannot import E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: name 'AnyPipeToBasic' is not defined

AnyPipeToBasic is defined in file pipe.py and AnyPipeToBasic uses module any_typ defined in utils.py. I do not know what is wrong in the python code that makes __init__.py to fail.

**Comment by ltdrdata** [comment]
goto " E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack" in cmd.
And execute this
```
git status
```

What is displayed?

**Comment by sanluis** [comment]
E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack>git status
On branch Main
Your branch is up to date with 'origin/Main'.

nothing to commit, working tree clean

E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack>python --version
Python 3.11.8

**Comment by ltdrdata** [comment]
Please disable all custom nodes except for the Impact Pakc and test it.

**Comment by sanluis** [comment]
Installing just ComfyUI-Impact-Pack produces no failure, then one of the other nodes is causing this issue, I will install again some of the other nodes and I will try to identify which one is causing this conflict,

E:\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
Total VRAM 6144 MB, total RAM 32580 MB
pytorch version: 2.4.1+cu124
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 2060 : cudaMallocAsync
Using pytorch cross attention
[Prompt Server] web root: E:\ComfyUI_windows_portable\ComfyUI\web
Adding extra search path checkpoints E:/ComfyUI_windows_portable/models/checkpoints
Adding extra search path clip E:/ComfyUI_windows_portable/models/clip/
Adding extra search path clip_vision E:/ComfyUI_windows_portable/models/clip_vision/
Adding extra search path configs E:/ComfyUI_windows_portable/models/configs/
Adding extra search path controlnet E:/ComfyUI_windows_portable/models/controlnet/
Adding extra search path embeddings E:/ComfyUI_windows_portable/models/embeddings/
Adding extra search path loras E:/ComfyUI_windows_portable/models/loras/
Adding extra search path upscale_models E:/ComfyUI_windows_portable/models/upscale_models/
Adding extra search path vae E:/ComfyUI_windows_portable/models/vae/
E:\ComfyUI_windows_portable\python_embeded\Lib\site-packages\kornia\feature\lightglue.py:44: FutureWarning: `torch.cuda.amp.custom_fwd(args...)` is deprecated. Please use `torch.amp.custom_fwd(args..., device_type='cuda')` instead.
  @torch.cuda.amp.custom_fwd(cast_inputs=torch.float32)
### Loading: ComfyUI-Impact-Pack (V7.7.2)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.7)
[WARN] ComfyUI-Impact-Pack: `ComfyUI` or `ComfyUI-Manager` is an outdated version.

Import times for custom nodes:
   1.9 seconds: E:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

Starting server

To see the GUI go to: http://127.0.0.1:8188
[Impact Pack] Wildcards loading done.
