### ISSUE TITLE
Cannot use lora weight in ImpactWildcardEncode

### ISSUE THREAD

**Issue by llotenberg** [ltdrdata/ComfyUI-Impact-Pack#790]
Attempting to add a weight to a LoRA in the latest version of this module produces this error:

```
!!! Exception during processing !!! multiple repeat at position 6
Traceback (most recent call last):
  File "D:\Programs\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Programs\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "D:\Programs\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "D:\Programs\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "D:\Programs\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 2207, in doit
    model, clip, conditioning = impact.wildcards.process_with_loras(wildcard_opt=populated, model=kwargs['model'], clip=kwargs['clip'], seed=kwargs['seed'], processed=processed)
  File "D:\Programs\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 358, in process_with_loras
    loras = extract_lora_values(pass1)
  File "D:\Programs\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 297, in extract_lora_values
    if is_numeric_string(sub_item):
  File "D:\Programs\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\wildcards.py", line 262, in is_numeric_string
    return re.match(r'^-?\d?+(\.\d+)?$', input_str) is not None
  File "C:\Python3\lib\re.py", line 190, in match
    return _compile(pattern, flags).match(string)
  File "C:\Python3\lib\re.py", line 303, in _compile
    p = sre_compile.compile(pattern, flags)
  File "C:\Python3\lib\sre_compile.py", line 788, in compile
    p = sre_parse.parse(p, flags)
  File "C:\Python3\lib\sre_parse.py", line 955, in parse
    p = _parse_sub(source, state, flags & SRE_FLAG_VERBOSE, 0)
  File "C:\Python3\lib\sre_parse.py", line 444, in _parse_sub
    itemsappend(_parse(source, state, verbose, nested + 1,
  File "C:\Python3\lib\sre_parse.py", line 672, in _parse
    raise source.error("multiple repeat",
re.error: multiple repeat at position 6
```

This only occurs on the latest version; reverting to 7.10.3 fixed the issue. I was attempting to use weights greater than 1, which may be relevant since the latest version tried to remove the requirement for a leading zero when using fractional weights. (I did not check to see if that functionality worked properly or not.)

**Comment by ltdrdata** [comment]
Fixed
