### ISSUE TITLE
custom nodes: DLL load failed while importing _ext: The specified procedure could not be found.

### ISSUE THREAD

**Issue by rvion** [ltdrdata/ComfyUI-Impact-Pack#8]
Hi there, I'm trying to install ComfyUI-Impact-Pack so I can ensure it's compatible with CushyStudio https://github.com/rvion/CushyStudio

I think I have those properly setup 

```
openmim
segment-anything
pycocotools
onnxruntime
mim install
```
and 
```
mmcv==2.0.0, mmdet==3.0.0, mmengine==0.7.2
```

but when ComfyUI starts, it gives 

```
### Loading: ComfyUI-Impact-Pack
Traceback (most recent call last):
  File "C:\Users\user\dev\intuition\ComfyUI\nodes.py", line 1237, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "C:\Users\user\dev\intuition\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 19, in <module>
    from .impact_pack import NODE_CLASS_MAPPINGS
  File "C:\Users\user\dev\intuition\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\impact_pack.py", line 22, in <module>       
    from mmdet.apis import (inference_detector, init_detector)
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\apis\__init__.py", line 2, in <module>
    from .det_inferencer import DetInferencer
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\apis\det_inferencer.py", line 21, in <module>
    from mmdet.evaluation import INSTANCE_OFFSET
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\evaluation\__init__.py", line 3, in <module>
    from .metrics import *  # noqa: F401,F403
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\evaluation\metrics\__init__.py", line 3, in <module>    
    from .coco_metric import CocoMetric
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\evaluation\metrics\coco_metric.py", line 16, in <module>
    from mmdet.datasets.api_wrappers import COCO, COCOeval
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\datasets\__init__.py", line 14, in <module>
    from .utils import get_loading_pipeline
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\datasets\utils.py", line 5, in <module>
    from mmdet.datasets.transforms import LoadAnnotations, LoadPanopticAnnotations
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\datasets\transforms\__init__.py", line 6, in <module>
    from .formatting import ImageToTensor, PackDetInputs, ToTensor, Transpose
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\datasets\transforms\formatting.py", line 9, in <module>
    from mmdet.structures.bbox import BaseBoxes
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\structures\bbox\__init__.py", line 2, in <module>
    from .base_boxes import BaseBoxes
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\structures\bbox\base_boxes.py", line 9, in <module>
    from mmdet.structures.mask.structures import BitmapMasks, PolygonMasks
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\structures\mask\__init__.py", line 3, in <module>
    from .structures import (BaseInstanceMasks, BitmapMasks, PolygonMasks,
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmdet\structures\mask\structures.py", line 12, in <module>
    from mmcv.ops.roi_align import roi_align
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmcv\ops\__init__.py", line 2, in <module>
    from .active_rotated_filter import active_rotated_filter
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmcv\ops\active_rotated_filter.py", line 10, in <module>
    ext_module = ext_loader.load_ext(
  File "C:\Users\user\dev\intuition\venv\lib\site-packages\mmcv\utils\ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "C:\python31010\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ImportError: DLL load failed while importing _ext: The specified procedure could not be found.

Cannot import C:\Users\user\dev\intuition\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: DLL load failed while importing _ext: The specified procedure could not be found.
xformers version: 0.0.17+b89a493.d20230304
```

any idea how to fix this ?

**Comment by ltdrdata** [comment]
In that case you can build manually.

1. Install visual studio with C++.
2. launch developer command-line.
3. goto comfyui directory
4. pip install pycocotools
5. mim install mmcv

maybe the step 4 is most dirty part.
it will build from source during install and takes long time.


I am providing pre-built package during install step. But, it looks like it is not compatible with yours.

**Comment by rvion** [comment]
The problem was probably related to some beta torch version I setup in january. 
a cleaner reinstall solved it, thanks !

**Comment by Thanh1122kkll** [comment]
I followed the steps mentioned above, but I still get the error: 
File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 3, in <module>
import cv2
ImportError: DLL load failed while importing cv2: The specified module could not be found.any way to deal with this, mine is window 10pro N

**Comment by ltdrdata** [comment]
> I followed the steps mentioned above, but I still get the error: File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\utils.py", line 3, in import cv2 ImportError: DLL load failed while importing cv2: The specified module could not be found.any way to deal with this, mine is window 10pro N

`D:\ComfyUI_windows_portable\python_embeded\python.exe -m pip uninstall opencv-python opencv-python-headless`

And try again.
