### ISSUE TITLE
(IMPORT FAILED): D:\Ai\换脸\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack

### ISSUE THREAD

**Issue by wbqb986** [ltdrdata/ComfyUI-Impact-Pack#801]
[Impact Pack] Failed to import due to several dependencies are missing!!!!
Traceback (most recent call last):
  File "D:\Ai\\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2001, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "D:\Ai\\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 53, in <module>
    raise e
  File "D:\Ai\\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\__init__.py", line 31, in <module>
    import impact.subpack_nodes  # This import must be done before cv2.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'impact.subpack_nodes'

Cannot import D:\Ai\\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'impact.subpack_nodes'

**Comment by thinkingjimmy** [comment]
same issue

**Comment by ltdrdata** [comment]
This is an issue that occurs due to having multiple versions of opencv installed.
Update all packages starting with opencv listed in pip freeze to their latest versions.

This issue typically occurs when installing certain custom nodes that downgrade dependencies to lower versions.
