### ISSUE TITLE
ValueError: Input image size (352*352) doesn't match model (224*224).

### ISSUE THREAD

**Issue by Cokeheart** [ltdrdata/ComfyUI-Impact-Pack#820]
Prompt executed in 4.47 seconds
got prompt
!!! Exception during processing !!! Input image size (352*352) doesn't match model (224*224).
Traceback (most recent call last):
  File "I:\ComfyUI-aki-v1.4\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "I:\ComfyUI-aki-v1.4\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "I:\ComfyUI-aki-v1.4\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "I:\ComfyUI-aki-v1.4\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "I:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 102, in doit
    segs = bbox_detector.detect(image, threshold, dilation, crop_factor, drop_size, detailer_hook)
  File "I:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 2032, in detect
    mask = self.detect_combined(image, bbox_threshold, bbox_dilation)
  File "I:\ComfyUI-aki-v1.4\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 2063, in detect_combined
    mask, _, _ = CLIPSeg().segment_image(image, prompt, self.blur, threshold, dilation_factor)
  File "I:\ComfyUI-aki-v1.4\custom_nodes\clipseg.py", line 129, in segment_image
    outputs = model(**input_prc)
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\clipseg\modeling_clipseg.py", line 1436, in forward
    if conditional_embeddings.shape[0] != pixel_values.shape[0]:
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\clipseg\modeling_clipseg.py", line 870, in forward
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1532, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\torch\nn\modules\module.py", line 1541, in _call_impl
    return forward_call(*args, **kwargs)
  File "I:\ComfyUI-aki-v1.4\python\lib\site-packages\transformers\models\clipseg\modeling_clipseg.py", line 211, in forward
ValueError: Input image size (352*352) doesn't match model (224*224).
Could you please help to solve this problem? Thank you very much.

**Comment by ltdrdata** [comment]
You need to downgrade transformers.
Or you can use forked version of the clipseg.

https://github.com/comfyanonymous/ComfyUI/issues/5402#issuecomment-2444855775
