### ISSUE TITLE
Node `Make Mask Batch` gives error: name 'utils' is not defined

### ISSUE THREAD

**Issue by LichAcademy** [ltdrdata/ComfyUI-Impact-Pack#831]
I am getting this error:

```md
!!! Exception during processing !!! name 'utils' is not defined
Traceback (most recent call last):
  File "C:\Users\professorlich\AI_projects\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\professorlich\AI_projects\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\professorlich\AI_projects\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\professorlich\AI_projects\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\professorlich\AI_projects\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\util_nodes.py", line 504, in doit
    masks = [utils.make_3d_mask(value) for value in kwargs.values()]
             ^^^^^
NameError: name 'utils' is not defined
```
![impact_clipv2_subs_3](https://github.com/user-attachments/assets/5106079f-774b-4c23-b916-6c099442ee33)

Amazingly, I can use use `Make Mask List`, and then `Mask List to Mask Batch` without issues. 🤔 Am I doing something wrong?

**Comment by ltdrdata** [comment]
This is fixed already. Update to latest vesion.
