### ISSUE TITLE
Error after updating just now

### ISSUE THREAD

**Issue by EnragedAntelope** [ltdrdata/ComfyUI-Impact-Pack#867]
```
Install: install script for 'D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack'
[!]
[!] WARN: The `COMFYUI_MODEL_PATH` environment variable is not set. Assuming `D:\ComfyUI\models` as the ComfyUI path.
[!] Traceback (most recent call last):
 ### ComfyUI-Impact-Pack: Check dependencies
 [!]### ComfyUI-Impact-Pack: Check basic models
   File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 121, in <module>
 [!][ERROR] ComfyUI-Impact-Pack: Dependency installation has failed. Please install manually.
     install()
[!]   File "D:\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\install.py", line 113, in install
[!]     shutil.rmtree(subpack_path)
[!]   File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\shutil.py", line 787, in rmtree
[!]     return _rmtree_unsafe(path, onerror)
[!]            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[!]   File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\shutil.py", line 629, in _rmtree_unsafe
[!]     _rmtree_unsafe(fullname, onerror)
[!]   File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\shutil.py", line 629, in _rmtree_unsafe
[!]     _rmtree_unsafe(fullname, onerror)
[!]   File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\shutil.py", line 629, in _rmtree_unsafe
[!]     _rmtree_unsafe(fullname, onerror)
[!]   File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\shutil.py", line 634, in _rmtree_unsafe
[!]     onerror(os.unlink, fullname, sys.exc_info())
[!]   File "C:\Users\Default.LivingRoomPC\.pyenv\pyenv-win\versions\3.11.9\Lib\shutil.py", line 632, in _rmtree_unsafe
[!]     os.unlink(fullname)
[!] PermissionError: [WinError 5] Access is denied: 'D:\\ComfyUI\\custom_nodes\\ComfyUI-Impact-Pack\\impact_subpack\\.git\\objects\\1e\\2aa01a101cd756211f8fefd0439b2e5c3ddb4d'
```

**Comment by ltdrdata** [comment]
Uninstall Impact Pack and reinstall Impact Pack and Impact Subpack.

**Comment by EnragedAntelope** [comment]
This appears to have fixed it, thanks.
