### ISSUE TITLE
"Cannot import" error in ComfyUI log

### ISSUE THREAD

**Issue by fafayqa** [ltdrdata/ComfyUI-Impact-Pack#868]
I am using latest ComfyUI Portable v0.3.9.10 (https://github.com/comfyanonymous/ComfyUI/releases) .

[2024-12-22 20:06:26.311] Cannot import Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack module for custom nodes: No module named 'segment_anything'
[2024-12-22 20:06:26.317] Total VRAM 12288 MB, total RAM 64599 MB
[2024-12-22 20:06:26.317] pytorch version: 2.5.1+cu124
[2024-12-22 20:06:26.318] Set vram state to: NORMAL_VRAM
[2024-12-22 20:06:26.318] Device: cuda:0 NVIDIA GeForce RTX 3060 : cudaMallocAsync
[2024-12-22 20:06:26.621] ### Loading: ComfyUI-Manager (V2.55.5)
[2024-12-22 20:06:26.735] ### ComfyUI Version: v0.3.9-10-g57f330c | Released on '2024-12-22'
[2024-12-22 20:06:26.919] Traceback (most recent call last):
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\nodes.py", line 2075, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 995, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\__init__.py", line 23, in <module>
    from .nodes import NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS
  File "Z:\_PSTART_\_APPS_\_AI_\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-reactor-node\nodes.py", line 15, in <module>
    from insightface.app.common import Face
ModuleNotFoundError: No module named 'insightface'

**Comment by ltdrdata** [comment]
This issue is not related to Impact Pack.
You need to install insightface manually.
https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#installation

**Comment by fafayqa** [comment]
> This issue is not related to Impact Pack. You need to install insightface manually. https://github.com/Gourieff/comfyui-reactor-node?tab=readme-ov-file#installation

I did installed it manually using standalone/portable Git exactly the same way I am installing other nodes using their respective Github .git file - most of the show no error in the log of ComfyUI when it starts, only like 5 of them do.
Could you elaborate more on the problem?
BTW this is not whole log, I thought only this part is relevant here, but I can paste the whole log if you will?

**Comment by ltdrdata** [comment]
> I did installed it manually using standalone/portable Git exactly the same way I am installing other nodes using their respective Github .git file - most of the show no error in the log of ComfyUI when it starts, only like 5 of them do.
> Could you elaborate more on the problem?
> BTW this is not whole log, I thought only this part is relevant here, but I can paste the whole log if you will?

Each import error requires a different fix.  
Each custom node has its own installation method.  
Typically, installing the `requirements.txt` using pip is sufficient, but in cases like insightface, a special installation method is required, as shown in the link above.
