### ISSUE TITLE
[ERROR] PixelTiledKSampleUpscalerProvider: ComfyUI_TiledKSampler custom node isn't installed. You must install BlenderNeko/ComfyUI_TiledKSampler extension to use this node.

### ISSUE THREAD

**Issue by bluenyx** [ltdrdata/ComfyUI-Impact-Pack#872]
To use PixelTiledKSampleUpscalerProvider, you will receive the error "ComfyUI_TiledKSampler custom node isn't installed. You must install BlenderNeko/ComfyUI_TiledKSampler extension to use this node" error.

Do I also need to use that custom node to use the Impact pack?

# ComfyUI Error Report
## Error Details
- **Node ID:** 51
- **Node Type:** PixelTiledKSampleUpscalerProvider
- **Exception Type:** Exception
- **Exception Message:** [ERROR] PixelTiledKSampleUpscalerProvider: ComfyUI_TiledKSampler custom node isn't installed. You must install BlenderNeko/ComfyUI_TiledKSampler extension to use this node.
Using xformers attention in VAE
Using xformers attention in VAE
VAE load device: cuda:0, offload device: cpu, dtype: torch.bfloat16
CLIP model load device: cuda:0, offload device: cpu, current: cpu, dtype: torch.float16
FETCH DATA from: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json [DONE]
[ComfyUI Manager API] Failed to try install - Unknown custom node url 'https://github.com/BlenderNeko/ComfyUI_TiledKSampler'
!!! Exception during processing !!! [ERROR] PixelTiledKSampleUpscalerProvider: ComfyUI_TiledKSampler custom node isn't installed. You must install BlenderNeko/ComfyUI_TiledKSampler extension to use this node.
Traceback (most recent call last):
  File "C:\Users\bluen\Documents\AI\ComfyUI_Portable\ComfyUI\execution.py", line 327, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bluen\Documents\AI\ComfyUI_Portable\ComfyUI\execution.py", line 202, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bluen\Documents\AI\ComfyUI_Portable\ComfyUI\execution.py", line 174, in _map_node_over_list
    process_inputs(input_dict, i)
  File "C:\Users\bluen\Documents\AI\ComfyUI_Portable\ComfyUI\execution.py", line 163, in process_inputs
    results.append(getattr(obj, func)(**inputs))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bluen\Documents\AI\ComfyUI_Portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 1010, in doit
    raise Exception("[ERROR] PixelTiledKSampleUpscalerProvider: ComfyUI_TiledKSampler custom node isn't installed. You must install BlenderNeko/ComfyUI_TiledKSampler extension to use this node.")
Exception: [ERROR] PixelTiledKSampleUpscalerProvider: ComfyUI_TiledKSampler custom node isn't installed. You must install BlenderNeko/ComfyUI_TiledKSampler extension to use this node.

Prompt executed in 4.02 seconds

## Additional Context
(Please add any additional context or steps to reproduce the error here)

![image](https://github.com/user-attachments/assets/3212f616-3556-4a36-8d78-4735c4ce946a)

**Comment by ltdrdata** [comment]
Some custom nodes internally depend on other node packs. Currently, the tiledksampler of blender_neko is not functioning properly, so installing https://github.com/LtDrData/ComfyUI_TiledKSampler will ensure it works correctly.
