### ISSUE TITLE
BBox detector missing treshold (but it exists)

### ISSUE THREAD

**Issue by DaveScream** [ltdrdata/ComfyUI-Impact-Pack#91]
Error occurred when executing BboxDetectorSEGS:

to_binary_mask() missing 1 required positional argument: 'threshold'

  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "D:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\detectors.py", line 83, in doit
    segs = bbox_detector.detect(image, threshold, dilation, crop_factor, drop_size)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1256, in detect
    mask = self.detect_combined(image, bbox_threshold, bbox_dilation)
  File "D:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1276, in detect_combined
    mask = to_binary_mask(mask)

**Comment by ltdrdata** [comment]
I just updated this, try latest version.

**Comment by monkeyguy** [comment]
I'm getting a similar error using the CLIPSegDetectorProvider

```
!!! Exception during processing !!!
Traceback (most recent call last):
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 997, in doit
    enhanced_img, cropped_enhanced, cropped_enhanced_alpha, mask = FaceDetailer.enhance_face(
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\impact_pack.py", line 960, in enhance_face
    segs = bbox_detector.detect(image, bbox_threshold, bbox_dilation, bbox_crop_factor, drop_size)
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1256, in detect
    mask = self.detect_combined(image, bbox_threshold, bbox_dilation)
  File "C:\SD\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack\modules\impact\core.py", line 1276, in detect_combined
    mask = to_binary_mask(mask)
TypeError: to_binary_mask() missing 1 required positional argument: 'threshold'
```

**Comment by ltdrdata** [comment]
Update your Impact Pack to latest version.
